:- module(codegen, [rust_source/1, javascript_source/1]).

:- use_module('0_schema').
:- use_module('2_patterns').

rust_source(Source) :-
    findall(Block, rust_decl(Block), Blocks),
    atomics_to_string(["// generated by swi-typespec-lab\n\n"|Blocks], "", Source).

rust_decl(Block) :-
    schema:type_decl(Name, model(Fields)),
    pascal(Name, RustName),
    maplist(rust_field, Fields, FieldLines),
    atomics_to_string(FieldLines, "", FieldsSource),
    format(string(Block), "#[derive(Debug, Clone)]\npub struct ~s {\n~s}\n\n", [RustName, FieldsSource]).
rust_decl(Block) :-
    schema:type_decl(Name, union(Variants)),
    pascal(Name, RustName),
    maplist(rust_variant, Variants, VariantLines),
    atomics_to_string(VariantLines, "", VariantsSource),
    format(string(Block), "#[derive(Debug, Clone)]\npub enum ~s {\n~s}\n\n", [RustName, VariantsSource]).
rust_decl(Block) :-
    schema:type_decl(Name, alias(Type)),
    pascal(Name, RustName), rust_type(Type, RustType),
    format(string(Block), "pub type ~s = ~s;\n\n", [RustName, RustType]).

rust_field(field(Name, Type), Line) :-
    rust_type(Type, RustType),
    format(string(Line), "    pub ~w: ~s,\n", [Name, RustType]).
rust_variant(literal(Value), Line) :-
    pascal(Value, Name), format(string(Line), "    ~s,\n", [Name]).

rust_type(string, "String") :- !.
rust_type(int, "i64") :- !.
rust_type(bool, "bool") :- !.
rust_type(optional(Type), Rust) :- !, rust_type(Type, Inner), format(string(Rust), "Option<~s>", [Inner]).
rust_type(array(Type), Rust) :- !, rust_type(Type, Inner), format(string(Rust), "Vec<~s>", [Inner]).
rust_type(map(_, Type), Rust) :- !, rust_type(Type, Inner), format(string(Rust), "std::collections::BTreeMap<String, ~s>", [Inner]).
rust_type(Name, Rust) :- atom(Name), pascal(Name, Rust).

javascript_source(Source) :-
    findall(Function, js_consumer(Function), Functions),
    atomics_to_string(["// generated by swi-typespec-lab\n\nconst baseUrl = globalThis.BASE_URL ?? \"http://127.0.0.1:4000\";\n\n"|Functions], "", Source).

js_consumer(Function) :-
    schema:consumer(http, Verb, PatternName, _),
    schema:pattern_decl(PatternName, PatternSource),
    patterns:parse_pattern(PatternSource, Parts),
    patterns:slots(Parts, Slots),
    maplist(slot_name, Slots, Names),
    atomics_to_string(Names, ", ", Arguments),
    js_template(Parts, Template),
    format(string(Function), "export async function ~w(~s) {\n  const response = await fetch(baseUrl + `~s`, { method: \"~s\" });\n  if (!response.ok) throw new Error(\"HTTP \" + response.status);\n  return response.json();\n}\n", [Verb, Arguments, Template, Verb]).

slot_name(Name-_, Name).
js_template([], "").
js_template([literal(Text)|Parts], Source) :-
    js_template(Parts, Tail), string_concat(Text, Tail, Source).
js_template([slot(Name, _)|Parts], Source) :-
    js_template(Parts, Tail), format(string(Source), "${encodeURIComponent(~w)}~s", [Name, Tail]).

pascal(Value, Pascal) :-
    (atom(Value) -> atom_string(Value, Text) ; Text = Value),
    split_string(Text, "_ -", "", Words),
    maplist(capitalize, Words, Capitalized),
    atomics_to_string(Capitalized, "", Pascal).
capitalize(Word, Capitalized) :-
    string_chars(Word, [Head|Tail]),
    upcase_atom(Head, Upper),
    string_chars(Capitalized, [Upper|Tail]).
