[workspace]

[package]
name        = "v3-parse-experiment"
version     = "0.0.0"
edition     = "2021"
publish     = false

[dependencies]
tree-sitter        = "0.25"
tree-sitter-json   = "0.24"
tree-sitter-rust   = "0.24"
tree-sitter-md     = "0.5"
regex              = "1"

[[bin]]
name = "inject"
path = "src/main.rs"

[[bin]]
name = "recurse_generic"
path = "src/bin/recurse_generic.rs"

[[bin]]
name = "unified"
path = "src/bin/unified.rs"
