:- module(emitter_p0_lab, [emit_all/0, go/0]).

:- use_module(library(filesex)).
:- use_module(library(process)).

emit_all :-
    lab_directory(LabDirectory),
    directory_file_path(LabDirectory, generated, GeneratedDirectory),
    make_directory_path(GeneratedDirectory),
    forall(generated_module(FileName, Lines),
           emit_module(GeneratedDirectory, FileName, Lines)).

go :-
    emit_all,
    lab_directory(LabDirectory),
    directory_file_path(LabDirectory, '2_grade.ts', GradeFile),
    process_create(path(node),
                   ['--experimental-transform-types', GradeFile],
                   [ process(ProcessId)
                   ]),
    process_wait(ProcessId, ExitStatus),
    ( ExitStatus == exit(0)
    -> true
    ; throw(error(emitter_p0_grade_failed(ExitStatus), _))
    ).

lab_directory(LabDirectory) :-
    source_file(emitter_p0_lab:emit_all, SourceFile),
    file_directory_name(SourceFile, LabDirectory).

emit_module(GeneratedDirectory, FileName, Lines) :-
    directory_file_path(GeneratedDirectory, FileName, OutputFile),
    atomic_list_concat(Lines, '\n', Body),
    setup_call_cleanup(
        open(OutputFile, write, OutputStream),
        format(OutputStream, '~w~n', [Body]),
        close(OutputStream)
    ).

generated_module('0_semi_naive_inline.ts',
  [ '// Generated by 0_lab.pl. Inline-specialized semi-naive statements.',
    'import { createSemiNaiveInlineVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createSemiNaiveInlineVariant({',
    '  forkDeltaJoinSql: `',
    '    INSERT OR IGNORE INTO fork_combined_delta(batch_id, value_a, value_b)',
    '    SELECT ?1, delta_result_a.value, current_result_b.value',
    '    FROM fork_delta AS delta_result_a',
    '    JOIN fork_result_b AS current_result_b',
    '    WHERE delta_result_a.batch_id = ?1 AND delta_result_a.rel = ''result_a''',
    '    UNION',
    '    SELECT ?1, current_result_a.value, delta_result_b.value',
    '    FROM fork_result_a AS current_result_a',
    '    JOIN fork_delta AS delta_result_b',
    '    WHERE delta_result_b.batch_id = ?1 AND delta_result_b.rel = ''result_b''',
    '  `,',
    '  recursiveDeltaSql: `',
    '    INSERT OR IGNORE INTO repeat_pulse_delta(batch_id, value)',
    '    SELECT ?1, previous_frontier.value + 1',
    '    FROM repeat_pulse_delta AS previous_frontier',
    '    WHERE previous_frontier.batch_id = ?2 AND previous_frontier.value < 3',
    '  `,',
    '  forkExplainSql: `',
    '    SELECT delta_result_a.value, current_result_b.value',
    '    FROM fork_delta AS delta_result_a',
    '    JOIN fork_result_b AS current_result_b',
    '    WHERE delta_result_a.batch_id = ?1 AND delta_result_a.rel = ''result_a''',
    '  `,',
    '  recursiveExplainSql: `',
    '    SELECT previous_frontier.value + 1',
    '    FROM repeat_pulse_delta AS previous_frontier',
    '    WHERE previous_frontier.batch_id = ?1 AND previous_frontier.value < 3',
    '  `,',
    '});'
  ]).

generated_module('1_semi_naive_helper.ts',
  [ '// Generated by 0_lab.pl. One shared semi-naive helper call.',
    'import { createSemiNaiveHelperVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createSemiNaiveHelperVariant({',
    '  forkDeltaTable: "fork_delta",',
    '  recursiveDeltaTable: "repeat_pulse_delta",',
    '});'
  ]).

generated_module('2_count_ivm_inline.ts',
  [ '// Generated by 0_lab.pl. Inline-specialized support maintenance.',
    'import { createCountIvmInlineVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createCountIvmInlineVariant({',
    '  transitionSql: `',
    '    INSERT INTO count_support_transition(batch_id, row_value, old_support, new_support)',
    '    SELECT ?1, source_delta.row_value, COALESCE(current_support.support_count, 0),',
    '           COALESCE(current_support.support_count, 0) + SUM(source_delta.weight)',
    '    FROM count_source_delta AS source_delta',
    '    LEFT JOIN count_support AS current_support',
    '      ON current_support.row_value = source_delta.row_value',
    '    WHERE source_delta.batch_id = ?1',
    '    GROUP BY source_delta.row_value',
    '  `,',
    '  reseedAuditSql: `',
    '    WITH RECURSIVE live(row_value) AS (',
    '      SELECT row_value FROM count_source',
    '      UNION',
    '      SELECT current_mirror.row_value',
    '      FROM count_mirror AS current_mirror',
    '      JOIN live ON live.row_value = current_mirror.row_value',
    '    ),',
    '    mismatch(row_value) AS (',
    '      SELECT current_mirror.row_value',
    '      FROM count_mirror AS current_mirror',
    '      LEFT JOIN live ON live.row_value = current_mirror.row_value',
    '      WHERE live.row_value IS NULL',
    '      UNION ALL',
    '      SELECT live.row_value',
    '      FROM live',
    '      LEFT JOIN count_mirror AS current_mirror ON current_mirror.row_value = live.row_value',
    '      WHERE current_mirror.row_value IS NULL',
    '    )',
    '    SELECT COUNT(*) FROM mismatch',
    '  `,',
    '  explainSql: `',
    '    SELECT row_value, SUM(weight)',
    '    FROM count_source_delta',
    '    WHERE batch_id = ?1',
    '    GROUP BY row_value',
    '  `,',
    '});'
  ]).

generated_module('3_count_ivm_helper.ts',
  [ '// Generated by 0_lab.pl. One shared support-maintenance helper call.',
    'import { createCountIvmHelperVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createCountIvmHelperVariant({',
    '  sourceDeltaTable: "count_source_delta",',
    '  supportTable: "count_support",',
    '});'
  ]).

generated_module('4_distinct_inline.ts',
  [ '// Generated by 0_lab.pl. Inline-specialized DISTINCT placement.',
    'import { createDistinctInlineVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createDistinctInlineVariant({',
    '  demandAssertSql: `',
    '    INSERT OR IGNORE INTO distinct_demand_delta(batch_id, row_value)',
    '    SELECT DISTINCT ?1, source_delta.row_value',
    '    FROM distinct_stale_delta AS source_delta',
    '    WHERE source_delta.batch_id = ?1',
    '      AND NOT EXISTS (',
    '        SELECT 1 FROM distinct_demand AS current_demand',
    '        WHERE current_demand.row_value = source_delta.row_value',
    '      )',
    '  `,',
    '  mirrorAssertSql: `',
    '    INSERT OR IGNORE INTO distinct_mirror_assert(batch_id, row_value)',
    '    SELECT DISTINCT ?1, source_delta.row_value',
    '    FROM distinct_source_delta AS source_delta',
    '    WHERE source_delta.batch_id = ?1 AND source_delta.weight > 0',
    '  `,',
    '  mirrorRetractSql: `',
    '    INSERT OR IGNORE INTO distinct_mirror_retract(batch_id, row_value)',
    '    SELECT DISTINCT ?1, source_delta.row_value',
    '    FROM distinct_source_delta AS source_delta',
    '    WHERE source_delta.batch_id = ?1 AND source_delta.weight < 0',
    '  `,',
    '  assertExplainSql: `',
    '    SELECT DISTINCT row_value',
    '    FROM distinct_stale_delta',
    '    WHERE batch_id = ?1',
    '  `,',
    '  retractExplainSql: `',
    '    SELECT DISTINCT row_value',
    '    FROM distinct_source_delta',
    '    WHERE batch_id = ?1 AND weight < 0',
    '  `,',
    '});'
  ]).

generated_module('5_distinct_helper.ts',
  [ '// Generated by 0_lab.pl. One shared DISTINCT-placement helper call.',
    'import { createDistinctHelperVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createDistinctHelperVariant({',
    '  demandSourceDeltaTable: "distinct_stale_delta",',
    '  mirrorSourceDeltaTable: "distinct_source_delta",',
    '});'
  ]).

generated_module('6_boundary_inline.ts',
  [ '// Generated by 0_lab.pl. Inline-specialized boundary stream read.',
    'import { createBoundaryInlineVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createBoundaryInlineVariant({',
    '  selectSql: `',
    '    SELECT rel, sign, row_json',
    '    FROM change_stream',
    '    WHERE batch_id = ?1',
    '    ORDER BY rel, sign, row_json',
    '  `,',
    '  explainSql: `',
    '    SELECT rel, sign, row_json',
    '    FROM change_stream',
    '    WHERE batch_id = ?1',
    '  `,',
    '});'
  ]).

generated_module('7_boundary_helper.ts',
  [ '// Generated by 0_lab.pl. One shared boundary-stream helper call.',
    'import { createBoundaryHelperVariant } from "../1_runtime.ts";',
    '',
    'export const variant = createBoundaryHelperVariant({',
    '  streamTable: "change_stream",',
    '});'
  ]).
