% emit_ts.pl : the prolog frontend's exit door, literal-TS edition. `<-` rules
% (native terms via op/3) are printed as a readable TypeScript module built
% from ast.ts's OWN constructor helpers (edbRel/derivedRel/relRef/v/lit/wild/
% compare/headVar/notRel) — the helpers that file ships "so hand-built programs
% (tests, a future parser) stay terse". This is that parser. No JSON, no
% hydration: the emitted module typechecks against `Program` and the engine
% (evalProgramSql) runs it unchanged. Replaces the rejected AST-JSON bridge
% (emit_ast.pl, removed; history at 020a4bbc).
%
% Emit:    swipl -q -l v6/prolog/src/emit_ts.pl -g "emit(reach, 'out.gen.ts'),halt"
% Score:   swipl -q -l v6/prolog/src/emit_ts.pl -g go -g halt   (from repo root)
%
% Variable naming: a join hole is named after the COLUMN of its first positive
% binding position (edge(Parent, Child) -> v("parent"), v("child")), so the
% emitted TS reads like the hand-written programs in the engine's tests.
% Collisions inside one rule get a numeric suffix; a hole with no positive
% binding falls back to v0-style. A hole occurring once is wild(); a head hole
% with no body binding fails emission (unsafe rule), same check the SQL
% lowering does.

% The module name says which engine seam this targets. `compile/emit_ts.pl` is
% the tsv2 backend and owns the plain `emit_ts` name; both files declaring it
% made an all-files load impossible ("No permission to redefine module
% emit_ts"). `just prolog-lint` is the gate that now refuses a re-collision.
% The file path is unchanged, so `-l v6/prolog/src/emit_ts.pl -g emit(...)`
% callers such as bench/engines/swi_emit.sh are unaffected.
:- module(emit_ts_engine_v1,
          [ emit/2, emit/3, go/0,
            decl_ts/2, rule_ts/3, used_helpers/2
          ]).

:- use_module(library(lists)).
:- use_module(library(apply)).
:- use_module(library(aggregate)).
:- use_module(library(process)).
:- use_module(library(readutil)).
:- use_module(grader).

:- op(1150, xfx, <-).

% ── programs ────────────────────────────────────────────────────────────────

program(reach,
  [ edb(root, [node]),
    edb(edge, [parent, child]),
    idb(reach, [node])
  ],
  [ ( reach(Node)  <- root(Node) ),
    ( reach(Child) <- (edge(Parent, Child), reach(Parent)) )
  ]).

% ── emission ────────────────────────────────────────────────────────────────

emit(Name, Path) :- emit(Name, Path, '../lower/ast.ts').

emit(Name, Path, AstImport) :-
    program(Name, Decls, Rules),
    maplist(decl_ts, Decls, DeclLines),
    maplist(rule_ts(Decls), Rules, RuleLines),
    atomic_list_concat(DeclLines, '\n', DeclsBlock),
    atomic_list_concat(RuleLines, '\n', RulesBlock),
    format(atom(Body),
           'export const program: Program = {~n  rels: [~n~w~n  ],~n  rules: [~n~w~n  ],~n};~n',
           [DeclsBlock, RulesBlock]),
    used_helpers(Body, Helpers),
    atomic_list_concat(Helpers, ', ', HelperList),
    format(atom(Text),
           '/** GENERATED by v6/prolog/src/emit_ts.pl from program \'~w\'. Do not edit. */~nimport { type Program, ~w } from "~w";~n~n~w',
           [Name, HelperList, AstImport, Body]),
    file_directory_name(Path, Dir),
    make_directory_path(Dir),
    setup_call_cleanup(open(Path, write, Stream), write(Stream, Text), close(Stream)).

% Only the helpers the body actually calls go in the import line. `Helper(`
% cannot occur any other way: rel/column names sit inside string quotes.
used_helpers(Body, Used) :-
    findall(Helper,
            ( member(Helper, [edbRel, derivedRel, relRef, notRel, wild, v, lit,
                              compare, headVar, headAgg]),
              format(atom(Call), '~w(', [Helper]),
              sub_atom(Body, _, _, _, Call)
            ),
            Unsorted),
    sort(Unsorted, Used).

decl_ts(edb(Name, Cols), Line) :-
    cols_ts(Cols, ColsS),
    format(atom(Line), '    edbRel("~w", [~w]),', [Name, ColsS]).
decl_ts(idb(Name, Cols), Line) :-
    cols_ts(Cols, ColsS),
    format(atom(Line), '    derivedRel("~w", [~w]),', [Name, ColsS]).

cols_ts(Cols, S) :-
    maplist([Col, Q]>>format(atom(Q), '"~w"', [Col]), Cols, Quoted),
    atomic_list_concat(Quoted, ', ', S).

rule_ts(Decls, Rule, Line) :-
    copy_term(Rule, Head <- BodyTerm),
    Head =.. [HeadName | HeadArgs],
    body_list(BodyTerm, Items),
    hole_occurrences(HeadArgs, Items, Occs),
    column_names(Decls, Items, Occs, ColumnNamed),
    fallback_names(Occs, Occs, ColumnNamed, Named),
    maplist(head_ts(Occs, Named), HeadArgs, HeadTs),
    maplist(body_ts(Occs, Named), Items, BodyTs),
    atomic_list_concat(HeadTs, ', ', HeadS),
    atomic_list_concat(BodyTs, ', ', BodyS),
    format(atom(Line), '    { head: "~w", headTerms: [~w], body: [~w] },',
           [HeadName, HeadS, BodyS]).

body_list((Item, Rest), [Item | Items]) :- !, body_list(Rest, Items).
body_list(Item, [Item]).

% every hole occurrence, duplicates preserved: count 1 = wildcard, 2+ = join var
hole_occurrences(HeadArgs, Items, Occs) :-
    foldl(item_holes, Items, [], BodyOccs),
    include(var, HeadArgs, HeadHoles),
    append(HeadHoles, BodyOccs, Occs).

item_holes(\+ Atom, Acc, Occs) :- !, Atom =.. [_ | Args],
    include(var, Args, Holes), append(Acc, Holes, Occs).
item_holes(Cmp, Acc, Occs) :- cmp_op(Cmp, _, Lhs, _), !,
    ( var(Lhs) -> append(Acc, [Lhs], Occs) ; Occs = Acc ).
item_holes(Atom, Acc, Occs) :- Atom =.. [_ | Args],
    include(var, Args, Holes), append(Acc, Holes, Occs).

% ── naming: positive binding position -> its declared column name ───────────

column_names(Decls, Items, Occs, Named) :-
    foldl(item_names(Decls, Occs), Items, [], Named).

item_names(_, _, \+ _, Acc, Acc) :- !.
item_names(_, _, Cmp, Acc, Acc) :- cmp_op(Cmp, _, _, _), !.
item_names(Decls, Occs, Atom, Acc, Out) :-
    Atom =.. [Rel | Args],
    rel_columns(Decls, Rel, Cols),
    args_names(Args, Cols, Occs, Acc, Out).

rel_columns(Decls, Rel, Cols) :- memberchk(edb(Rel, Cols), Decls), !.
rel_columns(Decls, Rel, Cols) :- memberchk(idb(Rel, Cols), Decls).

args_names([], _, _, Acc, Acc).
args_names([Arg | Args], [Col | Cols], Occs, Acc, Out) :-
    (   var(Arg), count_occ(Arg, Occs, N), N >= 2, \+ hlookup(Arg, Acc, _)
    ->  fresh_name(Col, Acc, Name), Acc1 = [Arg-Name | Acc]
    ;   Acc1 = Acc
    ),
    args_names(Args, Cols, Occs, Acc1, Out).

fresh_name(Col, Acc, Col) :- \+ name_taken(Col, Acc), !.
fresh_name(Col, Acc, Name) :-
    between(2, 99, I),
    format(atom(Name), '~w~w', [Col, I]),
    \+ name_taken(Name, Acc), !.

name_taken(Name, Acc) :- member(_-Taken, Acc), Taken == Name, !.

% a join hole with no positive binding (negation-only) still needs a name
fallback_names([], _, Named, Named).
fallback_names([Hole | Rest], Occs, Acc, Named) :-
    (   hlookup(Hole, Acc, _) -> Acc1 = Acc
    ;   count_occ(Hole, Occs, N), N >= 2
    ->  length(Acc, I), format(atom(Name), 'v~w', [I]), Acc1 = [Hole-Name | Acc]
    ;   Acc1 = Acc
    ),
    fallback_names(Rest, Occs, Acc1, Named).

hlookup(Hole, [Key-Name | _], Name) :- Hole == Key, !.
hlookup(Hole, [_ | Rest], Name) :- hlookup(Hole, Rest, Name).

count_occ(Hole, Occs, N) :-
    aggregate_all(count, (member(O, Occs), O == Hole), N).

% ── rendering ───────────────────────────────────────────────────────────────

% head terms: holes only, each body-bound (count 2+) or emission FAILS (unsafe)
head_ts(Occs, Named, Arg, T) :-
    var(Arg),
    count_occ(Arg, Occs, N), N >= 2,
    hlookup(Arg, Named, Name),
    format(atom(T), 'headVar("~w")', [Name]).

body_ts(Occs, Named, \+ Atom, T) :- !,
    Atom =.. [Rel | Args],
    maplist(arg_ts(Occs, Named), Args, ArgTs),
    call_ts(notRel, Rel, ArgTs, T).
body_ts(_Occs, Named, Cmp, T) :-
    cmp_op(Cmp, Op, Lhs, Rhs), !,
    hlookup(Lhs, Named, Name),
    lit_ts(Rhs, RhsS),
    format(atom(T), 'compare("~w", "~w", ~w)', [Op, Name, RhsS]).
body_ts(Occs, Named, Atom, T) :-
    Atom =.. [Rel | Args],
    maplist(arg_ts(Occs, Named), Args, ArgTs),
    call_ts(relRef, Rel, ArgTs, T).

call_ts(Fn, Rel, [], T) :- !, format(atom(T), '~w("~w")', [Fn, Rel]).
call_ts(Fn, Rel, ArgTs, T) :-
    atomic_list_concat(ArgTs, ', ', ArgsS),
    format(atom(T), '~w("~w", ~w)', [Fn, Rel, ArgsS]).

arg_ts(Occs, Named, Arg, T) :-
    (   var(Arg)
    ->  (   count_occ(Arg, Occs, 1) -> T = 'wild()'
        ;   hlookup(Arg, Named, Name), format(atom(T), 'v("~w")', [Name])
        )
    ;   lit_ts(Arg, L), format(atom(T), 'lit(~w)', [L])
    ).

lit_ts(N, N) :- number(N), !.
lit_ts(A, S) :- atom(A), format(atom(S), '"~w"', [A]).

cmp_op(A > B,   gt, A, B).
cmp_op(A < B,   lt, A, B).
cmp_op(A >= B,  ge, A, B).
cmp_op(A =< B,  le, A, B).
cmp_op(A =:= B, eq, A, B).
cmp_op(A =\= B, ne, A, B).

% ── grader ──────────────────────────────────────────────────────────────────

reach_decls([edb(root, [node]), edb(edge, [parent, child]), idb(reach, [node])]).

check(reach_emits_readable_ts, (
    tmp_file_stream(text, Path, S0), close(S0),
    emit(reach, Path),
    read_file_to_string(Path, Text, []),
    sub_string(Text, _, _, _, "export const program: Program"),
    sub_string(Text, _, _, _, "edbRel(\"edge\", [\"parent\", \"child\"])"),
    sub_string(Text, _, _, _, "relRef(\"edge\", v(\"parent\"), v(\"child\"))"),
    sub_string(Text, _, _, _, "relRef(\"reach\", v(\"parent\"))"),   % the join, by name
    sub_string(Text, _, _, _, "headVar(\"child\")"),
    \+ sub_string(Text, _, _, _, "notRel")   % unused helpers stay unimported
)).
check(unsafe_head_fails, (
    reach_decls(Decls),
    \+ rule_ts(Decls, (bad(X) <- edge(_, _)), _),
    copy_term(X, _)
)).
% e2e: emit the module, node runs it through evalProgramSql on the benchgraph
% workload at 2x200. killed=200 is arithmetic on the generator: after deleting
% root 0, reach = root 1 + layer1 w%3==0 (67) + layer2 w%3 in {0,2} (133) +
% layer2 w=199 via the (w+1)%width wraparound to layer1 node 0, so 202 survive
% of 402. Run from repo root.
check(emitted_module_runs_engine, (
    emit(reach, 'v6/sprefa-store/js/src/gen/reach.gen.ts'),
    process_create(path(node),
        [ '--experimental-transform-types',   % lowerSql.ts uses parameter properties
          'v6/sprefa-store/js/src/labs/prolog_emit_bench.ts',
          'v6/sprefa-store/js/src/gen/reach.gen.ts', '2', '200' ],
        [stdout(pipe(Out)), stderr(null)]),
    read_string(Out, _, OutS), close(Out),
    split_string(OutS, "\n", "", Lines),
    member(Line, Lines),
    split_string(Line, ",", "", ["CSV", "swi-emit", "402", _, "200" | _])
)).

go :- run(check).
