[package]
name    = "spine"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
sprefa_parse   = { path = "../sprefa_parse" }
effect_runtime = { path = "../effect_runtime" }

futures-core   = "0.3"
futures-util   = "0.3"
bytes          = "1"
tokio          = { version = "1", features = ["sync", "io-util", "io-std"] }
tokio-util     = { version = "0.7", features = ["rt"] }
async-trait    = "0.1"
tracing        = "0.1"
chrono         = { version = "0.4", features = ["clock"] }
globset        = "0.4"
regex          = "1"
anyhow         = "1"
