//! Op trait. Object-safe for storage in `Pipeline::Op(Box<dyn Op>)`.
//!
//! PAIN POINT — static `type Slot` punted:
//!
//! The natural spelling is:
//!
//! ```ignore
//! trait Op {
//!     type Slot: Any + Send + Sync = ();  // for LSP slot-graph check
//!     async fn pipe(&self, ctx: &RtCtx, c: Cursor) -> Vec<Cursor>;
//! }
//! ```
//!
//! That shape gives authors one-line ergonomics (`c.put::<Self::Slot>(v)`)
//! AND lets a pipeline typechecker walk `.sprf`-composed pipelines at
//! compile time to verify every reader has a writer upstream.
//!
//! It breaks object safety. `Pipeline::Op(Box<dyn Op>)` requires no
//! associated types on the trait, because `Box<dyn Op>` cannot carry a
//! monomorphized slot type.
//!
//! Two paths out, deferred:
//!   A. Split metadata: `trait OpMeta { type Slot; const NAME: &str; }`
//!      as a companion, `impl Op for T where T: OpMeta` generated by a
//!      macro. Op stays object-safe; OpMeta powers the typechecker.
//!   B. Monomorphize Pipeline per composition via generics + codegen
//!      (self-hosted, per project_op_owned_cursor_slots). Works for
//!      Rust-compile-time-known `.sprf`; runtime-parsed pipelines still
//!      need the dyn path.
//!
//! For this slice: object-safe Op only. Slot access via `c.put_slot::<T>`
//! and `c.get_slot::<T>`, with the TypeId-map dyn boundary visible but
//! typed at the call site.

use crate::_0_cursor::Cursor;
use effect_runtime::{BoxFuture, RtCtx};

pub trait Op: Send + Sync + 'static {
    /// Stable identifier used for `PathSeg::Op { name, .. }` tagging
    /// and for diagnostics. Framework reads this, ops don't.
    fn name(&self) -> &'static str;

    /// Per-cursor work. Returns zero-or-more output cursors.
    ///
    /// PAIN POINT — per-cursor signature vs batch prefetch:
    ///
    /// v2's ast_grep op prefetches bytes for N cursors then rayon-maps
    /// (see v2/src/ops/_9_ast_grep.rs:279-400). That pattern depends on
    /// seeing the full batch inside the op. The v3 finding (FINDINGS.md
    /// §5.2) says the batch-prefetch should happen at the *effect*
    /// layer: one `ctx.put::<ReadBytesBatch>(Vec<path>)` from the op,
    /// batcher coalesces, op gets the bytes back as one Vec. That
    /// removes the need for a `pipe_batch` method here, but only if
    /// every batching use-case fits through the effect surface. Cases
    /// where the op must *decide* based on cross-cursor comparison
    /// (e.g., join-group ops) still want a batch view; left for a
    /// follow-up slice.
    fn pipe<'a>(&'a self, ctx: &'a RtCtx, c: Cursor) -> BoxFuture<'a, Vec<Cursor>>;

    /// Sub-grammar for this op's paren-slot body (§14.5).
    ///
    /// `None` = non-pattern op (capture_write, void, str). The lowerer
    /// and LSP hover dispatcher branch on this.
    fn language(&self) -> Option<tree_sitter::Language> { None }

    /// Editor highlight queries for the sub-grammar (§14.5). Usually
    /// `include_str!("queries/highlights.scm")` via `#[sprf_pattern_op]`.
    fn highlights(&self) -> Option<&'static str> { None }
}
