// GENERATED by v6/prolog/compile (tsv2 Phase B, round 2). Do not
// hand-edit; recompile. Program: braces_in_head_position.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// Strategy matches Phase A's hand-carved exemplar (gen/*.ts): read every
// rel's rows before a tick's writes and again after, diff with the
// runtime's multisetDiff (reused, never reimplemented -- one algorithm
// covers Set/level rels via plain set diff and Log rels via occurrence-count
// diff, since engine.pl r7's "one +Row per new stamp" for an append-only
// Log rel is exactly "count in next minus count in prev"). Edge-rule keyed
// writes are resolved in JS directly from the `arrivals` array (no tick
// number reaches tick() in the real seam -- the runtime owns tick
// numbering, ../runtime/tickLoop.ts -- so "this tick's fresh trigger rows"
// has no SQL-side answer; they ARE the arrivals argument already).
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IRow,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[] };

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

const ddl: readonly string[] = [
  `CREATE TABLE "doc_out" ("col1" TEXT NOT NULL, PRIMARY KEY ("col1")) WITHOUT ROWID`,
  `CREATE TABLE "seed" ("name" TEXT NOT NULL, PRIMARY KEY ("name")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  doc_out: ["col1"],
  seed: ["name"],
};

const arrivalTargets: readonly string[] = ["seed"];

const boot: readonly IBootStatement[] = [
  { sql: `INSERT OR IGNORE INTO "seed" ("name") VALUES (?)`, params: ["cli"] },
  { sql: `DELETE FROM "doc_out"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "doc_out" ("col1") SELECT json_object('fn', '{}', 'args', json_array(json_object('fn', ':', 'args', json_array('repo', b0."name")))) FROM "seed" b0`, params: [] },
];

type Snapshot = {
  readonly doc_out: readonly IRow[];
  readonly seed: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    doc_out: selectRows(seam, `SELECT CASE WHEN json_valid("col1") AND json_type("col1") = 'object' THEN json_extract("col1", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("col1", '$.args')) || ')' ELSE "col1" END AS "col1" FROM "doc_out"`, relColumns.doc_out!),
    seed: selectRows(seam, `SELECT CASE WHEN json_valid("name") AND json_type("name") = 'object' THEN json_extract("name", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("name", '$.args')) || ')' ELSE "name" END AS "name" FROM "seed"`, relColumns.seed!),
  });
}

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  seed: { kind: "set", addSql: `INSERT OR IGNORE INTO "seed" ("name") VALUES (?)`, delSql: `DELETE FROM "seed" WHERE "name" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`braces_in_head_position: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`braces_in_head_position: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`braces_in_head_position: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "doc_out";\nINSERT OR IGNORE INTO "doc_out" ("col1") SELECT json_object('fn', '{}', 'args', json_array(json_object('fn', ':', 'args', json_array('repo', b0."name")))) FROM "seed" b0`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const doc_out = multisetDiff(before.doc_out, after.doc_out);
  const seed = multisetDiff(before.seed, after.seed);
  return {
    rels: [
      { rel: "doc_out", add: doc_out.add, del: doc_out.del },
      { rel: "seed", add: seed.add, del: seed.del },
    ],
    carryPending: false,
  };
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // braces_in_head_position: no edge rules -- absorb arrivals, recompute levels, diff.
}

export const program: IGenProgramWithBoot = {
  name: "braces_in_head_position",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  tick: runTick,
};
