// GENERATED by v6/prolog/compile (tsv2 emitter P3). Do not
// hand-edit; recompile. Program: dirty_retracts_on_matching_commit.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// The default path stages effective tick changes in indexed TEMP tables,
// executes emitted frontier-side joins for positive level rules, promotes
// edge and post-write level growth across drain ticks, and computes boundary
// changes from the staged stream. Retractions and negative bodies use emitted
// support-count reconciliation. The snapshot path remains selectable with
// SPREFA_TSV2_EMITTER_MODE=naive as a byte-identity referee.
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { IncrementalRuntime } from "../runtime/1_incremental.ts";
import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IIncrementalEdgeStatement,
  IIncrementalLevelStatement,
  IIncrementalProgramPlan,
  IIncrementalRelationPlan,
  IRelDelta,
  IRow,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IHostColumnPlan { readonly name: string; readonly type: "int" | "text" | "json" }
interface IHostPlanData { readonly name: string; readonly inputs: readonly IHostColumnPlan[]; readonly outputs: readonly IHostColumnPlan[]; readonly template: string; readonly demandRel: string; readonly responseRel: string; readonly execution: string }
interface IBindPlanData { readonly name: string; readonly columns: readonly IHostColumnPlan[]; readonly literals: readonly (string | number)[]; readonly execution: string }
interface IQueryPlanData { readonly rel: string; readonly arity: number; readonly snapshot: "current" }

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[]; readonly finalSelect: Record<string, string>; readonly hostPlans: readonly IHostPlanData[]; readonly bindPlans: readonly IBindPlanData[]; readonly queryPlans: readonly IQueryPlanData[]; readonly unsupportedExecution: readonly string[] };

export const hostPlans: readonly IHostPlanData[] = [];
export const bindPlans: readonly IBindPlanData[] = [];
export const queryPlans: readonly IQueryPlanData[] = [];
export const unsupportedExecution: readonly string[] = [];

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

function triggerOccurrences(
  kind: "log" | "set",
  relName: string,
  beforeRows: readonly IRow[],
  arrivals: IArrivalBatch,
): IArrivalBatch {
  if (kind === "log") return arrivals.filter((arrival) => arrival.rel === relName && arrival.sign === "add");
  const seen = new Set<string>(beforeRows.map((row) => JSON.stringify(row)));
  const occurrences: IArrivalRow[] = [];
  for (const arrival of arrivals) {
    if (arrival.rel !== relName || arrival.sign !== "add") continue;
    const key = JSON.stringify(arrival.row);
    if (seen.has(key)) continue;
    seen.add(key);
    occurrences.push(arrival);
  }
  return occurrences;
}

const ddl: readonly string[] = [
  `CREATE TABLE "commit_arrival" ("rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE TABLE "dirty" ("path" TEXT NOT NULL, "__support_count" INTEGER NOT NULL DEFAULT 1, PRIMARY KEY ("path")) WITHOUT ROWID`,
  `CREATE TABLE "head" ("repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, PRIMARY KEY ("repo_id")) WITHOUT ROWID`,
  `CREATE TABLE "head_move" ("repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE TABLE "tree_file" ("rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL, PRIMARY KEY ("rev_id", "path")) WITHOUT ROWID`,
  `CREATE TABLE "worktree_edit" ("path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE TABLE "worktree_file" ("path" TEXT NOT NULL, "digest" TEXT NOT NULL, PRIMARY KEY ("path")) WITHOUT ROWID`,
  `CREATE TEMP TABLE "__delta_commit_arrival" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_commit_arrival_sign" ON "__delta_commit_arrival" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_commit_arrival" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_commit_arrival_phase" ON "__frontier_commit_arrival" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_commit_arrival" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_commit_arrival_phase" ON "__next_frontier_commit_arrival" ("_phase")`,
  `CREATE TEMP TABLE "__delta_dirty" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_dirty_sign" ON "__delta_dirty" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_dirty" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_dirty_phase" ON "__frontier_dirty" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_dirty" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_dirty_phase" ON "__next_frontier_dirty" ("_phase")`,
  `CREATE TEMP TABLE "__delta_head" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__delta_head_sign" ON "__delta_head" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_head" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__frontier_head_phase" ON "__frontier_head" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_head" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__next_frontier_head_phase" ON "__next_frontier_head" ("_phase")`,
  `CREATE TEMP TABLE "__delta_head_move" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__delta_head_move_sign" ON "__delta_head_move" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_head_move" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__frontier_head_move_phase" ON "__frontier_head_move" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_head_move" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "repo_id" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL)`,
  `CREATE INDEX "__next_frontier_head_move_phase" ON "__next_frontier_head_move" ("_phase")`,
  `CREATE TEMP TABLE "__delta_tree_file" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_tree_file_sign" ON "__delta_tree_file" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_tree_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_tree_file_phase" ON "__frontier_tree_file" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_tree_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "rev_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_tree_file_phase" ON "__next_frontier_tree_file" ("_phase")`,
  `CREATE TEMP TABLE "__delta_worktree_edit" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_worktree_edit_sign" ON "__delta_worktree_edit" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_worktree_edit" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_worktree_edit_phase" ON "__frontier_worktree_edit" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_worktree_edit" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_worktree_edit_phase" ON "__next_frontier_worktree_edit" ("_phase")`,
  `CREATE TEMP TABLE "__delta_worktree_file" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_worktree_file_sign" ON "__delta_worktree_file" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_worktree_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_worktree_file_phase" ON "__frontier_worktree_file" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_worktree_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "path" TEXT NOT NULL, "digest" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_worktree_file_phase" ON "__next_frontier_worktree_file" ("_phase")`,
  `CREATE TEMP TABLE "__support_next_dirty" ("path" TEXT NOT NULL, "__support_count" INTEGER NOT NULL, PRIMARY KEY ("path")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  commit_arrival: ["rev_id", "path", "digest"],
  dirty: ["path"],
  head: ["repo_id", "rev_id"],
  head_move: ["repo_id", "rev_id"],
  tree_file: ["rev_id", "path", "digest"],
  worktree_edit: ["path", "digest"],
  worktree_file: ["path", "digest"],
};

const arrivalTargets: readonly string[] = ["commit_arrival", "head_move", "worktree_edit"];

const boot: readonly IBootStatement[] = [
  { sql: `INSERT OR IGNORE INTO "head" ("repo_id", "rev_id") VALUES (?, ?)`, params: [1, 100] },
  { sql: `INSERT OR IGNORE INTO "tree_file" ("rev_id", "path", "digest") VALUES (?, ?, ?)`, params: [100, "src/lib.rs", "sha_v1"] },
  { sql: `INSERT OR IGNORE INTO "worktree_file" ("path", "digest") VALUES (?, ?)`, params: ["src/lib.rs", "sha_v1"] },
  { sql: `DELETE FROM "dirty"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "dirty" ("path") SELECT b0."path" FROM "worktree_file" b0, "head" b1, "tree_file" b2 WHERE b2."rev_id" = b1."rev_id" AND b2."path" = b0."path" AND (b0."digest" <> b2."digest")`, params: [] },
];

type Snapshot = {
  readonly commit_arrival: readonly IRow[];
  readonly dirty: readonly IRow[];
  readonly head: readonly IRow[];
  readonly head_move: readonly IRow[];
  readonly tree_file: readonly IRow[];
  readonly worktree_edit: readonly IRow[];
  readonly worktree_file: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    commit_arrival: selectRows(seam, `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "commit_arrival"`, relColumns.commit_arrival!),
    dirty: selectRows(seam, `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path" FROM "dirty"`, relColumns.dirty!),
    head: selectRows(seam, `SELECT "repo_id", "rev_id" FROM "head"`, relColumns.head!),
    head_move: selectRows(seam, `SELECT "repo_id", "rev_id" FROM "head_move"`, relColumns.head_move!),
    tree_file: selectRows(seam, `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "tree_file"`, relColumns.tree_file!),
    worktree_edit: selectRows(seam, `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "worktree_edit"`, relColumns.worktree_edit!),
    worktree_file: selectRows(seam, `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "worktree_file"`, relColumns.worktree_file!),
  });
}

const finalSelect: Record<string, string> = {
  commit_arrival: `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "commit_arrival"`,
  dirty: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path" FROM "dirty"`,
  head: `SELECT "repo_id", "rev_id" FROM "head"`,
  head_move: `SELECT "repo_id", "rev_id" FROM "head_move"`,
  tree_file: `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "tree_file"`,
  worktree_edit: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "worktree_edit"`,
  worktree_file: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest" FROM "worktree_file"`,
};

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  commit_arrival: { kind: "log", addSql: `INSERT INTO "commit_arrival" ("rev_id", "path", "digest") VALUES (?, ?, ?)`, delSql: null },
  head_move: { kind: "log", addSql: `INSERT INTO "head_move" ("repo_id", "rev_id") VALUES (?, ?)`, delSql: null },
  worktree_edit: { kind: "log", addSql: `INSERT INTO "worktree_edit" ("path", "digest") VALUES (?, ?)`, delSql: null },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`dirty_retracts_on_matching_commit: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`dirty_retracts_on_matching_commit: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`dirty_retracts_on_matching_commit: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = [
  { rel: "commit_arrival", kind: "log", tableName: "commit_arrival", deltaTableName: "__delta_commit_arrival", frontierTableName: "__frontier_commit_arrival", nextFrontierTableName: "__next_frontier_commit_arrival", columns: ["rev_id", "path", "digest"], keyIndices: [], arrivalAddSql: `INSERT INTO "commit_arrival" ("rev_id", "path", "digest") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]'), json_extract(value, '$[2]') FROM json_each(?) RETURNING "rev_id", "path", "digest"`, arrivalDelSql: null, boundarySql: `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_commit_arrival" WHERE "_sign" IN (-1, 1) GROUP BY "rev_id", "path", "digest", "_sign"` },
  { rel: "dirty", kind: "set", tableName: "dirty", deltaTableName: "__delta_dirty", frontierTableName: "__frontier_dirty", nextFrontierTableName: "__next_frontier_dirty", columns: ["path"], keyIndices: [], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_dirty" WHERE "_sign" IN (-1, 1) GROUP BY "path", "_sign"` },
  { rel: "head", kind: "set", tableName: "head", deltaTableName: "__delta_head", frontierTableName: "__frontier_head", nextFrontierTableName: "__next_frontier_head", columns: ["repo_id", "rev_id"], keyIndices: [0], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT "repo_id", "rev_id", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_head" WHERE "_sign" IN (-1, 1) GROUP BY "repo_id", "rev_id", "_sign"` },
  { rel: "head_move", kind: "log", tableName: "head_move", deltaTableName: "__delta_head_move", frontierTableName: "__frontier_head_move", nextFrontierTableName: "__next_frontier_head_move", columns: ["repo_id", "rev_id"], keyIndices: [], arrivalAddSql: `INSERT INTO "head_move" ("repo_id", "rev_id") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?) RETURNING "repo_id", "rev_id"`, arrivalDelSql: null, boundarySql: `SELECT "repo_id", "rev_id", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_head_move" WHERE "_sign" IN (-1, 1) GROUP BY "repo_id", "rev_id", "_sign"` },
  { rel: "tree_file", kind: "set", tableName: "tree_file", deltaTableName: "__delta_tree_file", frontierTableName: "__frontier_tree_file", nextFrontierTableName: "__next_frontier_tree_file", columns: ["rev_id", "path", "digest"], keyIndices: [0, 1], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT "rev_id", CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_tree_file" WHERE "_sign" IN (-1, 1) GROUP BY "rev_id", "path", "digest", "_sign"` },
  { rel: "worktree_edit", kind: "log", tableName: "worktree_edit", deltaTableName: "__delta_worktree_edit", frontierTableName: "__frontier_worktree_edit", nextFrontierTableName: "__next_frontier_worktree_edit", columns: ["path", "digest"], keyIndices: [], arrivalAddSql: `INSERT INTO "worktree_edit" ("path", "digest") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?) RETURNING "path", "digest"`, arrivalDelSql: null, boundarySql: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_worktree_edit" WHERE "_sign" IN (-1, 1) GROUP BY "path", "digest", "_sign"` },
  { rel: "worktree_file", kind: "set", tableName: "worktree_file", deltaTableName: "__delta_worktree_file", frontierTableName: "__frontier_worktree_file", nextFrontierTableName: "__next_frontier_worktree_file", columns: ["path", "digest"], keyIndices: [0], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT CASE WHEN json_valid("path") AND json_type("path") = 'object' THEN json_extract("path", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("path", '$.args')) || ')' ELSE "path" END AS "path", CASE WHEN json_valid("digest") AND json_type("digest") = 'object' THEN json_extract("digest", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("digest", '$.args')) || ')' ELSE "digest" END AS "digest", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_worktree_file" WHERE "_sign" IN (-1, 1) GROUP BY "path", "digest", "_sign"` },
];

const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = [
  { headRel: "worktree_file", headKind: "set", headTableName: "worktree_file", headDeltaTableName: "__delta_worktree_file", headColumns: ["path", "digest"], keyIndices: [0], projectSql: `SELECT d0."path" AS "path", d0."digest" AS "digest" FROM "__frontier_worktree_edit" d0 WHERE d0."_phase" >= 0 ORDER BY d0."_phase", d0."_sequence"` },
  { headRel: "tree_file", headKind: "set", headTableName: "tree_file", headDeltaTableName: "__delta_tree_file", headColumns: ["rev_id", "path", "digest"], keyIndices: [0, 1], projectSql: `SELECT d0."rev_id" AS "rev_id", d0."path" AS "path", d0."digest" AS "digest" FROM "__frontier_commit_arrival" d0 WHERE d0."_phase" >= 0 ORDER BY d0."_phase", d0."_sequence"` },
  { headRel: "head", headKind: "set", headTableName: "head", headDeltaTableName: "__delta_head", headColumns: ["repo_id", "rev_id"], keyIndices: [0], projectSql: `SELECT d0."repo_id" AS "repo_id", d0."rev_id" AS "rev_id" FROM "__frontier_head_move" d0 WHERE d0."_phase" >= 0 ORDER BY d0."_phase", d0."_sequence"` },
];

const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = [
  { headRel: "dirty", headDeltaTableName: "__delta_dirty", headColumns: ["path"], insertSql: `INSERT OR IGNORE INTO "dirty" ("path") SELECT DISTINCT d0."path" FROM "__frontier_worktree_file" d0, "head" b0, "tree_file" b1 WHERE d0."_phase" >= 0 AND b1."rev_id" = b0."rev_id" AND b1."path" = d0."path" AND (d0."digest" <> b1."digest") UNION ALL SELECT DISTINCT b0."path" FROM "__frontier_head" d0, "worktree_file" b0, "tree_file" b1 WHERE d0."_phase" >= 0 AND b1."rev_id" = d0."rev_id" AND b1."path" = b0."path" AND (b0."digest" <> b1."digest") UNION ALL SELECT DISTINCT d0."path" FROM "__frontier_tree_file" d0, "worktree_file" b0, "head" b1 WHERE d0."_phase" >= 0 AND b0."path" = d0."path" AND b1."rev_id" = d0."rev_id" AND (b0."digest" <> d0."digest") RETURNING "path"`, selectSql: `SELECT "path" FROM "dirty"`, recomputeSql: `DELETE FROM "dirty";\nINSERT OR IGNORE INTO "dirty" ("path") SELECT b0."path" FROM "worktree_file" b0, "head" b1, "tree_file" b2 WHERE b2."rev_id" = b1."rev_id" AND b2."path" = b0."path" AND (b0."digest" <> b2."digest")`, supportSql: [`DELETE FROM "__support_next_dirty"`, `INSERT INTO "__support_next_dirty" ("path", "__support_count") SELECT "path", sum("__support_count") FROM (SELECT b0."path" AS "path", count(*) AS "__support_count" FROM "worktree_file" b0, "head" b1, "tree_file" b2 WHERE b2."rev_id" = b1."rev_id" AND b2."path" = b0."path" AND (b0."digest" <> b2."digest") GROUP BY b0."path") GROUP BY "path"`, `UPDATE "dirty" AS h SET "__support_count" = "__support_count" - ("__support_count" - COALESCE((SELECT n."__support_count" FROM "__support_next_dirty" n WHERE n."path" = h."path"), 0))`, `DELETE FROM "dirty" WHERE "__support_count" <= 0 RETURNING "path"`, `INSERT INTO "dirty" ("path", "__support_count") SELECT "path", n."__support_count" FROM "__support_next_dirty" n WHERE NOT EXISTS (SELECT 1 FROM "dirty" h WHERE n."path" = h."path") RETURNING "path"`], aggregateSql: null },
];

const EDGE_WORKTREE_FILE_0_PROJECT_SQL = `SELECT ?1 AS "path", ?2 AS "digest"`;
const EDGE_WORKTREE_FILE_0_WRITE_SQL = `INSERT INTO "worktree_file" ("path", "digest") VALUES (?, ?) ON CONFLICT("path") DO UPDATE SET "digest" = excluded."digest"`;
const EDGE_WORKTREE_FILE_0_HEAD_COLUMNS: readonly string[] = ["path", "digest"];
const EDGE_WORKTREE_FILE_0_KEY_INDICES: readonly number[] = [0];

const EDGE_TREE_FILE_1_PROJECT_SQL = `SELECT ?1 AS "rev_id", ?2 AS "path", ?3 AS "digest"`;
const EDGE_TREE_FILE_1_WRITE_SQL = `INSERT INTO "tree_file" ("rev_id", "path", "digest") VALUES (?, ?, ?) ON CONFLICT("rev_id", "path") DO UPDATE SET "digest" = excluded."digest"`;
const EDGE_TREE_FILE_1_HEAD_COLUMNS: readonly string[] = ["rev_id", "path", "digest"];
const EDGE_TREE_FILE_1_KEY_INDICES: readonly number[] = [0, 1];

const EDGE_HEAD_2_PROJECT_SQL = `SELECT ?1 AS "repo_id", ?2 AS "rev_id"`;
const EDGE_HEAD_2_WRITE_SQL = `INSERT INTO "head" ("repo_id", "rev_id") VALUES (?, ?) ON CONFLICT("repo_id") DO UPDATE SET "rev_id" = excluded."rev_id"`;
const EDGE_HEAD_2_HEAD_COLUMNS: readonly string[] = ["repo_id", "rev_id"];
const EDGE_HEAD_2_KEY_INDICES: readonly number[] = [0];

function resolveWorktreeFile_0Writes(seam: ISqlSeam, before: Snapshot, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {
  const triggerRows = triggerOccurrences("log", "worktree_edit", before.worktree_edit, arrivals);
  if (triggerRows.length === 0) return of([]);
  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: EDGE_WORKTREE_FILE_0_PROJECT_SQL, args: bindArgs(arrival.row) }))).pipe(
    map((results) => {
      const resolved = new Map<string, IRow>();
      for (const result of results) {
        const projectedRows = result.rows.map((row) => EDGE_WORKTREE_FILE_0_HEAD_COLUMNS.map((column) => row[column] as IRowValue) as IRow);
        for (const projectedRow of projectedRows) {
          const key = JSON.stringify(EDGE_WORKTREE_FILE_0_KEY_INDICES.map((index) => projectedRow[index]));
          resolved.set(key, projectedRow);
        }
      }
      return [...resolved.values()].map((row): SqlStatement => ({ sql: EDGE_WORKTREE_FILE_0_WRITE_SQL, args: bindArgs(row) }));
    }),
  );
}

function resolveTreeFile_1Writes(seam: ISqlSeam, before: Snapshot, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {
  const triggerRows = triggerOccurrences("log", "commit_arrival", before.commit_arrival, arrivals);
  if (triggerRows.length === 0) return of([]);
  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: EDGE_TREE_FILE_1_PROJECT_SQL, args: bindArgs(arrival.row) }))).pipe(
    map((results) => {
      const resolved = new Map<string, IRow>();
      for (const result of results) {
        const projectedRows = result.rows.map((row) => EDGE_TREE_FILE_1_HEAD_COLUMNS.map((column) => row[column] as IRowValue) as IRow);
        for (const projectedRow of projectedRows) {
          const key = JSON.stringify(EDGE_TREE_FILE_1_KEY_INDICES.map((index) => projectedRow[index]));
          resolved.set(key, projectedRow);
        }
      }
      return [...resolved.values()].map((row): SqlStatement => ({ sql: EDGE_TREE_FILE_1_WRITE_SQL, args: bindArgs(row) }));
    }),
  );
}

function resolveHead_2Writes(seam: ISqlSeam, before: Snapshot, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {
  const triggerRows = triggerOccurrences("log", "head_move", before.head_move, arrivals);
  if (triggerRows.length === 0) return of([]);
  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: EDGE_HEAD_2_PROJECT_SQL, args: bindArgs(arrival.row) }))).pipe(
    map((results) => {
      const resolved = new Map<string, IRow>();
      for (const result of results) {
        const projectedRows = result.rows.map((row) => EDGE_HEAD_2_HEAD_COLUMNS.map((column) => row[column] as IRowValue) as IRow);
        for (const projectedRow of projectedRows) {
          const key = JSON.stringify(EDGE_HEAD_2_KEY_INDICES.map((index) => projectedRow[index]));
          resolved.set(key, projectedRow);
        }
      }
      return [...resolved.values()].map((row): SqlStatement => ({ sql: EDGE_HEAD_2_WRITE_SQL, args: bindArgs(row) }));
    }),
  );
}

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "dirty";\nINSERT OR IGNORE INTO "dirty" ("path") SELECT b0."path" FROM "worktree_file" b0, "head" b1, "tree_file" b2 WHERE b2."rev_id" = b1."rev_id" AND b2."path" = b0."path" AND (b0."digest" <> b2."digest")`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const commit_arrival = multisetDiff(before.commit_arrival, after.commit_arrival);
  const dirty = multisetDiff(before.dirty, after.dirty);
  const head = multisetDiff(before.head, after.head);
  const head_move = multisetDiff(before.head_move, after.head_move);
  const tree_file = multisetDiff(before.tree_file, after.tree_file);
  const worktree_edit = multisetDiff(before.worktree_edit, after.worktree_edit);
  const worktree_file = multisetDiff(before.worktree_file, after.worktree_file);
  return {
    rels: [
      { rel: "commit_arrival", add: commit_arrival.add, del: commit_arrival.del },
      { rel: "dirty", add: dirty.add, del: dirty.del },
      { rel: "head", add: head.add, del: head.del },
      { rel: "head_move", add: head_move.add, del: head_move.del },
      { rel: "tree_file", add: tree_file.add, del: tree_file.del },
      { rel: "worktree_edit", add: worktree_edit.add, del: worktree_edit.del },
      { rel: "worktree_file", add: worktree_file.add, del: worktree_file.del },
    ],
    carryPending: head.add.length > 0 || head.del.length > 0 || tree_file.add.length > 0 || tree_file.del.length > 0 || worktree_file.add.length > 0 || worktree_file.del.length > 0,
  };
}

function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) =>
      forkJoin([resolveWorktreeFile_0Writes(seam, before, arrivals), resolveTreeFile_1Writes(seam, before, arrivals), resolveHead_2Writes(seam, before, arrivals)]).pipe(map((groups) => groups.flat())).pipe(
        concatMap((statements) => seam.runner.batch(seam.db, statements)),
        map(() => before),
      ),
    ),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // dirty_retracts_on_matching_commit: engine.pl process_occurrences -> level_closure -> boundary_deltas.
}

const INCREMENTAL_PROGRAM_SAFE = true;
const RECONCILE_EVERY_TICK = false;
const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";

function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return IncrementalRuntime.prepareTick(seam, INCREMENTAL_RELATIONS).pipe(
    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyLevelsBeforeEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.mergeNextIntoCurrent(seam, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.recomputeLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS, RECONCILE_EVERY_TICK)),
    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),
    concatMap((rels) => IncrementalRuntime.promoteFrontiers(seam, INCREMENTAL_RELATIONS).pipe(
      map((carryPending): ITickDeltas => ({ rels, carryPending })),
    )),
  );
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE) {
    return runNaiveTick(seam, arrivals);
  }
  return runIncrementalTick(seam, arrivals);
}

export const incrementalPlan: IIncrementalProgramPlan = {
  safe: INCREMENTAL_PROGRAM_SAFE,
  reconcileEveryTick: RECONCILE_EVERY_TICK,
  retractionGuard: "plain-count-acyclic",
  relations: INCREMENTAL_RELATIONS,
  edges: INCREMENTAL_EDGE_STATEMENTS,
  levels: INCREMENTAL_LEVEL_STATEMENTS,
};

export const program: IGenProgramWithBoot = {
  name: "dirty_retracts_on_matching_commit",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  finalSelect,
  hostPlans,
  bindPlans,
  queryPlans,
  unsupportedExecution,
  tick: runTick,
};
