// GENERATED by v6/prolog/compile (tsv2 emitter P1). Do not
// hand-edit; recompile. Program: fill_as_cache_update_swr.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// The default path stages effective tick changes in indexed TEMP tables,
// executes emitted delta-side joins for positive acyclic level rules, and
// computes boundary changes from the staged stream. The snapshot recompute
// path remains selectable with SPREFA_TSV2_EMITTER_MODE=naive and is used
// automatically for P1-unsafe shapes and ticks containing retractions.
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { IncrementalRuntime } from "../runtime/1_incremental.ts";
import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IIncrementalEdgeStatement,
  IIncrementalLevelStatement,
  IIncrementalProgramPlan,
  IIncrementalRelationPlan,
  IRelDelta,
  IRow,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[] };

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

function triggerOccurrences(
  kind: "log" | "set",
  relName: string,
  beforeRows: readonly IRow[],
  arrivals: IArrivalBatch,
): IArrivalBatch {
  if (kind === "log") return arrivals.filter((arrival) => arrival.rel === relName && arrival.sign === "add");
  const seen = new Set<string>(beforeRows.map((row) => JSON.stringify(row)));
  const occurrences: IArrivalRow[] = [];
  for (const arrival of arrivals) {
    if (arrival.rel !== relName || arrival.sign !== "add") continue;
    const key = JSON.stringify(arrival.row);
    if (seen.has(key)) continue;
    seen.add(key);
    occurrences.push(arrival);
  }
  return occurrences;
}

const ddl: readonly string[] = [
  `CREATE TABLE "cache_row" ("target" TEXT NOT NULL, "body" TEXT NOT NULL, PRIMARY KEY ("target")) WITHOUT ROWID`,
  `CREATE TABLE "demanded" ("target" TEXT NOT NULL, "session_id" TEXT NOT NULL, PRIMARY KEY ("target", "session_id")) WITHOUT ROWID`,
  `CREATE TABLE "feed_view" ("target" TEXT NOT NULL, "body" TEXT NOT NULL, PRIMARY KEY ("target", "body")) WITHOUT ROWID`,
  `CREATE TABLE "fill_arrived" ("target" TEXT NOT NULL, "body" TEXT NOT NULL)`,
  `CREATE TABLE "open_feed" ("session_id" TEXT NOT NULL, "target" TEXT NOT NULL, PRIMARY KEY ("session_id", "target")) WITHOUT ROWID`,
  `CREATE TEMP TABLE "__delta_cache_row" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "target" TEXT NOT NULL, "body" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_cache_row_sign" ON "__delta_cache_row" ("_sign")`,
  `CREATE TEMP TABLE "__delta_demanded" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "target" TEXT NOT NULL, "session_id" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_demanded_sign" ON "__delta_demanded" ("_sign")`,
  `CREATE TEMP TABLE "__delta_feed_view" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "target" TEXT NOT NULL, "body" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_feed_view_sign" ON "__delta_feed_view" ("_sign")`,
  `CREATE TEMP TABLE "__delta_fill_arrived" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "target" TEXT NOT NULL, "body" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_fill_arrived_sign" ON "__delta_fill_arrived" ("_sign")`,
  `CREATE TEMP TABLE "__delta_open_feed" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "session_id" TEXT NOT NULL, "target" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_open_feed_sign" ON "__delta_open_feed" ("_sign")`,
];

const relColumns: Record<string, readonly string[]> = {
  cache_row: ["target", "body"],
  demanded: ["target", "session_id"],
  feed_view: ["target", "body"],
  fill_arrived: ["target", "body"],
  open_feed: ["session_id", "target"],
};

const arrivalTargets: readonly string[] = ["fill_arrived", "open_feed"];

const boot: readonly IBootStatement[] = [
  { sql: `DELETE FROM "demanded"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "demanded" ("target", "session_id") SELECT b0."target", b0."session_id" FROM "open_feed" b0`, params: [] },
  { sql: `DELETE FROM "feed_view"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "feed_view" ("target", "body") SELECT b0."target", b1."body" FROM "demanded" b0, "cache_row" b1 WHERE b1."target" = b0."target"`, params: [] },
];

type Snapshot = {
  readonly cache_row: readonly IRow[];
  readonly demanded: readonly IRow[];
  readonly feed_view: readonly IRow[];
  readonly fill_arrived: readonly IRow[];
  readonly open_feed: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    cache_row: selectRows(seam, `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body" FROM "cache_row"`, relColumns.cache_row!),
    demanded: selectRows(seam, `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("session_id") AND json_type("session_id") = 'object' THEN json_extract("session_id", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("session_id", '$.args')) || ')' ELSE "session_id" END AS "session_id" FROM "demanded"`, relColumns.demanded!),
    feed_view: selectRows(seam, `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body" FROM "feed_view"`, relColumns.feed_view!),
    fill_arrived: selectRows(seam, `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body" FROM "fill_arrived"`, relColumns.fill_arrived!),
    open_feed: selectRows(seam, `SELECT CASE WHEN json_valid("session_id") AND json_type("session_id") = 'object' THEN json_extract("session_id", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("session_id", '$.args')) || ')' ELSE "session_id" END AS "session_id", CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target" FROM "open_feed"`, relColumns.open_feed!),
  });
}

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  fill_arrived: { kind: "log", addSql: `INSERT INTO "fill_arrived" ("target", "body") VALUES (?, ?)`, delSql: null },
  open_feed: { kind: "set", addSql: `INSERT OR IGNORE INTO "open_feed" ("session_id", "target") VALUES (?, ?)`, delSql: `DELETE FROM "open_feed" WHERE "session_id" = ? AND "target" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`fill_as_cache_update_swr: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`fill_as_cache_update_swr: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`fill_as_cache_update_swr: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = [
  { rel: "cache_row", kind: "set", tableName: "cache_row", deltaTableName: "__delta_cache_row", columns: ["target", "body"], arrivalAddSql: null, boundarySql: `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_cache_row" WHERE "_sign" IN (-1, 1) GROUP BY "target", "body", "_sign"` },
  { rel: "demanded", kind: "set", tableName: "demanded", deltaTableName: "__delta_demanded", columns: ["target", "session_id"], arrivalAddSql: null, boundarySql: `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("session_id") AND json_type("session_id") = 'object' THEN json_extract("session_id", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("session_id", '$.args')) || ')' ELSE "session_id" END AS "session_id", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_demanded" WHERE "_sign" IN (-1, 1) GROUP BY "target", "session_id", "_sign"` },
  { rel: "feed_view", kind: "set", tableName: "feed_view", deltaTableName: "__delta_feed_view", columns: ["target", "body"], arrivalAddSql: null, boundarySql: `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_feed_view" WHERE "_sign" IN (-1, 1) GROUP BY "target", "body", "_sign"` },
  { rel: "fill_arrived", kind: "log", tableName: "fill_arrived", deltaTableName: "__delta_fill_arrived", columns: ["target", "body"], arrivalAddSql: `INSERT INTO "fill_arrived" ("target", "body") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?) RETURNING "target", "body"`, boundarySql: `SELECT CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", CASE WHEN json_valid("body") AND json_type("body") = 'object' THEN json_extract("body", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body", '$.args')) || ')' ELSE "body" END AS "body", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_fill_arrived" WHERE "_sign" IN (-1, 1) GROUP BY "target", "body", "_sign"` },
  { rel: "open_feed", kind: "set", tableName: "open_feed", deltaTableName: "__delta_open_feed", columns: ["session_id", "target"], arrivalAddSql: `INSERT OR IGNORE INTO "open_feed" ("session_id", "target") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?) RETURNING "session_id", "target"`, boundarySql: `SELECT CASE WHEN json_valid("session_id") AND json_type("session_id") = 'object' THEN json_extract("session_id", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("session_id", '$.args')) || ')' ELSE "session_id" END AS "session_id", CASE WHEN json_valid("target") AND json_type("target") = 'object' THEN json_extract("target", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("target", '$.args')) || ')' ELSE "target" END AS "target", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_open_feed" WHERE "_sign" IN (-1, 1) GROUP BY "session_id", "target", "_sign"` },
];

const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = [
  { headRel: "cache_row", headKind: "set", headTableName: "cache_row", headDeltaTableName: "__delta_cache_row", headColumns: ["target", "body"], keyIndices: [0], projectSql: `SELECT d0."target" AS "target", d0."body" AS "body" FROM "__delta_fill_arrived" d0 WHERE d0."_sign" = 1 ORDER BY d0."_sequence"` },
];

const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = [
  { headRel: "demanded", headDeltaTableName: "__delta_demanded", headColumns: ["target", "session_id"], insertSql: `INSERT OR IGNORE INTO "demanded" ("target", "session_id") SELECT DISTINCT d0."target", d0."session_id" FROM "__delta_open_feed" d0 WHERE d0."_sign" = 1 RETURNING "target", "session_id"` },
  { headRel: "feed_view", headDeltaTableName: "__delta_feed_view", headColumns: ["target", "body"], insertSql: `INSERT OR IGNORE INTO "feed_view" ("target", "body") SELECT DISTINCT d0."target", b0."body" FROM "__delta_demanded" d0, "cache_row" b0 WHERE d0."_sign" = 1 AND b0."target" = d0."target" UNION ALL SELECT DISTINCT d0."target", d0."body" FROM "__delta_cache_row" d0, "demanded" b0 WHERE d0."_sign" = 1 AND b0."target" = d0."target" RETURNING "target", "body"` },
];

const EDGE_CACHE_ROW_0_PROJECT_SQL = `SELECT ?1 AS "target", ?2 AS "body"`;
const EDGE_CACHE_ROW_0_WRITE_SQL = `INSERT INTO "cache_row" ("target", "body") VALUES (?, ?) ON CONFLICT("target") DO UPDATE SET "body" = excluded."body"`;
const EDGE_CACHE_ROW_0_HEAD_COLUMNS: readonly string[] = ["target", "body"];
const EDGE_CACHE_ROW_0_KEY_INDICES: readonly number[] = [0];

function resolveCacheRow_0Writes(seam: ISqlSeam, before: Snapshot, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {
  const triggerRows = triggerOccurrences("log", "fill_arrived", before.fill_arrived, arrivals);
  if (triggerRows.length === 0) return of([]);
  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: EDGE_CACHE_ROW_0_PROJECT_SQL, args: bindArgs(arrival.row) }))).pipe(
    map((results) => {
      const resolved = new Map<string, IRow>();
      for (const result of results) {
        const projectedRows = result.rows.map((row) => EDGE_CACHE_ROW_0_HEAD_COLUMNS.map((column) => row[column] as IRowValue) as IRow);
        for (const projectedRow of projectedRows) {
          const key = JSON.stringify(EDGE_CACHE_ROW_0_KEY_INDICES.map((index) => projectedRow[index]));
          resolved.set(key, projectedRow);
        }
      }
      return [...resolved.values()].map((row): SqlStatement => ({ sql: EDGE_CACHE_ROW_0_WRITE_SQL, args: bindArgs(row) }));
    }),
  );
}

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "demanded";\nINSERT OR IGNORE INTO "demanded" ("target", "session_id") SELECT b0."target", b0."session_id" FROM "open_feed" b0;\nDELETE FROM "feed_view";\nINSERT OR IGNORE INTO "feed_view" ("target", "body") SELECT b0."target", b1."body" FROM "demanded" b0, "cache_row" b1 WHERE b1."target" = b0."target"`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const cache_row = multisetDiff(before.cache_row, after.cache_row);
  const demanded = multisetDiff(before.demanded, after.demanded);
  const feed_view = multisetDiff(before.feed_view, after.feed_view);
  const fill_arrived = multisetDiff(before.fill_arrived, after.fill_arrived);
  const open_feed = multisetDiff(before.open_feed, after.open_feed);
  return {
    rels: [
      { rel: "cache_row", add: cache_row.add, del: cache_row.del },
      { rel: "demanded", add: demanded.add, del: demanded.del },
      { rel: "feed_view", add: feed_view.add, del: feed_view.del },
      { rel: "fill_arrived", add: fill_arrived.add, del: fill_arrived.del },
      { rel: "open_feed", add: open_feed.add, del: open_feed.del },
    ],
    carryPending: cache_row.add.length > 0 || cache_row.del.length > 0,
  };
}

function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) =>
      resolveCacheRow_0Writes(seam, before, arrivals).pipe(
        concatMap((statements) => seam.runner.batch(seam.db, statements)),
        map(() => before),
      ),
    ),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // fill_as_cache_update_swr: engine.pl process_occurrences -> level_closure -> boundary_deltas.
}

const INCREMENTAL_PROGRAM_SAFE = false;
const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";

function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return IncrementalRuntime.clearDeltas(seam, INCREMENTAL_RELATIONS).pipe(
    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS)),
    concatMap(() => IncrementalRuntime.applyLevels(seam, INCREMENTAL_LEVEL_STATEMENTS)),
    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),
    map((rels): ITickDeltas => ({
      rels,
      carryPending: rels.some((delta) => ["cache_row"].includes(delta.rel) && (delta.add.length > 0 || delta.del.length > 0)),
    })),
  );
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  const hasRetraction = arrivals.some((arrival) => arrival.sign === "del");
  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE || hasRetraction) {
    return runNaiveTick(seam, arrivals);
  }
  return runIncrementalTick(seam, arrivals);
}

export const incrementalPlan: IIncrementalProgramPlan = {
  safe: INCREMENTAL_PROGRAM_SAFE,
  relations: INCREMENTAL_RELATIONS,
  edges: INCREMENTAL_EDGE_STATEMENTS,
  levels: INCREMENTAL_LEVEL_STATEMENTS,
};

export const program: IGenProgramWithBoot = {
  name: "fill_as_cache_update_swr",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  tick: runTick,
};
