// GENERATED by v6/prolog/compile (tsv2 emitter P3). Do not
// hand-edit; recompile. Program: fork_join_is_a_conjunctive_body.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// The default path stages effective tick changes in indexed TEMP tables,
// executes emitted frontier-side joins for positive level rules, promotes
// edge and post-write level growth across drain ticks, and computes boundary
// changes from the staged stream. Retractions and negative bodies use emitted
// support-count reconciliation. The snapshot path remains selectable with
// SPREFA_TSV2_EMITTER_MODE=naive as a byte-identity referee.
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { IncrementalRuntime } from "../runtime/1_incremental.ts";
import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IIncrementalEdgeStatement,
  IIncrementalLevelStatement,
  IIncrementalProgramPlan,
  IIncrementalRelationPlan,
  IRelDelta,
  IRow,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IHostColumnPlan { readonly name: string; readonly type: "int" | "text" | "json" }
interface IHostPlanData { readonly name: string; readonly inputs: readonly IHostColumnPlan[]; readonly outputs: readonly IHostColumnPlan[]; readonly template: string; readonly demandRel: string; readonly responseRel: string; readonly execution: string }
interface IBindPlanData { readonly name: string; readonly columns: readonly IHostColumnPlan[]; readonly execution: string }
interface IQueryPlanData { readonly rel: string; readonly arity: number; readonly snapshot: "current" }

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[]; readonly finalSelect: Record<string, string>; readonly hostPlans: readonly IHostPlanData[]; readonly bindPlans: readonly IBindPlanData[]; readonly queryPlans: readonly IQueryPlanData[]; readonly unsupportedExecution: readonly string[] };

export const hostPlans: readonly IHostPlanData[] = [];
export const bindPlans: readonly IBindPlanData[] = [];
export const queryPlans: readonly IQueryPlanData[] = [];
export const unsupportedExecution: readonly string[] = [];

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

const ddl: readonly string[] = [
  `CREATE TABLE "combined" ("value_a" TEXT NOT NULL, "value_b" TEXT NOT NULL, "__support_count" INTEGER NOT NULL DEFAULT 1, PRIMARY KEY ("value_a", "value_b")) WITHOUT ROWID`,
  `CREATE TABLE "result_a" ("value_a" TEXT NOT NULL, PRIMARY KEY ("value_a")) WITHOUT ROWID`,
  `CREATE TABLE "result_b" ("value_b" TEXT NOT NULL, PRIMARY KEY ("value_b")) WITHOUT ROWID`,
  `CREATE TEMP TABLE "__delta_combined" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_combined_sign" ON "__delta_combined" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_combined" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_combined_phase" ON "__frontier_combined" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_combined" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_combined_phase" ON "__next_frontier_combined" ("_phase")`,
  `CREATE TEMP TABLE "__delta_result_a" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_result_a_sign" ON "__delta_result_a" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_result_a" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_result_a_phase" ON "__frontier_result_a" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_result_a" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_a" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_result_a_phase" ON "__next_frontier_result_a" ("_phase")`,
  `CREATE TEMP TABLE "__delta_result_b" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_result_b_sign" ON "__delta_result_b" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_result_b" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_result_b_phase" ON "__frontier_result_b" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_result_b" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "value_b" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_result_b_phase" ON "__next_frontier_result_b" ("_phase")`,
  `CREATE TEMP TABLE "__support_next_combined" ("value_a" TEXT NOT NULL, "value_b" TEXT NOT NULL, "__support_count" INTEGER NOT NULL, PRIMARY KEY ("value_a", "value_b")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  combined: ["value_a", "value_b"],
  result_a: ["value_a"],
  result_b: ["value_b"],
};

const arrivalTargets: readonly string[] = ["result_a", "result_b"];

const boot: readonly IBootStatement[] = [
  { sql: `DELETE FROM "combined"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "combined" ("value_a", "value_b") SELECT b0."value_a", b1."value_b" FROM "result_a" b0, "result_b" b1`, params: [] },
];

type Snapshot = {
  readonly combined: readonly IRow[];
  readonly result_a: readonly IRow[];
  readonly result_b: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    combined: selectRows(seam, `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a", CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b" FROM "combined"`, relColumns.combined!),
    result_a: selectRows(seam, `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a" FROM "result_a"`, relColumns.result_a!),
    result_b: selectRows(seam, `SELECT CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b" FROM "result_b"`, relColumns.result_b!),
  });
}

const finalSelect: Record<string, string> = {
  combined: `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a", CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b" FROM "combined"`,
  result_a: `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a" FROM "result_a"`,
  result_b: `SELECT CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b" FROM "result_b"`,
};

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  result_a: { kind: "set", addSql: `INSERT OR IGNORE INTO "result_a" ("value_a") VALUES (?)`, delSql: `DELETE FROM "result_a" WHERE "value_a" = ?` },
  result_b: { kind: "set", addSql: `INSERT OR IGNORE INTO "result_b" ("value_b") VALUES (?)`, delSql: `DELETE FROM "result_b" WHERE "value_b" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`fork_join_is_a_conjunctive_body: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`fork_join_is_a_conjunctive_body: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`fork_join_is_a_conjunctive_body: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = [
  { rel: "combined", kind: "set", tableName: "combined", deltaTableName: "__delta_combined", frontierTableName: "__frontier_combined", nextFrontierTableName: "__next_frontier_combined", columns: ["value_a", "value_b"], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a", CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_combined" WHERE "_sign" IN (-1, 1) GROUP BY "value_a", "value_b", "_sign"` },
  { rel: "result_a", kind: "set", tableName: "result_a", deltaTableName: "__delta_result_a", frontierTableName: "__frontier_result_a", nextFrontierTableName: "__next_frontier_result_a", columns: ["value_a"], arrivalAddSql: `INSERT OR IGNORE INTO "result_a" ("value_a") SELECT json_extract(value, '$[0]') FROM json_each(?) RETURNING "value_a"`, arrivalDelSql: `DELETE FROM "result_a" WHERE ("value_a") IN (SELECT json_extract(value, '$[0]') FROM json_each(?)) RETURNING "value_a"`, boundarySql: `SELECT CASE WHEN json_valid("value_a") AND json_type("value_a") = 'object' THEN json_extract("value_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_a", '$.args')) || ')' ELSE "value_a" END AS "value_a", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_result_a" WHERE "_sign" IN (-1, 1) GROUP BY "value_a", "_sign"` },
  { rel: "result_b", kind: "set", tableName: "result_b", deltaTableName: "__delta_result_b", frontierTableName: "__frontier_result_b", nextFrontierTableName: "__next_frontier_result_b", columns: ["value_b"], arrivalAddSql: `INSERT OR IGNORE INTO "result_b" ("value_b") SELECT json_extract(value, '$[0]') FROM json_each(?) RETURNING "value_b"`, arrivalDelSql: `DELETE FROM "result_b" WHERE ("value_b") IN (SELECT json_extract(value, '$[0]') FROM json_each(?)) RETURNING "value_b"`, boundarySql: `SELECT CASE WHEN json_valid("value_b") AND json_type("value_b") = 'object' THEN json_extract("value_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("value_b", '$.args')) || ')' ELSE "value_b" END AS "value_b", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_result_b" WHERE "_sign" IN (-1, 1) GROUP BY "value_b", "_sign"` },
];

const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = [
];

const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = [
  { headRel: "combined", headDeltaTableName: "__delta_combined", headColumns: ["value_a", "value_b"], insertSql: `INSERT OR IGNORE INTO "combined" ("value_a", "value_b") SELECT DISTINCT d0."value_a", b0."value_b" FROM "__frontier_result_a" d0, "result_b" b0 WHERE d0."_phase" >= 0 UNION ALL SELECT DISTINCT b0."value_a", d0."value_b" FROM "__frontier_result_b" d0, "result_a" b0 WHERE d0."_phase" >= 0 RETURNING "value_a", "value_b"`, selectSql: `SELECT "value_a", "value_b" FROM "combined"`, recomputeSql: `DELETE FROM "combined";\nINSERT OR IGNORE INTO "combined" ("value_a", "value_b") SELECT b0."value_a", b1."value_b" FROM "result_a" b0, "result_b" b1`, supportSql: [`DELETE FROM "__support_next_combined"`, `INSERT INTO "__support_next_combined" ("value_a", "value_b", "__support_count") SELECT "value_a", "value_b", sum("__support_count") FROM (SELECT b0."value_a" AS "value_a", b1."value_b" AS "value_b", count(*) AS "__support_count" FROM "result_a" b0, "result_b" b1 GROUP BY b0."value_a", b1."value_b") GROUP BY "value_a", "value_b"`, `UPDATE "combined" AS h SET "__support_count" = "__support_count" - ("__support_count" - COALESCE((SELECT n."__support_count" FROM "__support_next_combined" n WHERE n."value_a" = h."value_a" AND n."value_b" = h."value_b"), 0))`, `DELETE FROM "combined" WHERE "__support_count" <= 0 RETURNING "value_a", "value_b"`, `INSERT INTO "combined" ("value_a", "value_b", "__support_count") SELECT "value_a", "value_b", n."__support_count" FROM "__support_next_combined" n WHERE NOT EXISTS (SELECT 1 FROM "combined" h WHERE n."value_a" = h."value_a" AND n."value_b" = h."value_b") RETURNING "value_a", "value_b"`], aggregateSql: null },
];

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "combined";\nINSERT OR IGNORE INTO "combined" ("value_a", "value_b") SELECT b0."value_a", b1."value_b" FROM "result_a" b0, "result_b" b1`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const combined = multisetDiff(before.combined, after.combined);
  const result_a = multisetDiff(before.result_a, after.result_a);
  const result_b = multisetDiff(before.result_b, after.result_b);
  return {
    rels: [
      { rel: "combined", add: combined.add, del: combined.del },
      { rel: "result_a", add: result_a.add, del: result_a.del },
      { rel: "result_b", add: result_b.add, del: result_b.del },
    ],
    carryPending: false,
  };
}

function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // fork_join_is_a_conjunctive_body: no edge rules -- absorb arrivals, recompute levels, diff.
}

const INCREMENTAL_PROGRAM_SAFE = true;
const RECONCILE_EVERY_TICK = false;
const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";

function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return IncrementalRuntime.prepareTick(seam, INCREMENTAL_RELATIONS).pipe(
    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyLevelsBeforeEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => of(undefined)),
    concatMap(() => of(undefined)),
    concatMap(() => IncrementalRuntime.recomputeLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS, RECONCILE_EVERY_TICK)),
    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),
    concatMap((rels) => IncrementalRuntime.promoteFrontiers(seam, INCREMENTAL_RELATIONS).pipe(
      map((carryPending): ITickDeltas => ({ rels, carryPending })),
    )),
  );
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE) {
    return runNaiveTick(seam, arrivals);
  }
  return runIncrementalTick(seam, arrivals);
}

export const incrementalPlan: IIncrementalProgramPlan = {
  safe: INCREMENTAL_PROGRAM_SAFE,
  reconcileEveryTick: RECONCILE_EVERY_TICK,
  retractionGuard: "plain-count-acyclic",
  relations: INCREMENTAL_RELATIONS,
  edges: INCREMENTAL_EDGE_STATEMENTS,
  levels: INCREMENTAL_LEVEL_STATEMENTS,
};

export const program: IGenProgramWithBoot = {
  name: "fork_join_is_a_conjunctive_body",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  finalSelect,
  hostPlans,
  bindPlans,
  queryPlans,
  unsupportedExecution,
  tick: runTick,
};
