// GENERATED by v6/prolog/compile (tsv2 Phase B, round 2). Do not
// hand-edit; recompile. Program: fork_join_error_arm_is_a_value.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// Strategy matches Phase A's hand-carved exemplar (gen/*.ts): read every
// rel's rows before a tick's writes and again after, diff with the
// runtime's multisetDiff (reused, never reimplemented -- one algorithm
// covers Set/level rels via plain set diff and Log rels via occurrence-count
// diff, since engine.pl r7's "one +Row per new stamp" for an append-only
// Log rel is exactly "count in next minus count in prev"). Edge-rule keyed
// writes are resolved in JS directly from the `arrivals` array (no tick
// number reaches tick() in the real seam -- the runtime owns tick
// numbering, ../runtime/tickLoop.ts -- so "this tick's fresh trigger rows"
// has no SQL-side answer; they ARE the arrivals argument already).
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IRow,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[] };

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

const ddl: readonly string[] = [
  `CREATE TABLE "any_failed" ("status" TEXT NOT NULL, PRIMARY KEY ("status")) WITHOUT ROWID`,
  `CREATE TABLE "both_ok" ("body_a" TEXT NOT NULL, "body_b" TEXT NOT NULL, PRIMARY KEY ("body_a", "body_b")) WITHOUT ROWID`,
  `CREATE TABLE "outcome_a" ("col1" TEXT NOT NULL, PRIMARY KEY ("col1")) WITHOUT ROWID`,
  `CREATE TABLE "outcome_b" ("col1" TEXT NOT NULL, PRIMARY KEY ("col1")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  any_failed: ["status"],
  both_ok: ["body_a", "body_b"],
  outcome_a: ["col1"],
  outcome_b: ["col1"],
};

const arrivalTargets: readonly string[] = ["outcome_a", "outcome_b"];

const boot: readonly IBootStatement[] = [
  { sql: `DELETE FROM "any_failed"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "any_failed" ("status") SELECT json_extract(b0."col1", '$.args[0]') FROM "outcome_a" b0 WHERE json_extract(b0."col1", '$.fn') = 'error'`, params: [] },
  { sql: `INSERT OR IGNORE INTO "any_failed" ("status") SELECT json_extract(b0."col1", '$.args[0]') FROM "outcome_b" b0 WHERE json_extract(b0."col1", '$.fn') = 'error'`, params: [] },
  { sql: `DELETE FROM "both_ok"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "both_ok" ("body_a", "body_b") SELECT json_extract(b0."col1", '$.args[0]'), json_extract(b1."col1", '$.args[0]') FROM "outcome_a" b0, "outcome_b" b1 WHERE json_extract(b0."col1", '$.fn') = 'ok' AND json_extract(b1."col1", '$.fn') = 'ok'`, params: [] },
];

type Snapshot = {
  readonly any_failed: readonly IRow[];
  readonly both_ok: readonly IRow[];
  readonly outcome_a: readonly IRow[];
  readonly outcome_b: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    any_failed: selectRows(seam, `SELECT CASE WHEN json_valid("status") AND json_type("status") = 'object' THEN json_extract("status", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("status", '$.args')) || ')' ELSE "status" END AS "status" FROM "any_failed"`, relColumns.any_failed!),
    both_ok: selectRows(seam, `SELECT CASE WHEN json_valid("body_a") AND json_type("body_a") = 'object' THEN json_extract("body_a", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body_a", '$.args')) || ')' ELSE "body_a" END AS "body_a", CASE WHEN json_valid("body_b") AND json_type("body_b") = 'object' THEN json_extract("body_b", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("body_b", '$.args')) || ')' ELSE "body_b" END AS "body_b" FROM "both_ok"`, relColumns.both_ok!),
    outcome_a: selectRows(seam, `SELECT CASE WHEN json_valid("col1") AND json_type("col1") = 'object' THEN json_extract("col1", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("col1", '$.args')) || ')' ELSE "col1" END AS "col1" FROM "outcome_a"`, relColumns.outcome_a!),
    outcome_b: selectRows(seam, `SELECT CASE WHEN json_valid("col1") AND json_type("col1") = 'object' THEN json_extract("col1", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("col1", '$.args')) || ')' ELSE "col1" END AS "col1" FROM "outcome_b"`, relColumns.outcome_b!),
  });
}

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  outcome_a: { kind: "set", addSql: `INSERT OR IGNORE INTO "outcome_a" ("col1") VALUES (?)`, delSql: `DELETE FROM "outcome_a" WHERE "col1" = ?` },
  outcome_b: { kind: "set", addSql: `INSERT OR IGNORE INTO "outcome_b" ("col1") VALUES (?)`, delSql: `DELETE FROM "outcome_b" WHERE "col1" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`fork_join_error_arm_is_a_value: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`fork_join_error_arm_is_a_value: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`fork_join_error_arm_is_a_value: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "any_failed";\nINSERT OR IGNORE INTO "any_failed" ("status") SELECT json_extract(b0."col1", '$.args[0]') FROM "outcome_a" b0 WHERE json_extract(b0."col1", '$.fn') = 'error';\nINSERT OR IGNORE INTO "any_failed" ("status") SELECT json_extract(b0."col1", '$.args[0]') FROM "outcome_b" b0 WHERE json_extract(b0."col1", '$.fn') = 'error';\nDELETE FROM "both_ok";\nINSERT OR IGNORE INTO "both_ok" ("body_a", "body_b") SELECT json_extract(b0."col1", '$.args[0]'), json_extract(b1."col1", '$.args[0]') FROM "outcome_a" b0, "outcome_b" b1 WHERE json_extract(b0."col1", '$.fn') = 'ok' AND json_extract(b1."col1", '$.fn') = 'ok'`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const any_failed = multisetDiff(before.any_failed, after.any_failed);
  const both_ok = multisetDiff(before.both_ok, after.both_ok);
  const outcome_a = multisetDiff(before.outcome_a, after.outcome_a);
  const outcome_b = multisetDiff(before.outcome_b, after.outcome_b);
  return {
    rels: [
      { rel: "any_failed", add: any_failed.add, del: any_failed.del },
      { rel: "both_ok", add: both_ok.add, del: both_ok.del },
      { rel: "outcome_a", add: outcome_a.add, del: outcome_a.del },
      { rel: "outcome_b", add: outcome_b.add, del: outcome_b.del },
    ],
    carryPending: false,
  };
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // fork_join_error_arm_is_a_value: no edge rules -- absorb arrivals, recompute levels, diff.
}

export const program: IGenProgramWithBoot = {
  name: "fork_join_error_arm_is_a_value",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  tick: runTick,
};
