// GENERATED by v6/prolog/compile (tsv2 emitter P3). Do not
// hand-edit; recompile. Program: groupby_aggregate_two_bare_integer_literals.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// The default path stages effective tick changes in indexed TEMP tables,
// executes emitted frontier-side joins for positive level rules, promotes
// edge and post-write level growth across drain ticks, and computes boundary
// changes from the staged stream. Retractions and negative bodies use emitted
// support-count reconciliation. The snapshot path remains selectable with
// SPREFA_TSV2_EMITTER_MODE=naive as a byte-identity referee.
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { IncrementalRuntime } from "../runtime/1_incremental.ts";
import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IIncrementalEdgeStatement,
  IIncrementalLevelStatement,
  IIncrementalProgramPlan,
  IIncrementalRelationPlan,
  IRelDelta,
  IRow,
  IRowColumnType,
  IRowValue,
  ISqlSeam,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IHostColumnPlan { readonly name: string; readonly type: string }
interface IHostPlanData { readonly name: string; readonly inputs: readonly IHostColumnPlan[]; readonly outputs: readonly IHostColumnPlan[]; readonly template: string; readonly demandRel: string; readonly responseRel: string; readonly execution: string }
interface IBindPlanData { readonly name: string; readonly columns: readonly IHostColumnPlan[]; readonly literals: readonly IRowValue[]; readonly execution: string }
interface IQueryPlanData { readonly rel: string; readonly arity: number; readonly snapshot: "current" }

interface IBootStatement {
  sql: string;
  params: readonly IRowValue[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[]; readonly finalSelect: Record<string, string>; readonly hostPlans: readonly IHostPlanData[]; readonly bindPlans: readonly IBindPlanData[]; readonly queryPlans: readonly IQueryPlanData[]; readonly unsupportedExecution: readonly string[] };

export const hostPlans: readonly IHostPlanData[] = [];
export const bindPlans: readonly IBindPlanData[] = [];
export const queryPlans: readonly IQueryPlanData[] = [];
export const unsupportedExecution: readonly string[] = [];

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => typeof value === "boolean" ? BigInt(value ? 1 : 0) : (typeof value === "number" && Number.isSafeInteger(value) ? BigInt(value) : value));
}

function validateArrivals(arrivals: IArrivalBatch): IArrivalBatch {
  return arrivals.map((arrival): IArrivalRow => {
    const types = relColumnTypes[arrival.rel];
    if (types === undefined || types.length !== arrival.row.length) throw new Error(`arrival shape mismatch for ${arrival.rel}`);
    const row = arrival.row.map((value, index): IRowValue => {
      const type = types[index];
      if (type === "bool") {
        if (typeof value !== "boolean") throw new Error(`bool arrival ${arrival.rel}[${index}] requires true or false`);
        return value;
      }
      if (type === "float") {
        if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`float arrival ${arrival.rel}[${index}] requires a finite number`);
        return Object.is(value, -0) ? 0 : value;
      }
      if (type === "int") {
        if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new Error(`int_out_of_range ${arrival.rel}[${index}]`);
      }
      return value;
    });
    return { ...arrival, row };
  });
}

const ddl: readonly string[] = [
  `CREATE TABLE "source" ("name" TEXT NOT NULL, PRIMARY KEY ("name")) WITHOUT ROWID`,
  `CREATE TABLE "tallied" ("line" INTEGER NOT NULL, "column" INTEGER NOT NULL, "total" INTEGER NOT NULL, "__support_count" INTEGER NOT NULL DEFAULT 1, PRIMARY KEY ("line", "column", "total")) WITHOUT ROWID`,
  `CREATE TEMP TABLE "__delta_source" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "name" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_source_sign" ON "__delta_source" ("_sign")`,
  `CREATE INDEX "__delta_source_group" ON "__delta_source" ("name")`,
  `CREATE TEMP TABLE "__frontier_source" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "name" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_source_phase" ON "__frontier_source" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_source" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "name" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_source_phase" ON "__next_frontier_source" ("_phase")`,
  `CREATE TEMP TABLE "__delta_tallied" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "line" INTEGER NOT NULL, "column" INTEGER NOT NULL, "total" INTEGER NOT NULL)`,
  `CREATE INDEX "__delta_tallied_sign" ON "__delta_tallied" ("_sign")`,
  `CREATE INDEX "__delta_tallied_group" ON "__delta_tallied" ("line", "column", "total")`,
  `CREATE TEMP TABLE "__frontier_tallied" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "line" INTEGER NOT NULL, "column" INTEGER NOT NULL, "total" INTEGER NOT NULL)`,
  `CREATE INDEX "__frontier_tallied_phase" ON "__frontier_tallied" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_tallied" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "line" INTEGER NOT NULL, "column" INTEGER NOT NULL, "total" INTEGER NOT NULL)`,
  `CREATE INDEX "__next_frontier_tallied_phase" ON "__next_frontier_tallied" ("_phase")`,
  `CREATE TEMP TABLE "__agg_scope_tallied" ("line" INTEGER NOT NULL, "column" INTEGER NOT NULL, PRIMARY KEY ("line", "column")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  source: ["name"],
  tallied: ["line", "column", "total"],
};

const relColumnTypes: Record<string, readonly IRowColumnType[]> = {
  source: ["text"],
  tallied: ["int", "int", "int"],
};

const arrivalTargets: readonly string[] = ["source"];

const boot: readonly IBootStatement[] = [
  { sql: `DELETE FROM "tallied"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "tallied" ("line", "column", "total") SELECT 0, 0, count(*) FROM "source" b0 GROUP BY (0 + 0), (0 + 0) HAVING count(*) > 0`, params: [] },
];

type Snapshot = {
  readonly source: readonly IRow[];
  readonly tallied: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    source: selectRows(seam, `SELECT CASE WHEN json_valid("name") AND json_type("name") = 'object' AND json_type("name", '$.fn') = 'text' AND json_type("name", '$.args') = 'array' THEN json_extract("name", '$.fn') || '(' || coalesce((SELECT group_concat(value, ',') FROM json_each("name", '$.args')), '') || ')' ELSE "name" END AS "name" FROM "source"`, relColumns.source!, relColumnTypes.source!),
    tallied: selectRows(seam, `SELECT "line", "column", "total" FROM "tallied"`, relColumns.tallied!, relColumnTypes.tallied!),
  });
}

const finalSelect: Record<string, string> = {
  source: `SELECT CASE WHEN json_valid("name") AND json_type("name") = 'object' AND json_type("name", '$.fn') = 'text' AND json_type("name", '$.args') = 'array' THEN json_extract("name", '$.fn') || '(' || coalesce((SELECT group_concat(value, ',') FROM json_each("name", '$.args')), '') || ')' ELSE "name" END AS "name" FROM "source"`,
  tallied: `SELECT "line", "column", "total" FROM "tallied"`,
};

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  source: { kind: "set", addSql: `INSERT OR IGNORE INTO "source" ("name") VALUES (?)`, delSql: `DELETE FROM "source" WHERE "name" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`groupby_aggregate_two_bare_integer_literals: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`groupby_aggregate_two_bare_integer_literals: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`groupby_aggregate_two_bare_integer_literals: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = [
  { rel: "source", kind: "set", tableName: "source", deltaTableName: "__delta_source", frontierTableName: "__frontier_source", nextFrontierTableName: "__next_frontier_source", columns: ["name"], columnTypes: ["text"], keyIndices: [], arrivalAddSql: `INSERT OR IGNORE INTO "source" ("name") SELECT json_extract(value, '$[0]') FROM json_each(?) RETURNING "name"`, arrivalDelSql: `DELETE FROM "source" WHERE ("name") IN (SELECT json_extract(value, '$[0]') FROM json_each(?)) RETURNING "name"`, boundarySql: `SELECT CASE WHEN json_valid("name") AND json_type("name") = 'object' AND json_type("name", '$.fn') = 'text' AND json_type("name", '$.args') = 'array' THEN json_extract("name", '$.fn') || '(' || coalesce((SELECT group_concat(value, ',') FROM json_each("name", '$.args')), '') || ')' ELSE "name" END AS "name", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_source" WHERE "_sign" IN (-1, 1) GROUP BY "name", "_sign"` },
  { rel: "tallied", kind: "set", tableName: "tallied", deltaTableName: "__delta_tallied", frontierTableName: "__frontier_tallied", nextFrontierTableName: "__next_frontier_tallied", columns: ["line", "column", "total"], columnTypes: ["int", "int", "int"], keyIndices: [], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT "line", "column", "total", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_tallied" WHERE "_sign" IN (-1, 1) GROUP BY "line", "column", "total", "_sign"` },
];

const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = [
];

const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = [
  { headRel: "tallied", headDeltaTableName: "__delta_tallied", headColumns: ["line", "column", "total"], insertSql: null, selectSql: `SELECT "line", "column", "total" FROM "tallied"`, recomputeSql: `DELETE FROM "tallied";
INSERT OR IGNORE INTO "tallied" ("line", "column", "total") SELECT 0, 0, count(*) FROM "source" b0 GROUP BY (0 + 0), (0 + 0) HAVING count(*) > 0`, supportSql: null, aggregateSql: { scopeClearSql: `DELETE FROM "__agg_scope_tallied"`, scopeSeedSql: [`INSERT OR IGNORE INTO "__agg_scope_tallied" ("line", "column") SELECT DISTINCT (0 + 0), (0 + 0) FROM "__delta_source" d0 WHERE d0."_sign" IN (-1, 1)`], deleteScopedSql: `DELETE FROM "tallied" WHERE ("line", "column") IN (SELECT "line", "column" FROM "__agg_scope_tallied") RETURNING "line", "column", "total"`, insertScopedSql: [`INSERT OR IGNORE INTO "tallied" ("line", "column", "total") SELECT 0, 0, count(*) FROM "source" b0 WHERE ((0 + 0), (0 + 0)) IN (SELECT "line", "column" FROM "__agg_scope_tallied") GROUP BY (0 + 0), (0 + 0) HAVING count(*) > 0 RETURNING "line", "column", "total"`], deltaMaintained: false } },
];

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "tallied";
INSERT OR IGNORE INTO "tallied" ("line", "column", "total") SELECT 0, 0, count(*) FROM "source" b0 GROUP BY (0 + 0), (0 + 0) HAVING count(*) > 0`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const source = multisetDiff(before.source, after.source);
  const tallied = multisetDiff(before.tallied, after.tallied);
  return {
    rels: [
      { rel: "source", add: source.add, del: source.del },
      { rel: "tallied", add: tallied.add, del: tallied.del },
    ],
    carryPending: false,
  };
}

function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // groupby_aggregate_two_bare_integer_literals: no edge rules -- absorb arrivals, recompute levels, diff.
}

const INCREMENTAL_PROGRAM_SAFE = true;
const RECONCILE_EVERY_TICK = false;
const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";

function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return IncrementalRuntime.prepareTick(seam, INCREMENTAL_RELATIONS).pipe(
    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyLevelsBeforeEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => of(undefined)),
    concatMap(() => of(undefined)),
    concatMap(() => IncrementalRuntime.recomputeLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS, RECONCILE_EVERY_TICK)),
    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),
    concatMap((rels) => IncrementalRuntime.promoteFrontiers(seam, INCREMENTAL_RELATIONS).pipe(
      map((carryPending): ITickDeltas => ({ rels, carryPending })),
    )),
  );
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  arrivals = validateArrivals(arrivals);
  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE) {
    return runNaiveTick(seam, arrivals);
  }
  return runIncrementalTick(seam, arrivals);
}

export const incrementalPlan: IIncrementalProgramPlan = {
  safe: INCREMENTAL_PROGRAM_SAFE,
  reconcileEveryTick: RECONCILE_EVERY_TICK,
  retractionGuard: "plain-count-acyclic",
  relations: INCREMENTAL_RELATIONS,
  edges: INCREMENTAL_EDGE_STATEMENTS,
  levels: INCREMENTAL_LEVEL_STATEMENTS,
};

export const program: IGenProgramWithBoot = {
  name: "groupby_aggregate_two_bare_integer_literals",
  ddl,
  relColumns,
  relColumnTypes,
  arrivalTargets,
  boot,
  finalSelect,
  hostPlans,
  bindPlans,
  queryPlans,
  unsupportedExecution,
  tick: runTick,
};
