// GENERATED by v6/prolog/compile (tsv2 emitter P3). Do not
// hand-edit; recompile. Program: struct_nested_value_renders_whole_tree.
// Compiles the reference engine's occurrence / keyed-replace / boundary-diff
// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not
// lower/lowerSql.ts's.
//
// The default path stages effective tick changes in indexed TEMP tables,
// executes emitted frontier-side joins for positive level rules, promotes
// edge and post-write level growth across drain ticks, and computes boundary
// changes from the staged stream. Retractions and negative bodies use emitted
// support-count reconciliation. The snapshot path remains selectable with
// SPREFA_TSV2_EMITTER_MODE=naive as a byte-identity referee.
//
// IGenProgram has no slot for boot-time work (seeding Initial rows before
// tick 1). `boot` is an extra field added beyond the five pinned names
// ("extend by adding fields, never renaming"); v6/tsv2/scripts/
// run-emitted.ts (the reconciliation runner) runs it after DDL and before
// the tick fold.

import { concatMap, forkJoin, map, of, type Observable } from "rxjs";

import { IncrementalRuntime } from "../runtime/1_incremental.ts";
import { multisetDiff } from "../runtime/diff.ts";
import { selectRows } from "../runtime/rows.ts";
import { StructPlane } from "../runtime/structPlane.ts";
import type {
  IArrivalBatch,
  IArrivalRow,
  IGenProgram,
  IIncrementalEdgeStatement,
  IIncrementalLevelStatement,
  IIncrementalProgramPlan,
  IIncrementalRelationPlan,
  IRelDelta,
  IRow,
  IRowValue,
  ISqlSeam,
  IStructRefColumns,
  IStructTypePlan,
  ITickDeltas,
  SqlStatement,
} from "../runtime/types.ts";

interface IHostColumnPlan { readonly name: string; readonly type: "int" | "text" | "json" }
interface IHostPlanData { readonly name: string; readonly inputs: readonly IHostColumnPlan[]; readonly outputs: readonly IHostColumnPlan[]; readonly template: string; readonly demandRel: string; readonly responseRel: string; readonly execution: string }
interface IBindPlanData { readonly name: string; readonly columns: readonly IHostColumnPlan[]; readonly literals: readonly (string | number)[]; readonly execution: string }
interface IQueryPlanData { readonly rel: string; readonly arity: number; readonly snapshot: "current" }

interface IBootStatement {
  sql: string;
  params: readonly (string | number)[];
}

type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[]; readonly finalSelect: Record<string, string>; readonly hostPlans: readonly IHostPlanData[]; readonly bindPlans: readonly IBindPlanData[]; readonly queryPlans: readonly IQueryPlanData[]; readonly unsupportedExecution: readonly string[] };

export const hostPlans: readonly IHostPlanData[] = [];
export const bindPlans: readonly IBindPlanData[] = [];
export const queryPlans: readonly IQueryPlanData[] = [];
export const unsupportedExecution: readonly string[] = [];

function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {
  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));
}

const STRUCT_TYPES: readonly IStructTypePlan[] = [
  { name: "span", columns: ["start", "end"], refs: [null, null], internSql: `INSERT OR IGNORE INTO "__dict_span" ("__semantic", "__rendered", "start", "end") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]'), json_extract(value, '$[2]'), json_extract(value, '$[3]') FROM json_each(?)`, lookupSql: `SELECT "__semantic", "__id" FROM "__dict_span" WHERE "__semantic" IN (SELECT value FROM json_each(?))` },
  { name: "place", columns: ["file", "at"], refs: [null, "span"], internSql: `INSERT OR IGNORE INTO "__dict_place" ("__semantic", "__rendered", "file", "at") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]'), json_extract(value, '$[2]'), json_extract(value, '$[3]') FROM json_each(?)`, lookupSql: `SELECT "__semantic", "__id" FROM "__dict_place" WHERE "__semantic" IN (SELECT value FROM json_each(?))` },
];

const STRUCT_REF_COLUMNS: IStructRefColumns = {
  "diag": ["place", null],
};

const ddl: readonly string[] = [
  `CREATE TABLE "__dict_span" ("__id" INTEGER PRIMARY KEY, "__semantic" TEXT NOT NULL, "__rendered" TEXT NOT NULL, "start" INTEGER NOT NULL, "end" INTEGER NOT NULL)`,
  `CREATE UNIQUE INDEX "__dict_span_semantic" ON "__dict_span" ("__semantic")`,
  `CREATE TABLE "__dict_place" ("__id" INTEGER PRIMARY KEY, "__semantic" TEXT NOT NULL, "__rendered" TEXT NOT NULL, "file" TEXT NOT NULL, "at" INTEGER NOT NULL)`,
  `CREATE UNIQUE INDEX "__dict_place_semantic" ON "__dict_place" ("__semantic")`,
  `CREATE TABLE "diag" ("where" INTEGER NOT NULL, "message" TEXT NOT NULL, PRIMARY KEY ("where", "message")) WITHOUT ROWID`,
  `CREATE TABLE "diag_file" ("file" TEXT NOT NULL, "__support_count" INTEGER NOT NULL DEFAULT 1, PRIMARY KEY ("file")) WITHOUT ROWID`,
  `CREATE TEMP TABLE "__delta_diag" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "where" INTEGER NOT NULL, "message" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_diag_sign" ON "__delta_diag" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_diag" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "where" INTEGER NOT NULL, "message" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_diag_phase" ON "__frontier_diag" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_diag" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "where" INTEGER NOT NULL, "message" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_diag_phase" ON "__next_frontier_diag" ("_phase")`,
  `CREATE TEMP TABLE "__delta_diag_file" ("_sign" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "file" TEXT NOT NULL)`,
  `CREATE INDEX "__delta_diag_file_sign" ON "__delta_diag_file" ("_sign")`,
  `CREATE TEMP TABLE "__frontier_diag_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "file" TEXT NOT NULL)`,
  `CREATE INDEX "__frontier_diag_file_phase" ON "__frontier_diag_file" ("_phase")`,
  `CREATE TEMP TABLE "__next_frontier_diag_file" ("_phase" INTEGER NOT NULL, "_sequence" INTEGER NOT NULL, "file" TEXT NOT NULL)`,
  `CREATE INDEX "__next_frontier_diag_file_phase" ON "__next_frontier_diag_file" ("_phase")`,
  `CREATE TEMP TABLE "__support_next_diag_file" ("file" TEXT NOT NULL, "__support_count" INTEGER NOT NULL, PRIMARY KEY ("file")) WITHOUT ROWID`,
];

const relColumns: Record<string, readonly string[]> = {
  diag: ["where", "message"],
  diag_file: ["file"],
};

const arrivalTargets: readonly string[] = ["diag"];

const boot: readonly IBootStatement[] = [
  { sql: `DELETE FROM "diag_file"`, params: [] },
  { sql: `INSERT OR IGNORE INTO "diag_file" ("file") SELECT b1."file" FROM "diag" b0, "__dict_place" b1 WHERE b1."__id" = b0."where"`, params: [] },
];

type Snapshot = {
  readonly diag: readonly IRow[];
  readonly diag_file: readonly IRow[];
};

function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {
  return forkJoin({
    diag: selectRows(seam, `SELECT (SELECT d."__rendered" FROM "__dict_place" d WHERE d."__id" = "where") AS "where", CASE WHEN json_valid("message") AND json_type("message") = 'object' THEN json_extract("message", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("message", '$.args')) || ')' ELSE "message" END AS "message" FROM "diag"`, relColumns.diag!),
    diag_file: selectRows(seam, `SELECT CASE WHEN json_valid("file") AND json_type("file") = 'object' THEN json_extract("file", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("file", '$.args')) || ')' ELSE "file" END AS "file" FROM "diag_file"`, relColumns.diag_file!),
  });
}

const finalSelect: Record<string, string> = {
  diag: `SELECT (SELECT d."__rendered" FROM "__dict_place" d WHERE d."__id" = "where") AS "where", CASE WHEN json_valid("message") AND json_type("message") = 'object' THEN json_extract("message", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("message", '$.args')) || ')' ELSE "message" END AS "message" FROM "diag"`,
  diag_file: `SELECT CASE WHEN json_valid("file") AND json_type("file") = 'object' THEN json_extract("file", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("file", '$.args')) || ')' ELSE "file" END AS "file" FROM "diag_file"`,
};

const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {
  diag: { kind: "set", addSql: `INSERT OR IGNORE INTO "diag" ("where", "message") VALUES (?, ?)`, delSql: `DELETE FROM "diag" WHERE "where" = ? AND "message" = ?` },
};

function arrivalStatement(arrival: IArrivalRow): SqlStatement {
  const template = ARRIVAL_STATEMENTS[arrival.rel];
  if (template === undefined) {
    throw new Error(`struct_nested_value_renders_whole_tree: tick received an arrival for undeclared rel '${arrival.rel}'`);
  }
  if (arrival.sign === "del") {
    if (template.kind === "log") {
      throw new Error(`struct_nested_value_renders_whole_tree: retract from log rel '${arrival.rel}' (engine.pl retract_from_log)`);
    }
    if (template.delSql === null) {
      throw new Error(`struct_nested_value_renders_whole_tree: rel '${arrival.rel}' has no delete statement`);
    }
    return { sql: template.delSql, args: bindArgs(arrival.row) };
  }
  return { sql: template.addSql, args: bindArgs(arrival.row) };
}

function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {
  const statements: SqlStatement[] = arrivals.map(arrivalStatement);
  return seam.runner.batch(seam.db, statements);
}

const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = [
  { rel: "diag", kind: "set", tableName: "diag", deltaTableName: "__delta_diag", frontierTableName: "__frontier_diag", nextFrontierTableName: "__next_frontier_diag", columns: ["where", "message"], keyIndices: [], arrivalAddSql: `INSERT OR IGNORE INTO "diag" ("where", "message") SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?) RETURNING "where", "message"`, arrivalDelSql: `DELETE FROM "diag" WHERE ("where", "message") IN (SELECT json_extract(value, '$[0]'), json_extract(value, '$[1]') FROM json_each(?)) RETURNING "where", "message"`, boundarySql: `SELECT (SELECT d."__rendered" FROM "__dict_place" d WHERE d."__id" = "where") AS "where", CASE WHEN json_valid("message") AND json_type("message") = 'object' THEN json_extract("message", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("message", '$.args')) || ')' ELSE "message" END AS "message", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_diag" WHERE "_sign" IN (-1, 1) GROUP BY "where", "message", "_sign"` },
  { rel: "diag_file", kind: "set", tableName: "diag_file", deltaTableName: "__delta_diag_file", frontierTableName: "__frontier_diag_file", nextFrontierTableName: "__next_frontier_diag_file", columns: ["file"], keyIndices: [], arrivalAddSql: null, arrivalDelSql: null, boundarySql: `SELECT CASE WHEN json_valid("file") AND json_type("file") = 'object' THEN json_extract("file", '$.fn') || '(' || (SELECT group_concat(value, ',') FROM json_each("file", '$.args')) || ')' ELSE "file" END AS "file", "_sign" AS "__sign", count(*) AS "__count" FROM "__delta_diag_file" WHERE "_sign" IN (-1, 1) GROUP BY "file", "_sign"` },
];

const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = [
];

const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = [
  { headRel: "diag_file", headDeltaTableName: "__delta_diag_file", headColumns: ["file"], insertSql: `INSERT OR IGNORE INTO "diag_file" ("file") SELECT DISTINCT b0."file" FROM "__frontier_diag" d0, "__dict_place" b0 WHERE d0."_phase" >= 0 AND b0."__id" = d0."where" RETURNING "file"`, selectSql: `SELECT "file" FROM "diag_file"`, recomputeSql: `DELETE FROM "diag_file";\nINSERT OR IGNORE INTO "diag_file" ("file") SELECT b1."file" FROM "diag" b0, "__dict_place" b1 WHERE b1."__id" = b0."where"`, supportSql: [`DELETE FROM "__support_next_diag_file"`, `INSERT INTO "__support_next_diag_file" ("file", "__support_count") SELECT "file", sum("__support_count") FROM (SELECT b1."file" AS "file", count(*) AS "__support_count" FROM "diag" b0, "__dict_place" b1 WHERE b1."__id" = b0."where" GROUP BY b1."file") GROUP BY "file"`, `UPDATE "diag_file" AS h SET "__support_count" = "__support_count" - ("__support_count" - COALESCE((SELECT n."__support_count" FROM "__support_next_diag_file" n WHERE n."file" = h."file"), 0))`, `DELETE FROM "diag_file" WHERE "__support_count" <= 0 RETURNING "file"`, `INSERT INTO "diag_file" ("file", "__support_count") SELECT "file", n."__support_count" FROM "__support_next_diag_file" n WHERE NOT EXISTS (SELECT 1 FROM "diag_file" h WHERE n."file" = h."file") RETURNING "file"`], aggregateSql: null },
];

function recomputeLevels(seam: ISqlSeam): Observable<void> {
  const sql = `DELETE FROM "diag_file";\nINSERT OR IGNORE INTO "diag_file" ("file") SELECT b1."file" FROM "diag" b0, "__dict_place" b1 WHERE b1."__id" = b0."where"`;
  return seam.runner.executeMultiple(seam.db, sql);
}

function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {
  const diag = multisetDiff(before.diag, after.diag);
  const diag_file = multisetDiff(before.diag_file, after.diag_file);
  return {
    rels: [
      { rel: "diag", add: diag.add, del: diag.del },
      { rel: "diag_file", add: diag_file.add, del: diag_file.del },
    ],
    carryPending: false,
  };
}

function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return readSnapshot(seam).pipe(
    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),
    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),
    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),
  );
  // struct_nested_value_renders_whole_tree: no edge rules -- absorb arrivals, recompute levels, diff.
}

const INCREMENTAL_PROGRAM_SAFE = true;
const RECONCILE_EVERY_TICK = false;
const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";

function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return IncrementalRuntime.prepareTick(seam, INCREMENTAL_RELATIONS).pipe(
    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyLevelsBeforeEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS, INCREMENTAL_RELATIONS)),
    concatMap(() => of(undefined)),
    concatMap(() => of(undefined)),
    concatMap(() => IncrementalRuntime.recomputeLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS, RECONCILE_EVERY_TICK)),
    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),
    concatMap((rels) => IncrementalRuntime.promoteFrontiers(seam, INCREMENTAL_RELATIONS).pipe(
      map((carryPending): ITickDeltas => ({ rels, carryPending })),
    )),
  );
}

function runTickOnInternedArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE) {
    return runNaiveTick(seam, arrivals);
  }
  return runIncrementalTick(seam, arrivals);
}

function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {
  return StructPlane.intern(seam, STRUCT_TYPES, STRUCT_REF_COLUMNS, arrivals).pipe(
    concatMap((interned) => runTickOnInternedArrivals(seam, interned)),
  );
}

export const incrementalPlan: IIncrementalProgramPlan = {
  safe: INCREMENTAL_PROGRAM_SAFE,
  reconcileEveryTick: RECONCILE_EVERY_TICK,
  retractionGuard: "plain-count-acyclic",
  relations: INCREMENTAL_RELATIONS,
  edges: INCREMENTAL_EDGE_STATEMENTS,
  levels: INCREMENTAL_LEVEL_STATEMENTS,
};

export const program: IGenProgramWithBoot = {
  name: "struct_nested_value_renders_whole_tree",
  ddl,
  relColumns,
  arrivalTargets,
  boot,
  finalSelect,
  hostPlans,
  bindPlans,
  queryPlans,
  unsupportedExecution,
  tick: runTick,
};
