[[seed]]
slug = "sprefa"
root = "/Users/chrishafley/projects/sprefa"
rev  = "HEAD"

[[seed]]
slug = "sprefa"
root = "/Users/chrishafley/projects/sprefa"
rev  = "test/1"

[[seed]]
slug = "sprefa"
root = "/Users/chrishafley/projects/sprefa"
rev  = "test/2"

[[seed]]
slug = "sprefa"
root = "/Users/chrishafley/projects/sprefa"
rev  = "test/3"
