[package]
name = "sprefa-v5"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dl"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled", "functions"] }
regex = "1"
globset = "0.4"
ignore = "0.4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blake3 = "1"
notify = "6"
rayon = "1"
syn = { version = "2", features = ["full"] }
tree-sitter = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-c = "0.24"
tree-sitter-json = "0.24"
streaming-iterator = "0.1"
ast-grep-core = "0.38"
ast-grep-language = "0.38"
lsp-server = "0.7.9"
lsp-types = "0.97.0"
oxc_resolver = "11.20.0"
toml = "1.1.2"
protobuf = "3.7"
scip = "0.7.1"
tree-sitter-yaml = "0.7"
tree-sitter-toml-ng = "0.7"
