% 1_emit_registry_docs.pl: regenerate SYNTAX.md's surface/5 table.
%
% Run:
%   swipl -q -l v6/prolog/compile/1_emit_registry_docs.pl \
%     -g emit_registry_docs -g halt

:- module(emit_registry_docs,
          [ emit_registry_docs/0,
            emit_dl6_grammar/0
          ]).

:- use_module(registry, [surface/5]).
:- use_module(library(lists)).

:- dynamic(compile_dir_fact/1).
:- prolog_load_context(directory, Here), assertz(compile_dir_fact(Here)).

begin_marker("<!-- BEGIN GENERATED surface/5 TABLE -->").
end_marker("<!-- END GENERATED surface/5 TABLE -->").

emit_registry_docs :-
    compile_dir_fact(CompileDir),
    atomic_list_concat([CompileDir, '/SYNTAX.md'], SyntaxPath),
    read_file_to_string(SyntaxPath, Existing, []),
    generated_table(Table),
    replace_generated_section(Existing, Table, Updated),
    setup_call_cleanup(
        open(SyntaxPath, write, Stream),
        format(Stream, '~s', [Updated]),
        close(Stream)),
    emit_dl6_grammar.

emit_dl6_grammar :-
    compile_dir_fact(CompileDir),
    file_directory_name(CompileDir, PrologDir),
    file_directory_name(PrologDir, V6Dir),
    atomic_list_concat([V6Dir, '/../editors/vscode-dl/syntaxes/dl6.tmLanguage.json'], GrammarPath),
    dl6_grammar(Text),
    setup_call_cleanup(
        open(GrammarPath, write, Stream),
        format(Stream, '~s', [Text]),
        close(Stream)).

dl6_grammar(Text) :-
    registry_word_regex(live, LiveWords),
    registry_word_regex(non_live, ReservedWords),
    json_quote(LiveWords, LiveRegex),
    json_quote(ReservedWords, ReservedRegex),
    format(string(Text),
`{
  "scopeName": "source.dl6",
  "name": "dl6",
  "comment": "GENERATED by v6/prolog/compile/1_emit_registry_docs.pl from registry.pl",
  "patterns": [{ "include": "#main" }],
  "repository": {
    "main": {
      "patterns": [
        { "include": "#comment" },
        { "include": "#template" },
        { "include": "#string" },
        { "include": "#atom" },
        { "include": "#number" },
        { "include": "#rule-arrow" },
        { "include": "#semicolon" },
        { "include": "#enum-shape" },
        { "include": "#decl-words" },
        { "include": "#live-keywords" },
        { "include": "#reserved-keywords" },
        { "include": "#relation-call" },
        { "include": "#operators" },
        { "include": "#variable" }
      ]
    },
    "comment": {
      "name": "comment.line.number-sign.dl6",
      "match": "#.*$"
    },
    "template": {
      "name": "string.quoted.template.dl6",
      "begin": "\\\\x60",
      "end": "\\\\x60",
      "patterns": [
        { "name": "constant.character.escape.dl6", "match": "\\\\." }
      ]
    },
    "string": {
      "name": "string.quoted.double.dl6",
      "begin": "\\\"",
      "end": "\\\"",
      "patterns": [
        { "name": "constant.character.escape.dl6", "match": "\\\\." }
      ]
    },
    "atom": {
      "name": "constant.language.atom.dl6",
      "begin": "'",
      "end": "'",
      "patterns": [
        { "name": "constant.character.escape.dl6", "match": "\\\\." }
      ]
    },
    "number": {
      "name": "constant.numeric.dl6",
      "match": "-?\\\\b\\\\d+\\\\b"
    },
    "rule-arrow": {
      "name": "keyword.operator.arrow.dl6",
      "match": "<-|<+|->"
    },
    "semicolon": {
      "name": "punctuation.separator.enum.dl6",
      "match": ";"
    },
    "enum-shape": {
      "name": "storage.type.enum.dl6",
      "match": "\\\\brel\\\\b(?=\\\\s+[a-z_]\\\\w*\\\\s*\\\\([^\\\\n]*;)"
    },
    "decl-words": {
      "name": "storage.type.declaration.dl6",
      "match": "\\\\b(rel|sh|bind|log|keep|key|int|text|json|salt)\\\\b"
    },
    "live-keywords": {
      "name": "keyword.control.dl6",
      "match": ~w
    },
    "reserved-keywords": {
      "name": "invalid.illegal.reserved.dl6",
      "match": ~w
    },
    "relation-call": {
      "name": "entity.name.function.dl6",
      "match": "\\\\b[a-z_]\\\\w*(?=\\\\()"
    },
    "operators": {
      "name": "keyword.operator.comparison.dl6",
      "match": ":=|<=|!=|==|>=|=<|\\\\==|<|>"
    },
    "variable": {
      "patterns": [
        {
          "name": "variable.other.constant.dl6",
          "match": "\\\\b[A-Z_][A-Za-z0-9_]*\\\\b"
        },
        {
          "name": "variable.other.readwrite.dl6",
          "match": "\\\\b[a-z][A-Za-z0-9_]*\\\\b"
        }
      ]
    }
  }
}
`, [LiveRegex, ReservedRegex]).

registry_word_regex(Which, Regex) :-
    findall(Name,
            ( surface(Name/Arity, Axis, _AnalyzeRole, _LowerRole, Status),
              ( Axis \== decl ; Name == set ),
              grammar_identifier(Name),
              grammar_arity(Arity),
              ( Which == live -> Status == live ; Status \== live )
            ),
            Names0),
    sort(Names0, Names),
    atomic_list_concat(Names, '|', Alternatives),
    format(atom(Regex), '\\b(~w)\\b', [Alternatives]).

grammar_arity(Arity) :- integer(Arity), !.
grammar_arity(variadic).

grammar_identifier(Name) :-
    atom_chars(Name, [First | Rest]),
    ( char_type(First, lower) ; First == '_' ),
    forall(member(Char, Rest), (char_type(Char, alnum) ; Char == '_')).

json_quote(Value, Quoted) :-
    atom_codes(Value, Codes),
    json_escape_codes(Codes, Escaped),
    atom_codes(EscapedAtom, Escaped),
    format(atom(Quoted), '"~w"', [EscapedAtom]).

json_escape_codes([], []).
json_escape_codes([Code | Rest], Out) :-
    ( Code =:= 0'\\ -> Escaped = [0'\\, 0'\\]
    ; Code =:= 0'" -> Escaped = [0'\\, 0'"]
    ; Code =:= 10 -> Escaped = [0'\\, 0'n]
    ; Code =:= 13 -> Escaped = [0'\\, 0'r]
    ; Code =:= 9 -> Escaped = [0'\\, 0't]
    ; Escaped = [Code]
    ),
    json_escape_codes(Rest, RestEscaped),
    append(Escaped, RestEscaped, Out).

generated_table(Table) :-
    findall(Line,
            ( surface(Signature, Axis, AnalyzeRole, LowerRole, Status),
              registry_row(Line, Signature, Axis, AnalyzeRole, LowerRole, Status)
            ),
            RowLines),
    atomic_list_concat(
        [ '| signature | axis | analyze role | lower role | status (writable surface) |\n',
          '|---|---|---|---|---|\n'
        | RowLines
        ],
        Table).

registry_row(Line, Functor/Arity, Axis, AnalyzeRole, LowerRole, Status) :-
    format(atom(SignatureText), '~w/~w', [Functor, Arity]),
    format(atom(AnalyzeText), '~q', [AnalyzeRole]),
    format(atom(LowerText), '~q', [LowerRole]),
    format(atom(Line), '| `~w` | `~w` | `~w` | `~w` | `~w` |~n',
           [SignatureText, Axis, AnalyzeText, LowerText, Status]).

replace_generated_section(Existing, Table, Updated) :-
    begin_marker(BeginMarker),
    end_marker(EndMarker),
    string_length(BeginMarker, BeginLength),
    sub_string(Existing, BeginAt, BeginLength, _, BeginMarker),
    PrefixLength is BeginAt + BeginLength,
    sub_string(Existing, 0, PrefixLength, _, Prefix),
    string_length(EndMarker, EndLength),
    sub_string(Existing, EndAt, EndLength, _, EndMarker),
    sub_string(Existing, EndAt, _, 0, Suffix),
    format(string(Updated), '~s~n~s~s', [Prefix, Table, Suffix]).
