% Generate the target-neutral CLI and HTTP inventory consumed by tsv2/cli.
%
% Run:
%   swipl -q -l v6/prolog/compile/2_emit_cli_inventory.pl \
%     -g emit_cli_inventory -g halt

:- module(emit_cli_inventory,
          [ emit_cli_inventory/0,
            cli_inventory_text/1
          ]).

:- use_module(registry, [cli_command/3, http_route/3]).

:- dynamic(compile_dir/1).
:- prolog_load_context(directory, Here), assertz(compile_dir(Here)).

emit_cli_inventory :-
    cli_inventory_text(Text),
    compile_dir(Here),
    directory_file_path(Here, '../../../v6/tsv2/cli/0_inventory.ts', Path),
    setup_call_cleanup(open(Path, write, Stream), format(Stream, '~s', [Text]), close(Stream)).

cli_inventory_text(Text) :-
    findall(Row, (cli_command(Verb, Args, Summary), command_row(Verb, Args, Summary, Row)), Commands),
    findall(Row, (http_route(Method, Path, Summary), route_row(Method, Path, Summary, Row)), Routes),
    atomic_list_concat(Commands, '\n', CommandText),
    atomic_list_concat(Routes, '\n', RouteText),
    format(string(Text),
'// GENERATED by v6/prolog/compile/2_emit_cli_inventory.pl from registry.pl.\n\nexport interface ICliCommandInventory { readonly verb: string; readonly args: string; readonly summary: string }\nexport interface IHttpRouteInventory { readonly method: string; readonly path: string; readonly summary: string }\n\nexport const CLI_COMMANDS: readonly ICliCommandInventory[] = [\n~w\n];\n\nexport const HTTP_ROUTES: readonly IHttpRouteInventory[] = [\n~w\n];\n',
           [CommandText, RouteText]).

command_row(Verb, Args, Summary, Row) :-
    format(atom(Row), '  { verb: "~w", args: "~w", summary: "~w" },', [Verb, Args, Summary]).

route_row(Method, Path, Summary, Row) :-
    format(atom(Row), '  { method: "~w", path: "~w", summary: "~w" },', [Method, Path, Summary]).
