% emit_ts.pl : prints a lowered/8 term as a literal TypeScript module
% conforming to IGenProgram (plans/2026-07-27-tsv2-compile-target-header.md,
% ADDENDUM). P1 emits two execution families. The default incremental family
% stages one tick's effective changes in indexed TEMP tables, runs inline
% delta-side joins for positive non-recursive level rules, and reads boundary
% changes from those tables. The recompute family remains available through
% SPREFA_TSV2_EMITTER_MODE=naive and remains the fallback for negative
% bodies and retraction ticks. P2 carries positive rule frontiers across
% drain ticks in per-relation current/next TEMP tables.
%
% Table-driven, not hand-unrolled: every rel's snapshot read / arrival
% statement / delta entry is one row in a compile-time array or record
% literal, the more "generated code" shape for a compiler meant to scale
% past two or three rels. The one genuinely dynamic-length pieces are
% `arrivals` itself (a runtime value: `.map()`/`.filter()` over it is plain
% array code, "sync stays sync") and the edge-write resolution's `forkJoin`
% over one query per matching arrival row (a real sequential IO fan-out,
% legitimately rx-shaped).
%
% SEAM NAMES: IGenProgram, ISqlSeam, IArrivalBatch, IArrivalRow, IRow,
% IRowValue, ITickDeltas, SqlStatement all imported from
% "../runtime/types.ts" (real file, merged). `IBootStatement` is a LOCAL
% type (the header's IGenProgram has no boot slot; "extend by adding
% fields, never renaming" -- v6/tsv2/scripts/run-emitted.ts confirms who
% runs it and when: after DDL, before the tick fold).

:- module(emit_ts, [ emit_program/5 ]).

:- use_module(library(lists)).
:- use_module(library(apply)).
% relplan_kind/3 (Ref -> log|set): PHASE C2 RULING 2's per-arm resolver needs
% the TRIGGER's kind (to choose the log-unconditional vs set-dedup branch of
% the emitted triggerOccurrences call), and RelPlans is available straight
% off the Lowered term this module already renders -- reused, not
% reimplemented.
:- use_module(lower, [ relplan_kind/3 ]).
:- use_module(analyze, [ body_ref_uses/2, rule_head_ref/2 ]).

:- op(1150, xfx, <-).
:- op(1150, xfx, <+).

% ═══ small text helpers ══════════════════════════════════════════════════════

lines_block(Lines, Text) :- atomic_list_concat(Lines, '\n', Text).

js_template(SqlText, JsLiteral) :-
    atom_string(SqlText, SqlString0),
    re_replace("`"/g, "\\`", SqlString0, SqlString1),
    re_replace("\\$\\{"/g, "\\${", SqlString1, SqlString2),
    format(atom(JsLiteral), '`~w`', [SqlString2]).

js_string(Atom, JsLiteral) :- format(atom(JsLiteral), '"~w"', [Atom]).

ref_name(Name/_Arity, Name).

upper_snake(Name/_Arity, Upper) :- upcase_atom(Name, Upper).

% snake_case -> PascalCase, for JS function/type names built by combining a
% rel name with a fixed prefix/suffix (e.g. "resolve" + "OpenScope" +
% "Writes") -- SCREAMING_SNAKE (upper_snake/2) is for SQL CONSTANT names,
% where it is idiomatic; mixing it into a camelCase function name
% (`resolveOPEN_SCOPEWrites`) is not.
pascal_case(Name/_Arity, Pascal) :- !, pascal_case(Name, Pascal).
pascal_case(Name, Pascal) :-
    atomic_list_concat(Parts, '_', Name),
    maplist(capitalize_atom, Parts, CapitalizedParts),
    atomic_list_concat(CapitalizedParts, Pascal).

capitalize_atom(Atom, Capitalized) :-
    atom_codes(Atom, [First | Rest]),
    code_type(UpperFirst, to_upper(First)),
    atom_codes(Capitalized, [UpperFirst | Rest]).

param_text(Param, Text) :- number(Param), !, format(atom(Text), '~w', [Param]).
param_text(Param, Text) :- js_string(Param, Text).

params_array_text(Params, Text) :-
    maplist(param_text, Params, ParamTexts),
    atomic_list_concat(ParamTexts, ', ', Joined),
    format(atom(Text), '[~w]', [Joined]).

quoted_string_array_text(Atoms, Text) :-
    maplist(js_string, Atoms, Quoted),
    atomic_list_concat(Quoted, ', ', Joined),
    format(atom(Text), '[~w]', [Joined]).

% Flattens a list of line-groups into one line list, one blank line between
% groups (never trailing).
flatten_with_blank_separators([], []).
flatten_with_blank_separators([Group], Group) :- !.
flatten_with_blank_separators([Group | Rest], Lines) :-
    flatten_with_blank_separators(Rest, RestLines),
    append(Group, [''], WithBlank),
    append(WithBlank, RestLines, Lines).

% ═══ header comment ══════════════════════════════════════════════════════════

header_lines(Name, Lines) :-
    format(atom(TitleLine), '// GENERATED by v6/prolog/compile (tsv2 emitter P3). Do not', []),
    format(atom(NameLine), '// hand-edit; recompile. Program: ~w.', [Name]),
    Lines =
    [ TitleLine, NameLine,
      '// Compiles the reference engine\'s occurrence / keyed-replace / boundary-diff',
      '// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not',
      '// lower/lowerSql.ts\'s.',
      '//',
      '// The default path stages effective tick changes in indexed TEMP tables,',
      '// executes emitted frontier-side joins for positive level rules, promotes',
      '// edge and post-write level growth across drain ticks, and computes boundary',
      '// changes from the staged stream. Retractions and negative bodies use emitted',
      '// support-count reconciliation. The snapshot path remains selectable with',
      '// SPREFA_TSV2_EMITTER_MODE=naive as a byte-identity referee.',
      '//',
      '// IGenProgram has no slot for boot-time work (seeding Initial rows before',
      '// tick 1). `boot` is an extra field added beyond the five pinned names',
      '// ("extend by adding fields, never renaming"); v6/tsv2/scripts/',
      '// run-emitted.ts (the reconciliation runner) runs it after DDL and before',
      '// the tick fold.'
    ].

% ═══ imports ═════════════════════════════════════════════════════════════════

imports_lines(_HasEdgeRules,
    [ 'import { concatMap, forkJoin, map, of, type Observable } from "rxjs";',
      '',
      'import { IncrementalRuntime } from "../runtime/1_incremental.ts";',
      'import { multisetDiff } from "../runtime/diff.ts";',
      'import { selectRows } from "../runtime/rows.ts";',
      'import type {',
      '  IArrivalBatch,',
      '  IArrivalRow,',
      '  IGenProgram,',
      '  IIncrementalEdgeStatement,',
      '  IIncrementalLevelStatement,',
      '  IIncrementalProgramPlan,',
      '  IIncrementalRelationPlan,',
      '  IRelDelta,',
      '  IRow,',
      '  IRowValue,',
      '  ISqlSeam,',
      '  ITickDeltas,',
      '  SqlStatement,',
      '} from "../runtime/types.ts";'
    ]).
    % `of` covers two zero-op shapes, not just the edge-rule forkJoin([])
    % guard it was originally added for: an edge-free tick still needs it for
    % edge_resolver_block/3's `of([])` when EdgeStatements is nonempty, AND
    % recompute_levels_fn_lines/2's no-level-rules fallback below needs
    % `of(undefined)`. Always importing it is simpler than tracking two
    % independent conditions, and tsconfig.json carries no
    % noUnusedLocals/noUnusedParameters flag, so an unused import is not a
    % typecheck error on the (rare) program shape that needs neither.

% ═══ local supporting types ══════════════════════════════════════════════════

local_types_lines(
    [ 'interface IBootStatement {',
      '  sql: string;',
      '  params: readonly (string | number)[];',
      '}',
      '',
      'type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[] };'
    ]).

% ═══ integer bind helper (phase C sweep finding) ═══════════════════════════
% @libsql/client binds a JS `number` parameter as SQLite REAL, not INTEGER --
% verified empirically (a bound `1` lands as the TEXT value "1.0" in a
% TEXT-affinity column, `1n` lands as "1"), a driver behavior, not a bug in
% any SQL text this compiler emits. A TEXT column (lower.pl:column_def/3)
% therefore needs an integer-valued arrival or edge-projected value to cross
% the driver seam as a bigint to keep its digit-for-digit text form; an
% INTEGER column (PHASE C2 RULING 1) round-trips correctly either way
% (verified empirically: both a bound bigint and a bound plain number land
% as SQLite INTEGER storage and read back as a JS number), so applying this
% unconditionally to every bind is simplest and correct for both column
% types. A genuine fractional number (none in this compiler's corpus today)
% passes through unchanged. Used everywhere a raw IRow (an arrival's own
% row, or an edge projection's numbered-placeholder bind) becomes
% SqlStatement args.

% The return type is NOT `readonly` -- @libsql/client's own `InArgs` is
% `InValue[]`, a mutable array type, so a `readonly` array here would fail
% typecheck at every call site despite being correct at runtime (`.map()`
% already returns a fresh mutable array; the annotation was simply too
% narrow).
bind_args_helper_lines(
    [ 'function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {',
      '  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));',
      '}'
    ]).

% ═══ trigger occurrence helper (PHASE C2 RULING 2) ══════════════════════════
% engine.pl's absorb_arrivals/8 (r7 + q1): a Log rel's `+Row` arrival is
% UNCONDITIONALLY a trigger occurrence (duplicates stack, r7 "one +Row per
% new stamp"); a Set rel's `+Row` arrival is a trigger occurrence ONLY when
% the row was not already present -- an exact-duplicate add is dedup, not a
% new occurrence, and mints no trigger. The dedup check is PROGRESSIVE
% across one tick's own arrival list (engine.pl folds Store0 forward through
% absorb_arrivals/8's own recursion), not just against the tick-start
% snapshot: two identical `+Row` arrivals to a Set rel in the SAME tick
% occurrence-fire only the FIRST. `beforeRows` is the tick-start snapshot
% (runTick's own `before`, captured by readSnapshot before this tick's
% applyArrivals runs); `seen` starts from it and grows as earlier arrivals
% in THIS tick are folded in, exactly mirroring that recursion.
trigger_occurrences_helper_lines(
    [ 'function triggerOccurrences(',
      '  kind: "log" | "set",',
      '  relName: string,',
      '  beforeRows: readonly IRow[],',
      '  arrivals: IArrivalBatch,',
      '): IArrivalBatch {',
      '  if (kind === "log") return arrivals.filter((arrival) => arrival.rel === relName && arrival.sign === "add");',
      '  const seen = new Set<string>(beforeRows.map((row) => JSON.stringify(row)));',
      '  const occurrences: IArrivalRow[] = [];',
      '  for (const arrival of arrivals) {',
      '    if (arrival.rel !== relName || arrival.sign !== "add") continue;',
      '    const key = JSON.stringify(arrival.row);',
      '    if (seen.has(key)) continue;',
      '    seen.add(key);',
      '    occurrences.push(arrival);',
      '  }',
      '  return occurrences;',
      '}'
    ]).

% ═══ ddl ═════════════════════════════════════════════════════════════════════

ddl_lines(Ddl, Lines) :-
    maplist(ddl_entry_line, Ddl, EntryLines),
    append([ ['const ddl: readonly string[] = ['], EntryLines, ['];'] ], Lines).

ddl_entry_line(Sql, Line) :- js_template(Sql, Template), format(atom(Line), '  ~w,', [Template]).

% ═══ relColumns / arrivalTargets ═════════════════════════════════════════════

rel_columns_lines(RelPlans, Lines) :-
    maplist(rel_columns_entry_line, RelPlans, EntryLines),
    append([ ['const relColumns: Record<string, readonly string[]> = {'], EntryLines, ['};'] ], Lines).

rel_columns_entry_line(relplan(Ref, _Kind, Columns, _Key, _ColumnTypes), Line) :-
    ref_name(Ref, Name),
    quoted_string_array_text(Columns, ColumnsSql),
    format(atom(Line), '  ~w: ~w,', [Name, ColumnsSql]).

arrival_targets_lines(ArrivalTargets, Lines) :-
    maplist(ref_name, ArrivalTargets, Names),
    quoted_string_array_text(Names, Sql),
    format(atom(Line), 'const arrivalTargets: readonly string[] = ~w;', [Sql]),
    Lines = [Line].

% ═══ boot ════════════════════════════════════════════════════════════════════

boot_lines(BootStatements, Lines) :-
    maplist(boot_entry_line, BootStatements, EntryLines),
    append([ ['const boot: readonly IBootStatement[] = ['], EntryLines, ['];'] ], Lines).

boot_entry_line(bootstmt(Sql, Params), Line) :-
    js_template(Sql, Template),
    params_array_text(Params, ParamsText),
    format(atom(Line), '  { sql: ~w, params: ~w },', [Template, ParamsText]).

% ═══ snapshot type + reader (forkJoin over selectRows, one entry per rel) ════

snapshot_type_lines(RelPlans, Lines) :-
    maplist(snapshot_field_line, RelPlans, FieldLines),
    append([ ['type Snapshot = {'], FieldLines, ['};'] ], Lines).

snapshot_field_line(relplan(Ref, _Kind, _Columns, _Key, _ColumnTypes), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '  readonly ~w: readonly IRow[];', [Name]).

% forkJoin({}) (zero keys) completes WITHOUT emitting, same hazard the
% edge-resolver's forkJoin([]) guard already documents (verified against
% rxjs 7.8.2, not assumed) -- a program with zero declared rels (Decls and
% Rules both empty; every phase-C fixture found so far avoids this via
% analyze.pl:declared_refs/2, but nothing upstream forbids it structurally)
% would otherwise stall runTick's very first concatMap forever. `of({})` is
% the one-value-then-complete fallback, matching recompute_levels_fn_lines/2's
% [] case just below.
read_snapshot_fn_lines([], Lines) :- !,
    Lines =
    [ 'function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {',
      '  void seam;',
      '  return of({} as Snapshot);',
      '}'
    ].
read_snapshot_fn_lines(DeltaStatements, Lines) :-
    DeltaStatements \== [],
    maplist(snapshot_read_entry_line, DeltaStatements, EntryLines),
    append(
        [ ['function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {', '  return forkJoin({'],
          EntryLines,
          ['  });', '}']
        ], Lines).

snapshot_read_entry_line(deltastmt(Ref, SelectSql, _DeltaTable, _BoundarySql), Line) :-
    ref_name(Ref, Name),
    js_template(SelectSql, Template),
    format(atom(Line), '    ~w: selectRows(seam, ~w, relColumns.~w!),', [Name, Template, Name]).

% ═══ arrivals ════════════════════════════════════════════════════════════════

arrival_statements_lines(ArrivalStatements, Lines) :-
    maplist(arrival_statement_entry_line, ArrivalStatements, EntryLines),
    append(
        [ ['const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {'],
          EntryLines,
          ['};']
        ], Lines).

arrival_statement_entry_line(arrivalstmt(Ref, log, AddSql, none, _, _), Line) :- !,
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    format(atom(Line), '  ~w: { kind: "log", addSql: ~w, delSql: null },', [Name, AddTemplate]).
arrival_statement_entry_line(arrivalstmt(Ref, set, AddSql, DelSql, _, _), Line) :-
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    js_template(DelSql, DelTemplate),
    format(atom(Line), '  ~w: { kind: "set", addSql: ~w, delSql: ~w },', [Name, AddTemplate, DelTemplate]).

arrival_statement_fn_lines(Name, Lines) :-
    format(atom(UndeclaredError), '    throw new Error(`~w: tick received an arrival for undeclared rel \'${arrival.rel}\'`);', [Name]),
    format(atom(RetractLogError), '      throw new Error(`~w: retract from log rel \'${arrival.rel}\' (engine.pl retract_from_log)`);', [Name]),
    format(atom(NoDeleteError), '      throw new Error(`~w: rel \'${arrival.rel}\' has no delete statement`);', [Name]),
    Lines =
    [ 'function arrivalStatement(arrival: IArrivalRow): SqlStatement {',
      '  const template = ARRIVAL_STATEMENTS[arrival.rel];',
      '  if (template === undefined) {',
      UndeclaredError,
      '  }',
      '  if (arrival.sign === "del") {',
      '    if (template.kind === "log") {',
      RetractLogError,
      '    }',
      '    if (template.delSql === null) {',
      NoDeleteError,
      '    }',
      '    return { sql: template.delSql, args: bindArgs(arrival.row) };',
      '  }',
      '  return { sql: template.addSql, args: bindArgs(arrival.row) };',
      '}',
      '',
      'function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {',
      '  const statements: SqlStatement[] = arrivals.map(arrivalStatement);',
      '  return seam.runner.batch(seam.db, statements);',
      '}'
    ].

% ═══ incremental relation plans ══════════════════════════════════════════════

incremental_relation_lines(RelPlans, ArrivalStatements, DeltaStatements, Lines) :-
    maplist(incremental_relation_entry_line(RelPlans, ArrivalStatements),
            DeltaStatements, EntryLines),
    append(
        [ ['const INCREMENTAL_RELATIONS: readonly IIncrementalRelationPlan[] = ['],
          EntryLines,
          ['];']
        ], Lines).

incremental_relation_entry_line(RelPlans, ArrivalStatements,
        deltastmt(Ref, _SelectSql, DeltaTable, BoundarySql), Line) :-
    ref_name(Ref, Name),
    relplan_kind(RelPlans, Ref, Kind),
    memberchk(relplan(Ref, _, Columns, _, _), RelPlans),
    quoted_string_array_text(Columns, ColumnsText),
    ( memberchk(arrivalstmt(Ref, _, _, _, ArrivalAddSql, _), ArrivalStatements)
    -> js_template(ArrivalAddSql, ArrivalAddTemplate)
    ; ArrivalAddTemplate = null
    ),
    ( memberchk(arrivalstmt(Ref, _, _, _, _, ArrivalDelSql), ArrivalStatements),
      ArrivalDelSql \== none
    -> js_template(ArrivalDelSql, ArrivalDelTemplate)
    ; ArrivalDelTemplate = null
    ),
    js_template(BoundarySql, BoundaryTemplate),
    format(atom(FrontierTable), '__frontier_~w', [Name]),
    format(atom(NextFrontierTable), '__next_frontier_~w', [Name]),
    format(atom(Line),
           '  { rel: "~w", kind: "~w", tableName: "~w", deltaTableName: "~w", frontierTableName: "~w", nextFrontierTableName: "~w", columns: ~w, arrivalAddSql: ~w, arrivalDelSql: ~w, boundarySql: ~w },',
           [Name, Kind, Name, DeltaTable, FrontierTable, NextFrontierTable,
            ColumnsText, ArrivalAddTemplate, ArrivalDelTemplate,
            BoundaryTemplate]).

incremental_edge_statement_lines(EdgeStatements, RelPlans, Lines) :-
    maplist(incremental_edge_statement_entry_line(RelPlans), EdgeStatements, EntryLines),
    append(
        [ ['const INCREMENTAL_EDGE_STATEMENTS: readonly IIncrementalEdgeStatement[] = ['],
          EntryLines,
          ['];']
        ], Lines).

incremental_edge_statement_entry_line(RelPlans,
        edgestmt(HeadRef, _TriggerRef, HeadColumns, KeyColumns, _ProjectSql,
                 _WriteSql, DeltaProjectSql), Line) :-
    ref_name(HeadRef, HeadName),
    relplan_kind(RelPlans, HeadRef, HeadKind),
    format(atom(DeltaTable), '__delta_~w', [HeadName]),
    quoted_string_array_text(HeadColumns, ColumnsText),
    key_indices(HeadColumns, KeyColumns, KeyIndices),
    atomic_list_concat(KeyIndices, ', ', KeyIndicesText),
    js_template(DeltaProjectSql, DeltaProjectTemplate),
    format(atom(Line),
           '  { headRel: "~w", headKind: "~w", headTableName: "~w", headDeltaTableName: "~w", headColumns: ~w, keyIndices: [~w], projectSql: ~w },',
           [HeadName, HeadKind, HeadName, DeltaTable, ColumnsText,
            KeyIndicesText, DeltaProjectTemplate]).

incremental_level_statement_lines(LevelStatements, RelPlans, Lines) :-
    maplist(incremental_level_statement_entry_line(RelPlans),
            LevelStatements, EntryLines),
    append(
        [ ['const INCREMENTAL_LEVEL_STATEMENTS: readonly IIncrementalLevelStatement[] = ['],
          EntryLines,
          ['];']
        ], Lines).

incremental_level_statement_entry_line(RelPlans,
        levelstmt(HeadRef, DeleteSql, InsertSqls, DeltaInsertSql,
                  supportsql(ClearSql, SeedSql, UpdateSql, CollectZeroSql,
                             InsertNewSql)), Line) :-
    ref_name(HeadRef, HeadName),
    format(atom(DeltaTable), '__delta_~w', [HeadName]),
    memberchk(relplan(HeadRef, _, HeadColumns, _, _), RelPlans),
    quoted_string_array_text(HeadColumns, ColumnsText),
    js_template(DeltaInsertSql, DeltaInsertTemplate),
    maplist(quote_ident_local, HeadColumns, QuotedHeadColumns),
    atomic_list_concat(QuotedHeadColumns, ', ', HeadColumnsSql),
    format(atom(SelectSql), 'SELECT ~w FROM "~w"', [HeadColumnsSql, HeadName]),
    js_template(SelectSql, SelectTemplate),
    atomic_list_concat([DeleteSql | InsertSqls], ';\\n', RecomputeSql),
    js_template(RecomputeSql, RecomputeTemplate),
    maplist(js_template,
            [ClearSql, SeedSql, UpdateSql, CollectZeroSql, InsertNewSql],
            [ClearTemplate, SeedTemplate, UpdateTemplate, CollectZeroTemplate,
             InsertNewTemplate]),
    format(atom(Line),
           '  { headRel: "~w", headDeltaTableName: "~w", headColumns: ~w, insertSql: ~w, selectSql: ~w, recomputeSql: ~w, supportSql: [~w, ~w, ~w, ~w, ~w] },',
           [HeadName, DeltaTable, ColumnsText, DeltaInsertTemplate,
            SelectTemplate, RecomputeTemplate, ClearTemplate, SeedTemplate,
            UpdateTemplate, CollectZeroTemplate, InsertNewTemplate]).

quote_ident_local(Name, Quoted) :- format(atom(Quoted), '"~w"', [Name]).

% ═══ edge rule resolution (one resolver function per ARM -- PHASE C2 RULING
% 2: an unmarked_conjunction rule with N body atoms lowers to N edgestmt
% entries, one per atom acting as trigger) ═══════════════════════════════
% ProjectSql (from lower.pl) is already aliased AS HeadColumns
% (lower.pl:edge_statement_single/5 passes HeadColumns, not `none`, to
% head_select_list/4 for exactly this reason), so the resolver reads each
% projected row back by named column access the same way runtime/rows.ts's
% selectRows does -- no string surgery on the SQL text happens in this file.
%
% A trigger occurrence's ProjectSql, once OtherAtoms is nonempty, is a real
% JOIN and can return ZERO, ONE, or MANY rows for a SINGLE triggering
% arrival (the forkJoin/rendezvous case the ruling names: the LAST-arriving
% input's occurrence, joined against every CURRENTLY matching row of the
% other atoms, can multiply). The resolver therefore iterates
% `result.rows` in full, not just its first entry (round 2's shape, correct
% only when there was never another atom to join).
%
% Global Index (this arm's 0-based position in the WHOLE flattened
% EdgeStatements list, not per-head) disambiguates names: multiple rules
% -- or multiple arms of ONE rule -- can share a HeadRef (merge_family.pl's
% `out(Item) <+ event_a(Item)` / `out(Item) <+ event_b(Item)`), which would
% otherwise collide on `resolve<Head>Writes`.

edge_resolver_blocks(EdgeStatements, RelPlans, ConstLines, FnLines) :-
    findall(Index-EdgeStmt, nth0(Index, EdgeStatements, EdgeStmt), IndexedStatements),
    maplist(edge_resolver_block_indexed(RelPlans), IndexedStatements, ConstLineGroups, FnLineGroups),
    flatten_with_blank_separators(ConstLineGroups, ConstLines),
    flatten_with_blank_separators(FnLineGroups, FnLines).

edge_resolver_block_indexed(RelPlans, Index-edgestmt(HeadRef, TriggerRef, HeadColumns, KeyColumns, ProjectSql, WriteSql, _DeltaProjectSql), ConstLines, FnLines) :-
    relplan_kind(RelPlans, TriggerRef, TriggerKind),
    relplan_kind(RelPlans, HeadRef, HeadKind),
    edge_resolver_block(edgestmt(HeadRef, TriggerRef, HeadColumns, KeyColumns, ProjectSql, WriteSql, _), TriggerKind, HeadKind, Index, ConstLines, FnLines).

% HeadKind decides how projected rows become SqlStatements (engine.pl
% apply_edge_writes/6, :236-254, unchanged distinction from before this
% ruling): a `set` head upserts by key, LAST WRITE WINS across every
% triggering arrival AND every row a single arrival's join produced (a
% `Map<string, IRow>` keyed by the key-column values, natural overwrite via
% `.set()`); a `log` head APPENDS every projected row unconditionally --
% collapsing through a key Map would be wrong (KeyColumns is `[]` for a Log
% head, so every row would collapse to the SAME key and only the last
% survive, contradicting q1's "duplicate rows are distinct occurrences").
edge_resolver_block(edgestmt(HeadRef, TriggerRef, HeadColumns, KeyColumns, ProjectSql, WriteSql, _DeltaProjectSql), TriggerKind, HeadKind, Index, ConstLines, FnLines) :-
    ref_name(TriggerRef, TriggerName),
    upper_snake(HeadRef, Upper),
    format(atom(ProjectConst), 'EDGE_~w_~w_PROJECT_SQL', [Upper, Index]),
    format(atom(WriteConst), 'EDGE_~w_~w_WRITE_SQL', [Upper, Index]),
    format(atom(ColumnsConst), 'EDGE_~w_~w_HEAD_COLUMNS', [Upper, Index]),
    js_template(ProjectSql, ProjectTemplate),
    js_template(WriteSql, WriteTemplate),
    quoted_string_array_text(HeadColumns, ColumnsArrayText),
    format(atom(ProjectLine), 'const ~w = ~w;', [ProjectConst, ProjectTemplate]),
    format(atom(WriteLine), 'const ~w = ~w;', [WriteConst, WriteTemplate]),
    format(atom(ColumnsLine), 'const ~w: readonly string[] = ~w;', [ColumnsConst, ColumnsArrayText]),
    ( HeadKind == log
    -> ConstLines = [ProjectLine, WriteLine, ColumnsLine]
    ;  format(atom(IndicesConst), 'EDGE_~w_~w_KEY_INDICES', [Upper, Index]),
       key_indices(HeadColumns, KeyColumns, Indices),
       atomic_list_concat(Indices, ', ', IndicesJoined),
       format(atom(IndicesArrayText), '[~w]', [IndicesJoined]),
       format(atom(IndicesLine), 'const ~w: readonly number[] = ~w;', [IndicesConst, IndicesArrayText]),
       ConstLines = [ProjectLine, WriteLine, ColumnsLine, IndicesLine]
    ),
    pascal_case(HeadRef, Pascal),
    format(atom(FnName), 'resolve~w_~wWrites', [Pascal, Index]),
    format(atom(SigLine), 'function ~w(seam: ISqlSeam, before: Snapshot, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {', [FnName]),
    format(atom(TriggerLine), '  const triggerRows = triggerOccurrences("~w", "~w", before.~w, arrivals);', [TriggerKind, TriggerName, TriggerName]),
    format(atom(ForkLine),
           '  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: ~w, args: bindArgs(arrival.row) }))).pipe(',
           [ProjectConst]),
    format(atom(RowsLine), '        const projectedRows = result.rows.map((row) => ~w.map((column) => row[column] as IRowValue) as IRow);', [ColumnsConst]),
    % bindArgs again, not just at the project bind above: a projected value
    % just read back through result.rows may itself be a plain JS number
    % (an INTEGER query-result column, not a TEXT one), and this second bind
    % is the one that actually writes the destination column -- the same
    % "number" -> REAL -> "N.0" hazard applies here independently of the
    % project-side fix (harmless, and still correct, against an INTEGER
    % destination column too -- PHASE C2 RULING 1, verified empirically).
    ( HeadKind == log
    -> format(atom(PushLine), '          written.push({ sql: ~w, args: bindArgs(projectedRow) });', [WriteConst]),
       MapBodyLines =
       [ '      const written: SqlStatement[] = [];',
         '      for (const result of results) {',
         RowsLine,
         '        for (const projectedRow of projectedRows) {',
         PushLine,
         '        }',
         '      }',
         '      return written;'
       ]
    ;  format(atom(IndicesConst), 'EDGE_~w_~w_KEY_INDICES', [Upper, Index]),
       format(atom(KeyLine), '          const key = JSON.stringify(~w.map((index) => projectedRow[index]));', [IndicesConst]),
       format(atom(WriteMapLine),
              '      return [...resolved.values()].map((row): SqlStatement => ({ sql: ~w, args: bindArgs(row) }));',
              [WriteConst]),
       MapBodyLines =
       [ '      const resolved = new Map<string, IRow>();',
         '      for (const result of results) {',
         RowsLine,
         '        for (const projectedRow of projectedRows) {',
         KeyLine,
         '          resolved.set(key, projectedRow);',
         '        }',
         '      }',
         WriteMapLine
       ]
    ),
    append(
        [ [ SigLine,
            TriggerLine,
            % forkJoin([]) COMPLETES WITHOUT EMITTING (verified against rxjs
            % 7.8.2, not assumed) -- a drain tick, or any tick where no
            % arrival matches this trigger, has an empty triggerRows, and
            % without this guard the WHOLE tick() chain silently completes
            % with no ITickDeltas at all for that tick (a real bug caught
            % running the emitted program against the real seam, not by
            % typecheck -- tsgo has no way to know forkJoin([]) is
            % empty-completing rather than []-emitting).
            '  if (triggerRows.length === 0) return of([]);',
            ForkLine,
            '    map((results) => {'
          ],
          MapBodyLines,
          [ '    }),',
            '  );',
            '}'
          ]
        ], FnLines).

key_indices(HeadColumns, KeyColumns, Indices) :-
    findall(Index0,
            ( member(Column, KeyColumns), nth0(Index0, HeadColumns, Column) ),
            Indices).

% ═══ level recompute ═════════════════════════════════════════════════════════
% Statements joined with the literal two-character escape sequence `\n`
% (NOT an actual newline byte in this Prolog source): embedded inside the
% backtick template literal, that text is what the JS engine itself
% interprets as a newline when the template is evaluated at runtime --
% matches Phase A's exemplar (`.join(";\n")` in real TS source, same
% escape). Keeps the emitted const a single source line.

% A program with zero level rules (every fixture whose Rules list is entirely
% edge rules, or empty outright -- e.g. an EDB-only fixture with no rules at
% all) still has run_tick_fn_lines call `recomputeLevels(seam)` unconditionally
% (that call is not itself gated on LevelStatements), so this needs a real
% zero-op function, not silent failure: `of(undefined)` is the one-void-then-
% complete shape the async-becomes-rxjs law calls for (EMPTY would complete
% without emitting, which starves the caller's `.pipe(map(() => before))` of
% a value and stalls the whole tick chain).
recompute_levels_fn_lines([], Lines) :- !,
    Lines =
    [ 'function recomputeLevels(seam: ISqlSeam): Observable<void> {',
      '  void seam;',
      '  return of(undefined);',
      '}'
    ].
recompute_levels_fn_lines(LevelStatements, Lines) :-
    LevelStatements \== [],
    % InsertSqls is a LIST (lower.pl:level_statement_group/3 -- one entry per
    % rule clause sharing this head, so a multi-clause head's rows all
    % INSERT after exactly one DELETE, never one DELETE per clause); flattens
    % to the identical [Delete, Insert] sequence as before for the common
    % single-clause case.
    findall(Sql, ( member(levelstmt(_, DeleteSql, InsertSqls, _, _), LevelStatements), ( Sql = DeleteSql ; member(Sql, InsertSqls) ) ), Sqls),
    atomic_list_concat(Sqls, ';\\n', JoinedSql),
    js_template(JoinedSql, SqlTemplate),
    format(atom(SqlLine), '  const sql = ~w;', [SqlTemplate]),
    Lines =
    [ 'function recomputeLevels(seam: ISqlSeam): Observable<void> {',
      SqlLine,
      '  return seam.runner.executeMultiple(seam.db, sql);',
      '}'
    ].

% ═══ buildDeltas ═════════════════════════════════════════════════════════════

build_deltas_fn_lines(RelPlans, EdgeStatements, Lines) :-
    maplist(diff_local_line, RelPlans, DiffLines),
    maplist(rel_entry_line, RelPlans, RelEntryLines),
    carry_pending_expr(EdgeStatements, CarryExpr),
    format(atom(CarryLine), '    carryPending: ~w,', [CarryExpr]),
    append(
        [ ['function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {'],
          DiffLines,
          ['  return {', '    rels: ['],
          RelEntryLines,
          ['    ],', CarryLine, '  };', '}']
        ], Lines).

diff_local_line(relplan(Ref, _Kind, _Columns, _Key, _ColumnTypes), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '  const ~w = multisetDiff(before.~w, after.~w);', [Name, Name, Name]).

rel_entry_line(relplan(Ref, _Kind, _Columns, _Key, _ColumnTypes), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '      { rel: "~w", add: ~w.add, del: ~w.del },', [Name, Name, Name]).

% carryPending (engine.pl q4/R2): true when a row this tick's edge rule(s)
% wrote SHOWS AS A DELTA (an equal-row rewrite is invisible to multisetDiff,
% so no separate no-op check is needed here -- the diff already absorbs it).
% Simplification, matching Phase A's exemplar finding 3: this ignores the
% general "post-write level growth with no edge write" carry source, safe
% for both target fixtures because neither has a level rule reading an
% arrival-driven rel directly without an edge rule in between. A program
% with zero edge rules (demand_laziness_effect_rows) has carryPending fixed
% at `false` -- not a per-tick computation, a structural fact about that
% program shape (no rule ever writes mid-tick). HeadRefs are DEDUPED (sort/2)
% before building conditions: PHASE C2 RULING 2 lets several edgestmt arms
% share one HeadRef (multiple rules, or multiple atoms of one unmarked
% body), and an un-deduped fold would repeat the identical `X.add.length >
% 0 || X.del.length > 0` disjunct once per arm -- harmless logically
% (idempotent OR), just noise in the emitted text.
carry_pending_expr([], 'false') :- !.
carry_pending_expr(EdgeStatements, Expr) :-
    findall(HeadRef, member(edgestmt(HeadRef, _, _, _, _, _, _), EdgeStatements), HeadRefs0),
    sort(HeadRefs0, HeadRefs),
    findall(Cond,
            ( member(HeadRef, HeadRefs),
              ref_name(HeadRef, Name),
              format(atom(Cond), '~w.add.length > 0 || ~w.del.length > 0', [Name, Name]) ),
            Conds),
    atomic_list_concat(Conds, ' || ', Expr).

% ═══ tick() + program export ════════════════════════════════════════════════

run_naive_tick_fn_lines(Name, [], Lines) :- !,
    format(atom(NameCommentLine), '  // ~w: no edge rules -- absorb arrivals, recompute levels, diff.', [Name]),
    Lines =
    [ 'function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  return readSnapshot(seam).pipe(',
      '    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),',
      '    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),',
      '    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),',
      '  );',
      NameCommentLine,
      '}'
    ].
run_naive_tick_fn_lines(Name, EdgeStatements, Lines) :-
    EdgeStatements \== [],
    edge_resolve_call_exprs(EdgeStatements, ResolveCallExprs),
    ( ResolveCallExprs = [SingleCall]
    -> format(atom(EdgeWritesExpr), '~w', [SingleCall])
    ; atomic_list_concat(ResolveCallExprs, ', ', JoinedCalls),
      format(atom(EdgeWritesExpr), 'forkJoin([~w]).pipe(map((groups) => groups.flat()))', [JoinedCalls])
    ),
    format(atom(EdgeWritesLine), '      ~w.pipe(', [EdgeWritesExpr]),
    format(atom(NameCommentLine), '  // ~w: engine.pl process_occurrences -> level_closure -> boundary_deltas.', [Name]),
    Lines =
    [ 'function runNaiveTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  return readSnapshot(seam).pipe(',
      '    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),',
      '    concatMap((before) =>',
      EdgeWritesLine,
      '        concatMap((statements) => seam.runner.batch(seam.db, statements)),',
      '        map(() => before),',
      '      ),',
      '    ),',
      '    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),',
      '    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),',
      '  );',
      NameCommentLine,
      '}'
    ].

incremental_mode_lines(IncrementalSafe, ReconcileEveryTick,
    [ SafeLine, ReconcileLine,
      'const EMITTER_MODE = process.env.SPREFA_TSV2_EMITTER_MODE === "naive" ? "naive" : "incremental";'
    ]) :-
    format(atom(SafeLine), 'const INCREMENTAL_PROGRAM_SAFE = ~w;', [IncrementalSafe]),
    format(atom(ReconcileLine), 'const RECONCILE_EVERY_TICK = ~w;',
           [ReconcileEveryTick]).

incremental_plan_export_lines(RetractionGuard,
    [ 'export const incrementalPlan: IIncrementalProgramPlan = {',
      '  safe: INCREMENTAL_PROGRAM_SAFE,',
      '  reconcileEveryTick: RECONCILE_EVERY_TICK,',
      GuardLine,
      '  relations: INCREMENTAL_RELATIONS,',
      '  edges: INCREMENTAL_EDGE_STATEMENTS,',
      '  levels: INCREMENTAL_LEVEL_STATEMENTS,',
      '};'
    ]) :-
    format(atom(GuardLine), '  retractionGuard: "~w",', [RetractionGuard]).

incremental_carry_expr([], 'false') :- !.
incremental_carry_expr(EdgeStatements, Expr) :-
    findall(HeadName,
            ( member(edgestmt(HeadRef, _, _, _, _, _, _), EdgeStatements),
              ref_name(HeadRef, HeadName) ),
            HeadNames0),
    sort(HeadNames0, HeadNames),
    findall(Quoted, (member(Name, HeadNames), js_string(Name, Quoted)), QuotedNames),
    atomic_list_concat(QuotedNames, ', ', NamesText),
    format(atom(Expr),
           '[~w].includes(delta.rel) && (delta.add.length > 0 || delta.del.length > 0)',
           [NamesText]).

run_incremental_tick_fn_lines(EdgeStatements, Lines) :-
    ( EdgeStatements == []
    -> MergeLine = '    concatMap(() => of(undefined)),',
       PostEdgeLevelLine = '    concatMap(() => of(undefined)),'
    ;  MergeLine = '    concatMap(() => IncrementalRuntime.mergeNextIntoCurrent(seam, INCREMENTAL_RELATIONS)),',
       PostEdgeLevelLine = '    concatMap(() => IncrementalRuntime.applyLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),'
    ),
    RecomputeLine = '    concatMap(() => IncrementalRuntime.recomputeLevelsAfterEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS, RECONCILE_EVERY_TICK)),',
    Lines =
    [ 'function runIncrementalTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  return IncrementalRuntime.prepareTick(seam, INCREMENTAL_RELATIONS).pipe(',
      '    concatMap(() => IncrementalRuntime.applyArrivals(seam, arrivals, INCREMENTAL_RELATIONS)),',
      '    concatMap(() => IncrementalRuntime.applyLevelsBeforeEdges(seam, INCREMENTAL_LEVEL_STATEMENTS, INCREMENTAL_RELATIONS)),',
      '    concatMap(() => IncrementalRuntime.applyEdges(seam, INCREMENTAL_EDGE_STATEMENTS, INCREMENTAL_RELATIONS)),',
      MergeLine,
      PostEdgeLevelLine,
      RecomputeLine,
      '    concatMap(() => IncrementalRuntime.readBoundary(seam, INCREMENTAL_RELATIONS)),',
      '    concatMap((rels) => IncrementalRuntime.promoteFrontiers(seam, INCREMENTAL_RELATIONS).pipe(',
      '      map((carryPending): ITickDeltas => ({ rels, carryPending })),',
      '    )),',
      '  );',
      '}',
      '',
      'function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  if (EMITTER_MODE === "naive" || !INCREMENTAL_PROGRAM_SAFE) {',
      '    return runNaiveTick(seam, arrivals);',
      '  }',
      '  return runIncrementalTick(seam, arrivals);',
      '}'
    ].

incremental_program_safe(plan(_, prog(_, Rules), _, _, _, _),
                         _EdgeStatements, _LevelStatements, Safe) :-
    rules_have_supported_level_bodies(Rules),
    Safe = true.

rules_have_supported_level_bodies([]).
rules_have_supported_level_bodies([_ | Rest]) :-
    rules_have_supported_level_bodies(Rest).

reconcile_every_tick(plan(_, prog(_, Rules), _, _, _, _), Reconcile) :-
    ( member(Rule, Rules),
      Rule = (_ <- Body),
      body_ref_uses(Body, Uses),
      member(use(_, _, neg, _), Uses)
    -> Reconcile = true
    ;  Reconcile = false
    ).

retraction_guard(plan(_, prog(_, Rules), _, _, _, _), Guard) :-
    ( member(Rule, Rules),
      Rule = (_ <- Body),
      rule_head_ref(Rule, HeadRef),
      body_ref_uses(Body, Uses),
      member(use(HeadRef, _, pos, _), Uses)
    -> Guard = 'recursive-cte-reseed'
    ;  Guard = 'plain-count-acyclic'
    ).

% Each arm's resolver call passes `before` (PHASE C2 RULING 2: a Set-kind
% trigger's occurrence detection needs the tick-start snapshot to tell a
% genuine new row from a same-tick or standing duplicate -- triggerOccurrences
% above); Index is this arm's 0-based position in the whole flattened
% EdgeStatements list, matching edge_resolver_blocks/4's own naming.
edge_resolve_call_exprs(EdgeStatements, Exprs) :-
    findall(Expr,
            ( nth0(Index, EdgeStatements, edgestmt(HeadRef, _, _, _, _, _, _)),
              edge_resolve_call_expr(HeadRef, Index, Expr) ),
            Exprs).

edge_resolve_call_expr(HeadRef, Index, Expr) :-
    pascal_case(HeadRef, Pascal),
    format(atom(Expr), 'resolve~w_~wWrites(seam, before, arrivals)', [Pascal, Index]).

program_export_lines(Name,
    [ 'export const program: IGenProgramWithBoot = {',
      NameLine,
      '  ddl,',
      '  relColumns,',
      '  arrivalTargets,',
      '  boot,',
      '  tick: runTick,',
      '};'
    ]) :-
    format(atom(NameLine), '  name: "~w",', [Name]).

% ═══ top level ═══════════════════════════════════════════════════════════════

emit_program(Name, Plan, Lowered, BootStatements, Text) :-
    Lowered = lowered(Name, Ddl, ArrivalStatements, EdgeStatements, LevelStatements, DeltaStatements, RelPlans, ArrivalTargets),
    header_lines(Name, HeaderLines),
    ( EdgeStatements == [] -> HasEdgeRules = false ; HasEdgeRules = true ),
    imports_lines(HasEdgeRules, ImportLines),
    local_types_lines(LocalTypeLines),
    bind_args_helper_lines(BindArgsHelperLines),
    ( EdgeStatements == [] -> TriggerOccurrencesHelperLines = [] ; trigger_occurrences_helper_lines(TriggerOccurrencesHelperLines) ),
    ddl_lines(Ddl, DdlLines),
    rel_columns_lines(RelPlans, RelColumnsLines),
    arrival_targets_lines(ArrivalTargets, ArrivalTargetsLines),
    boot_lines(BootStatements, BootLines),
    snapshot_type_lines(RelPlans, SnapshotTypeLines),
    read_snapshot_fn_lines(DeltaStatements, ReadSnapshotFnLines),
    arrival_statements_lines(ArrivalStatements, ArrivalStatementsLines),
    arrival_statement_fn_lines(Name, ArrivalStatementFnLines),
    incremental_relation_lines(RelPlans, ArrivalStatements, DeltaStatements, IncrementalRelationLines),
    incremental_edge_statement_lines(EdgeStatements, RelPlans, IncrementalEdgeStatementLines),
    incremental_level_statement_lines(LevelStatements, RelPlans, IncrementalLevelStatementLines),
    ( EdgeStatements == []
    -> EdgeConstLines = [], EdgeFnLines = []
    ; edge_resolver_blocks(EdgeStatements, RelPlans, EdgeConstLines, EdgeFnLines)
    ),
    recompute_levels_fn_lines(LevelStatements, RecomputeLevelsFnLines),
    build_deltas_fn_lines(RelPlans, EdgeStatements, BuildDeltasFnLines),
    run_naive_tick_fn_lines(Name, EdgeStatements, RunNaiveTickFnLines),
    incremental_program_safe(Plan, EdgeStatements, LevelStatements, IncrementalSafe),
    reconcile_every_tick(Plan, ReconcileEveryTick),
    retraction_guard(Plan, RetractionGuard),
    incremental_mode_lines(IncrementalSafe, ReconcileEveryTick,
                           IncrementalModeLines),
    run_incremental_tick_fn_lines(EdgeStatements, RunIncrementalTickFnLines),
    incremental_plan_export_lines(RetractionGuard, IncrementalPlanExportLines),
    program_export_lines(Name, ProgramExportLines),
    Sections0 =
    [ HeaderLines, ImportLines, LocalTypeLines, BindArgsHelperLines, TriggerOccurrencesHelperLines,
      DdlLines, RelColumnsLines, ArrivalTargetsLines,
      BootLines, SnapshotTypeLines, ReadSnapshotFnLines,
      ArrivalStatementsLines, ArrivalStatementFnLines,
      IncrementalRelationLines, IncrementalEdgeStatementLines, IncrementalLevelStatementLines,
      EdgeConstLines, EdgeFnLines,
      RecomputeLevelsFnLines, BuildDeltasFnLines, RunNaiveTickFnLines,
      IncrementalModeLines, RunIncrementalTickFnLines, IncrementalPlanExportLines,
      ProgramExportLines
    ],
    exclude(==([]), Sections0, Sections),
    maplist(lines_block, Sections, SectionTexts),
    atomic_list_concat(SectionTexts, '\n\n', Body),
    format(atom(Text), '~w\n', [Body]).
