% emit_ts.pl : prints a lowered/8 term as a literal TypeScript module
% conforming to IGenProgram (plans/2026-07-27-tsv2-compile-target-header.md,
% ADDENDUM). Table-driven, not hand-unrolled: every rel's mutation/delta/
% refresh statement is one row in a compile-time array or record literal,
% which is the more "generated code" shape for a compiler meant to scale
% past two or three rels (regular row shape beats N differently-named
% variables). The one genuinely dynamic-length piece is the arrivals fold
% (`arrivals.rows`, a runtime value), which is the one real `from(...).pipe(
% concatMap(...))` loop in the file; everything else is a fixed-length
% concat/toArray sequence over compile-time-known statements, matching
% "Async becomes rxjs; sync stays sync": the final envelope assembly
% (`buildTickDeltas`) is a plain synchronous `forEach` over a compile-time
% array, never further Observable machinery.
%
% SEAM NAMES: only the four the header pins (IGenProgram, ISqlSeam,
% IArrivalBatch, ITickDeltas) are imported from "../runtime/types.ts", which
% does not exist in this worktree (Phase A owns it, landing separately).
% Every OTHER supporting type (IArrivalRow, ISqlQueryResult, SqlParam,
% ITickDeltaSet, IBootStatement, ISqlStatement, IDeltaQuery) is a LOCAL
% assumption this file declares itself, flagged in a header comment as an
% assumption rather than folded into the pinned import -- real seam friction,
% not resolved unilaterally here (see the arc report).

:- module(emit_ts, [ emit_program/5 ]).

:- use_module(library(lists)).
:- use_module(library(apply)).

% ═══ small text helpers ══════════════════════════════════════════════════════

lines_block(Lines, Text) :- atomic_list_concat(Lines, '\n', Text).

indent(Level, Lines, Indented) :-
    tab_atom(Level, Tab),
    maplist(prefix_line(Tab), Lines, Indented).

prefix_line(_, '', '') :- !.
prefix_line(Tab, Line, Indented) :- format(atom(Indented), '~w~w', [Tab, Line]).

tab_atom(0, '') :- !.
tab_atom(Level, Tab) :- Level > 0, N is Level * 2, length(Spaces, N), maplist(=(' '), Spaces), atomic_list_concat(Spaces, Tab).

% Backtick template literal, defensively escaping the two characters that
% would break out of one (neither appears in any SQL this compiler emits,
% since identifiers are quote_ident'd with double quotes and text literals
% use sql_literal's single quotes, but the escape costs nothing).
js_template(SqlText, JsLiteral) :-
    atom_string(SqlText, SqlString0),
    re_replace("`"/g, "\\`", SqlString0, SqlString1),
    re_replace("\\$\\{"/g, "\\${", SqlString1, SqlString2),
    format(atom(JsLiteral), '`~w`', [SqlString2]).

js_string(Atom, JsLiteral) :- format(atom(JsLiteral), '"~w"', [Atom]).

upper_snake(Name/_Arity, Upper) :- upcase_atom(Name, Upper).

ref_name(Name/_Arity, Name).

% ═══ header comment ══════════════════════════════════════════════════════════

header_lines(Name, Lines) :-
    format(atom(TitleLine), '// GENERATED by v6/prolog/compile (tsv2 Phase B). Do not hand-edit; recompile', []),
    format(atom(FromLine), '// from v6/prolog/conformance/fixtures/scopes.pl via compile.pl. Program:', []),
    format(atom(NameLine), '// ~w. Compiles the reference engine\'s occurrence / keyed-replace /', [Name]),
    Lines =
    [ TitleLine, FromLine, NameLine,
      '// boundary-diff semantics (engine.pl) to SQLite, not lower/lowerSql.ts\'s.',
      '//',
      '// ASSUMED seam shapes beyond the four the header pins (ISqlSeam,',
      '// IArrivalBatch, ITickDeltas, IGenProgram, imported below from',
      '// "../runtime/types.ts", which does not exist in this worktree yet):',
      '// IArrivalRow { rel: string; sign: "add" | "del"; values: readonly string[] }',
      '// on IArrivalBatch.rows, and ISqlQueryResult { rows: readonly',
      '// Record<string, SqlParam>[]; rowsAffected: number } as ISqlSeam.run\'s',
      '// resolved value. If Phase A\'s real runtime/types.ts shapes these',
      '// differently, only this file\'s local type declarations and tick() body',
      '// need to change, not the exported program\'s IGenProgram surface.',
      '//',
      '// IGenProgram has no slot for boot-time work (seeding Initial rows, then',
      '// priming the boundary-diff snapshot tables so tick 1\'s delta does not',
      '// show the seed as a "+" addition -- engine.pl:run_program does this',
      '// before state(1, ...) exists, a non-tick step). `boot` is an extra field',
      '// added beyond the five pinned names ("extend by adding fields, never',
      '// renaming"); who calls it and when is unresolved -- flagged, not decided.'
    ].

% ═══ imports ═════════════════════════════════════════════════════════════════

imports_lines(
    [ 'import type { Observable } from "rxjs";',
      'import { concat, from } from "rxjs";',
      'import { concatMap, map, toArray } from "rxjs";',
      'import type { IGenProgram, ISqlSeam, IArrivalBatch, ITickDeltas } from "../runtime/types.ts";'
    ]).

% ═══ local supporting types ══════════════════════════════════════════════════

local_types_lines(
    [ 'type SqlParam = string | number;',
      '',
      'interface ISqlQueryResult {',
      '  rows: readonly Record<string, SqlParam>[];',
      '  rowsAffected: number;',
      '}',
      '',
      'interface IArrivalRow {',
      '  rel: string;',
      '  sign: "add" | "del";',
      '  values: readonly string[];',
      '}',
      '',
      'interface ITickDeltaSet {',
      '  add: readonly Record<string, SqlParam>[];',
      '  del: readonly Record<string, SqlParam>[];',
      '}',
      '',
      'interface IBootStatement {',
      '  sql: string;',
      '  params: readonly SqlParam[];',
      '}',
      '',
      'interface ISqlStatement {',
      '  sql: string;',
      '  params: readonly SqlParam[];',
      '}',
      '',
      'interface IArrivalTemplate {',
      '  kind: "log" | "set";',
      '  addSql: string;',
      '  delSql: string | null;',
      '}',
      '',
      'interface IDeltaQuery {',
      '  rel: string;',
      '  sign: "add" | "del";',
      '  sql: string;',
      '  params: readonly SqlParam[];',
      '}',
      '',
      'interface IGenProgramWithBoot extends IGenProgram {',
      '  boot: readonly IBootStatement[];',
      '}'
    ]).

% ═══ ddl ═════════════════════════════════════════════════════════════════════

ddl_lines(Ddl, Lines) :-
    maplist(ddl_entry_line, Ddl, EntryLines),
    append([ ['const ddl: readonly string[] = ['], EntryLines, ['];'] ], Lines).

ddl_entry_line(Sql, Line) :- js_template(Sql, Template), format(atom(Line), '  ~w,', [Template]).

% ═══ relColumns / arrivalTargets ═════════════════════════════════════════════

rel_columns_lines(RelPlans, Lines) :-
    maplist(rel_columns_entry_line, RelPlans, EntryLines),
    append([ ['const relColumns: Record<string, readonly string[]> = {'], EntryLines, ['};'] ], Lines).

rel_columns_entry_line(relplan(Ref, _Kind, Columns, _Key), Line) :-
    ref_name(Ref, Name),
    maplist(js_string, Columns, QuotedColumns),
    atomic_list_concat(QuotedColumns, ', ', ColumnsSql),
    format(atom(Line), '  ~w: [~w],', [Name, ColumnsSql]).

arrival_targets_lines(ArrivalTargets, Lines) :-
    maplist(ref_name, ArrivalTargets, Names),
    maplist(js_string, Names, Quoted),
    atomic_list_concat(Quoted, ', ', Sql),
    format(atom(Line), 'const arrivalTargets: readonly string[] = [~w];', [Sql]),
    Lines = [Line].

% ═══ boot ════════════════════════════════════════════════════════════════════

boot_lines(BootStatements, Lines) :-
    maplist(boot_entry_line, BootStatements, EntryLines),
    append([ ['const boot: readonly IBootStatement[] = ['], EntryLines, ['];'] ], Lines).

boot_entry_line(bootstmt(Sql, Params), Line) :-
    js_template(Sql, Template),
    params_array_text(Params, ParamsText),
    format(atom(Line), '  { sql: ~w, params: ~w },', [Template, ParamsText]).

params_array_text(Params, Text) :-
    maplist(param_text, Params, ParamTexts),
    atomic_list_concat(ParamTexts, ', ', Joined),
    format(atom(Text), '[~w]', [Joined]).

param_text(Param, Text) :- number(Param), !, format(atom(Text), '~w', [Param]).
param_text(Param, Text) :- js_string(Param, Text).

% ═══ arrival statement templates ═════════════════════════════════════════════

arrival_statements_lines(ArrivalStatements, Lines) :-
    maplist(arrival_statement_entry_line, ArrivalStatements, EntryLines),
    append(
        [ ['const ARRIVAL_STATEMENTS: Record<string, IArrivalTemplate> = {'],
          EntryLines,
          ['};']
        ], Lines).

arrival_statement_entry_line(arrivalstmt(Ref, log, AddSql, none), Line) :- !,
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    format(atom(Line), '  ~w: { kind: "log", addSql: ~w, delSql: null },', [Name, AddTemplate]).
arrival_statement_entry_line(arrivalstmt(Ref, set, AddSql, DelSql), Line) :-
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    js_template(DelSql, DelTemplate),
    format(atom(Line), '  ~w: { kind: "set", addSql: ~w, delSql: ~w },', [Name, AddTemplate, DelTemplate]).

apply_arrival_row_fn_lines(Name, Lines) :-
    format(atom(UndeclaredError),
           '    throw new Error(`~w: tick received an arrival for undeclared rel \'${row.rel}\'`);', [Name]),
    format(atom(RetractLogError),
           '      throw new Error(`~w: retract from log rel \'${row.rel}\' (engine.pl retract_from_log)`);', [Name]),
    format(atom(NoDeleteError),
           '      throw new Error(`~w: rel \'${row.rel}\' has no delete statement`);', [Name]),
    Lines =
    [ 'function applyArrivalRow(seam: ISqlSeam, tick: number, seq: number, row: IArrivalRow): Observable<ISqlQueryResult> {',
      '  const statement = ARRIVAL_STATEMENTS[row.rel];',
      '  if (statement === undefined) {',
      UndeclaredError,
      '  }',
      '  if (row.sign === "del") {',
      '    if (statement.kind === "log") {',
      RetractLogError,
      '    }',
      '    if (statement.delSql === null) {',
      NoDeleteError,
      '    }',
      '    return seam.run(statement.delSql, row.values);',
      '  }',
      '  const params = statement.kind === "log" ? [tick, seq, ...row.values] : row.values;',
      '  return seam.run(statement.addSql, params);',
      '}'
    ].

% ═══ edge / level SQL consts + mutationStatements ════════════════════════════

edge_const_lines(EdgeStatements, ConstLines, EntryLines) :-
    maplist(edge_const_pair, EdgeStatements, ConstLinePairs, EntryLinePairs),
    append(ConstLinePairs, ConstLines),
    append(EntryLinePairs, EntryLines).

edge_const_pair(edgestmt(Ref, DeleteSql, InsertSql), [DeleteLine, InsertLine], [DeleteEntry, InsertEntry]) :-
    upper_snake(Ref, Upper),
    format(atom(DeleteConst), 'EDGE_~w_DELETE_SQL', [Upper]),
    format(atom(InsertConst), 'EDGE_~w_INSERT_SQL', [Upper]),
    js_template(DeleteSql, DeleteTemplate),
    js_template(InsertSql, InsertTemplate),
    format(atom(DeleteLine), 'const ~w = ~w;', [DeleteConst, DeleteTemplate]),
    format(atom(InsertLine), 'const ~w = ~w;', [InsertConst, InsertTemplate]),
    format(atom(DeleteEntry), '  { sql: ~w, params: [tick] },', [DeleteConst]),
    format(atom(InsertEntry), '  { sql: ~w, params: [tick] },', [InsertConst]).

level_const_lines(LevelStatements, ConstLines, EntryLines) :-
    maplist(level_const_pair, LevelStatements, ConstLinePairs, EntryLinePairs),
    append(ConstLinePairs, ConstLines),
    append(EntryLinePairs, EntryLines).

level_const_pair(levelstmt(Ref, DeleteSql, InsertSql), [DeleteLine, InsertLine], [DeleteEntry, InsertEntry]) :-
    upper_snake(Ref, Upper),
    format(atom(DeleteConst), 'LEVEL_~w_DELETE_SQL', [Upper]),
    format(atom(InsertConst), 'LEVEL_~w_INSERT_SQL', [Upper]),
    js_template(DeleteSql, DeleteTemplate),
    js_template(InsertSql, InsertTemplate),
    format(atom(DeleteLine), 'const ~w = ~w;', [DeleteConst, DeleteTemplate]),
    format(atom(InsertLine), 'const ~w = ~w;', [InsertConst, InsertTemplate]),
    format(atom(DeleteEntry), '  { sql: ~w, params: [] },', [DeleteConst]),
    format(atom(InsertEntry), '  { sql: ~w, params: [] },', [InsertConst]).

mutation_statements_fn_lines(EdgeEntryLines, LevelEntryLines, Lines) :-
    append(EdgeEntryLines, LevelEntryLines, AllEntryLines),
    append(
        [ ['function mutationStatements(tick: number): readonly ISqlStatement[] {', '  return ['],
          AllEntryLines,
          ['  ];', '}']
        ], Lines).

% ═══ delta SQL consts + deltaQueries + refreshSnapshotStatements ════════════

delta_const_lines(DeltaStatements, ConstLines, QueryEntryLines, RefreshEntryLines) :-
    maplist(delta_const_group, DeltaStatements, ConstLinePairs, QueryEntryLinePairs, RefreshEntryLinePairs),
    append(ConstLinePairs, ConstLines),
    append(QueryEntryLinePairs, QueryEntryLines),
    append(RefreshEntryLinePairs, RefreshEntryLines).

delta_const_group(deltastmt(Ref, log, AddsSql, none, []), ConstLines, QueryEntries, []) :- !,
    upper_snake(Ref, Upper),
    ref_name(Ref, Name),
    format(atom(AddsConst), 'DELTA_~w_ADDS_SQL', [Upper]),
    js_template(AddsSql, AddsTemplate),
    format(atom(AddsLine), 'const ~w = ~w;', [AddsConst, AddsTemplate]),
    ConstLines = [AddsLine],
    format(atom(QueryEntry), '  { rel: "~w", sign: "add", sql: ~w, params: [tick] },', [Name, AddsConst]),
    QueryEntries = [QueryEntry].
delta_const_group(deltastmt(Ref, set, AddsSql, DelsSql, [RefreshDeleteSql, RefreshInsertSql]), ConstLines, QueryEntries, RefreshEntries) :-
    upper_snake(Ref, Upper),
    ref_name(Ref, Name),
    format(atom(AddsConst), 'DELTA_~w_ADDS_SQL', [Upper]),
    format(atom(DelsConst), 'DELTA_~w_DELS_SQL', [Upper]),
    js_template(AddsSql, AddsTemplate),
    js_template(DelsSql, DelsTemplate),
    format(atom(AddsLine), 'const ~w = ~w;', [AddsConst, AddsTemplate]),
    format(atom(DelsLine), 'const ~w = ~w;', [DelsConst, DelsTemplate]),
    ConstLines = [AddsLine, DelsLine],
    format(atom(AddEntry), '  { rel: "~w", sign: "add", sql: ~w, params: [] },', [Name, AddsConst]),
    format(atom(DelEntry), '  { rel: "~w", sign: "del", sql: ~w, params: [] },', [Name, DelsConst]),
    QueryEntries = [AddEntry, DelEntry],
    js_template(RefreshDeleteSql, RefreshDeleteTemplate),
    js_template(RefreshInsertSql, RefreshInsertTemplate),
    format(atom(RefreshDeleteEntry), '  { sql: ~w, params: [] },', [RefreshDeleteTemplate]),
    format(atom(RefreshInsertEntry), '  { sql: ~w, params: [] },', [RefreshInsertTemplate]),
    RefreshEntries = [RefreshDeleteEntry, RefreshInsertEntry].

delta_queries_fn_lines(QueryEntryLines, Lines) :-
    append(
        [ ['function deltaQueries(tick: number): readonly IDeltaQuery[] {', '  return ['],
          QueryEntryLines,
          ['  ];', '}']
        ], Lines).

refresh_snapshot_fn_lines(RefreshEntryLines, Lines) :-
    append(
        [ ['function refreshSnapshotStatements(): readonly ISqlStatement[] {', '  return ['],
          RefreshEntryLines,
          ['  ];', '}']
        ], Lines).

% ═══ runAllStatements / buildTickDeltas / runTick ═══════════════════════════

run_all_fn_lines(
    [ 'function runAllStatements(seam: ISqlSeam, statements: readonly ISqlStatement[]): Observable<readonly ISqlQueryResult[]> {',
      '  return concat(...statements.map((statement) => seam.run(statement.sql, statement.params))).pipe(toArray());',
      '}'
    ]).

build_tick_deltas_fn_lines(RelPlans, Lines) :-
    maplist(rel_deltas_init_line, RelPlans, InitLines),
    append(
        [ ['function buildTickDeltas(tick: number, queries: readonly IDeltaQuery[], results: readonly ISqlQueryResult[]): ITickDeltas {',
           '  const deltas: Record<string, ITickDeltaSet> = {'],
          InitLines,
          [ '  };',
            '  queries.forEach((query, index) => {',
            '    const rows = results[index]!.rows;',
            '    if (query.sign === "add") deltas[query.rel]!.add = rows;',
            '    else deltas[query.rel]!.del = rows;',
            '  });',
            '  return { tick, deltas };',
            '}'
          ]
        ], Lines).

rel_deltas_init_line(relplan(Ref, _Kind, _Columns, _Key), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '    ~w: { add: [], del: [] },', [Name]).

run_tick_fn_lines(Name,
    [ 'function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  const tick = arrivals.tick;',
      '  return from(arrivals.rows).pipe(',
      '    concatMap((row, index) => applyArrivalRow(seam, tick, index + 1, row)),',
      '    toArray(),',
      '    concatMap(() => runAllStatements(seam, mutationStatements(tick))),',
      '    concatMap(() => {',
      '      const queries = deltaQueries(tick);',
      '      return runAllStatements(seam, queries).pipe(map((results) => buildTickDeltas(tick, queries, results)));',
      '    }),',
      '    concatMap((deltas) => runAllStatements(seam, refreshSnapshotStatements()).pipe(map(() => deltas))),',
      '  );',
      NameCommentLine,
      '}'
    ]) :-
    format(atom(NameCommentLine), '  // ~w: engine.pl process_occurrences -> level_closure -> boundary_deltas, one tick.', [Name]).

program_export_lines(Name,
    [ 'export const program: IGenProgramWithBoot = {',
      NameLine,
      '  ddl,',
      '  relColumns,',
      '  arrivalTargets,',
      '  boot,',
      '  tick: runTick,',
      '};'
    ]) :-
    format(atom(NameLine), '  name: "~w",', [Name]).

% ═══ top level ═══════════════════════════════════════════════════════════════

emit_program(Name, _Plan, Lowered, BootStatements, Text) :-
    Lowered = lowered(Name, Ddl, ArrivalStatements, EdgeStatements, LevelStatements, DeltaStatements, RelPlans, ArrivalTargets),
    header_lines(Name, HeaderLines),
    imports_lines(ImportLines),
    local_types_lines(LocalTypeLines),
    ddl_lines(Ddl, DdlLines),
    rel_columns_lines(RelPlans, RelColumnsLines),
    arrival_targets_lines(ArrivalTargets, ArrivalTargetsLines),
    boot_lines(BootStatements, BootLines),
    arrival_statements_lines(ArrivalStatements, ArrivalStatementsLines),
    apply_arrival_row_fn_lines(Name, ApplyArrivalRowLines),
    edge_const_lines(EdgeStatements, EdgeConstLines, EdgeEntryLines),
    level_const_lines(LevelStatements, LevelConstLines, LevelEntryLines),
    mutation_statements_fn_lines(EdgeEntryLines, LevelEntryLines, MutationFnLines),
    delta_const_lines(DeltaStatements, DeltaConstLines, DeltaQueryEntryLines, RefreshEntryLines),
    delta_queries_fn_lines(DeltaQueryEntryLines, DeltaQueriesFnLines),
    refresh_snapshot_fn_lines(RefreshEntryLines, RefreshFnLines),
    run_all_fn_lines(RunAllFnLines),
    build_tick_deltas_fn_lines(RelPlans, BuildTickDeltasFnLines),
    run_tick_fn_lines(Name, RunTickFnLines),
    program_export_lines(Name, ProgramExportLines),
    Sections =
    [ HeaderLines, ImportLines, LocalTypeLines, DdlLines, RelColumnsLines, ArrivalTargetsLines,
      BootLines, ArrivalStatementsLines, ApplyArrivalRowLines,
      EdgeConstLines, LevelConstLines, MutationFnLines,
      DeltaConstLines, DeltaQueriesFnLines, RefreshFnLines,
      RunAllFnLines, BuildTickDeltasFnLines, RunTickFnLines, ProgramExportLines
    ],
    maplist(lines_block, Sections, SectionTexts),
    atomic_list_concat(SectionTexts, '\n\n', Body),
    format(atom(Text), '~w\n', [Body]).
