% emit_ts.pl : prints a lowered/8 term as a literal TypeScript module
% conforming to IGenProgram (plans/2026-07-27-tsv2-compile-target-header.md,
% ADDENDUM). ROUND 2 (reconciliation): renders against the REAL
% v6/tsv2/runtime/types.ts (merged, no longer an assumption) and reuses the
% REAL runtime helpers per the reuse law -- `multisetDiff` (runtime/diff.ts)
% for before/after boundary deltas, `selectRows` (runtime/rows.ts) for
% shaping a SELECT's result into `IRow[]`. Matches Phase A's hand-carved
% exemplar (v6/tsv2/gen/*.ts) architecture: read every rel's rows before a
% tick's writes and again after, diff with multisetDiff; edge-rule keyed
% writes are resolved in JS from the raw `arrivals` array (a Map keyed by
% the head row's key-column values, natural last-write-wins via `.set()`),
% never via a SQL self-join on a tick number the seam does not provide.
%
% Table-driven, not hand-unrolled: every rel's snapshot read / arrival
% statement / delta entry is one row in a compile-time array or record
% literal, the more "generated code" shape for a compiler meant to scale
% past two or three rels. The one genuinely dynamic-length pieces are
% `arrivals` itself (a runtime value: `.map()`/`.filter()` over it is plain
% array code, "sync stays sync") and the edge-write resolution's `forkJoin`
% over one query per matching arrival row (a real sequential IO fan-out,
% legitimately rx-shaped).
%
% SEAM NAMES: IGenProgram, ISqlSeam, IArrivalBatch, IArrivalRow, IRow,
% IRowValue, ITickDeltas, SqlStatement all imported from
% "../runtime/types.ts" (real file, merged). `IBootStatement` is a LOCAL
% type (the header's IGenProgram has no boot slot; "extend by adding
% fields, never renaming" -- v6/tsv2/scripts/run-emitted.ts confirms who
% runs it and when: after DDL, before the tick fold).

:- module(emit_ts, [ emit_program/5 ]).

:- use_module(library(lists)).
:- use_module(library(apply)).

% ═══ small text helpers ══════════════════════════════════════════════════════

lines_block(Lines, Text) :- atomic_list_concat(Lines, '\n', Text).

js_template(SqlText, JsLiteral) :-
    atom_string(SqlText, SqlString0),
    re_replace("`"/g, "\\`", SqlString0, SqlString1),
    re_replace("\\$\\{"/g, "\\${", SqlString1, SqlString2),
    format(atom(JsLiteral), '`~w`', [SqlString2]).

js_string(Atom, JsLiteral) :- format(atom(JsLiteral), '"~w"', [Atom]).

ref_name(Name/_Arity, Name).

upper_snake(Name/_Arity, Upper) :- upcase_atom(Name, Upper).

% snake_case -> PascalCase, for JS function/type names built by combining a
% rel name with a fixed prefix/suffix (e.g. "resolve" + "OpenScope" +
% "Writes") -- SCREAMING_SNAKE (upper_snake/2) is for SQL CONSTANT names,
% where it is idiomatic; mixing it into a camelCase function name
% (`resolveOPEN_SCOPEWrites`) is not.
pascal_case(Name/_Arity, Pascal) :- !, pascal_case(Name, Pascal).
pascal_case(Name, Pascal) :-
    atomic_list_concat(Parts, '_', Name),
    maplist(capitalize_atom, Parts, CapitalizedParts),
    atomic_list_concat(CapitalizedParts, Pascal).

capitalize_atom(Atom, Capitalized) :-
    atom_codes(Atom, [First | Rest]),
    code_type(UpperFirst, to_upper(First)),
    atom_codes(Capitalized, [UpperFirst | Rest]).

param_text(Param, Text) :- number(Param), !, format(atom(Text), '~w', [Param]).
param_text(Param, Text) :- js_string(Param, Text).

params_array_text(Params, Text) :-
    maplist(param_text, Params, ParamTexts),
    atomic_list_concat(ParamTexts, ', ', Joined),
    format(atom(Text), '[~w]', [Joined]).

quoted_string_array_text(Atoms, Text) :-
    maplist(js_string, Atoms, Quoted),
    atomic_list_concat(Quoted, ', ', Joined),
    format(atom(Text), '[~w]', [Joined]).

% Flattens a list of line-groups into one line list, one blank line between
% groups (never trailing).
flatten_with_blank_separators([], []).
flatten_with_blank_separators([Group], Group) :- !.
flatten_with_blank_separators([Group | Rest], Lines) :-
    flatten_with_blank_separators(Rest, RestLines),
    append(Group, [''], WithBlank),
    append(WithBlank, RestLines, Lines).

% ═══ header comment ══════════════════════════════════════════════════════════

header_lines(Name, Lines) :-
    format(atom(TitleLine), '// GENERATED by v6/prolog/compile (tsv2 Phase B, round 2). Do not', []),
    format(atom(NameLine), '// hand-edit; recompile. Program: ~w.', [Name]),
    Lines =
    [ TitleLine, NameLine,
      '// Compiles the reference engine\'s occurrence / keyed-replace / boundary-diff',
      '// semantics (engine.pl) to SQLite + the real v6/tsv2 runtime seam, not',
      '// lower/lowerSql.ts\'s.',
      '//',
      '// Strategy matches Phase A\'s hand-carved exemplar (gen/*.ts): read every',
      '// rel\'s rows before a tick\'s writes and again after, diff with the',
      '// runtime\'s multisetDiff (reused, never reimplemented -- one algorithm',
      '// covers Set/level rels via plain set diff and Log rels via occurrence-count',
      '// diff, since engine.pl r7\'s "one +Row per new stamp" for an append-only',
      '// Log rel is exactly "count in next minus count in prev"). Edge-rule keyed',
      '// writes are resolved in JS directly from the `arrivals` array (no tick',
      '// number reaches tick() in the real seam -- the runtime owns tick',
      '// numbering, ../runtime/tickLoop.ts -- so "this tick\'s fresh trigger rows"',
      '// has no SQL-side answer; they ARE the arrivals argument already).',
      '//',
      '// IGenProgram has no slot for boot-time work (seeding Initial rows before',
      '// tick 1). `boot` is an extra field added beyond the five pinned names',
      '// ("extend by adding fields, never renaming"); v6/tsv2/scripts/',
      '// run-emitted.ts (the reconciliation runner) runs it after DDL and before',
      '// the tick fold.'
    ].

% ═══ imports ═════════════════════════════════════════════════════════════════

imports_lines(_HasEdgeRules,
    [ 'import { concatMap, forkJoin, map, of, type Observable } from "rxjs";',
      '',
      'import { multisetDiff } from "../runtime/diff.ts";',
      'import { selectRows } from "../runtime/rows.ts";',
      'import type {',
      '  IArrivalBatch,',
      '  IArrivalRow,',
      '  IGenProgram,',
      '  IRow,',
      '  IRowValue,',
      '  ISqlSeam,',
      '  ITickDeltas,',
      '  SqlStatement,',
      '} from "../runtime/types.ts";'
    ]).
    % `of` covers two zero-op shapes, not just the edge-rule forkJoin([])
    % guard it was originally added for: an edge-free tick still needs it for
    % edge_resolver_block/3's `of([])` when EdgeStatements is nonempty, AND
    % recompute_levels_fn_lines/2's no-level-rules fallback below needs
    % `of(undefined)`. Always importing it is simpler than tracking two
    % independent conditions, and tsconfig.json carries no
    % noUnusedLocals/noUnusedParameters flag, so an unused import is not a
    % typecheck error on the (rare) program shape that needs neither.

% ═══ local supporting types ══════════════════════════════════════════════════

local_types_lines(
    [ 'interface IBootStatement {',
      '  sql: string;',
      '  params: readonly (string | number)[];',
      '}',
      '',
      'type IGenProgramWithBoot = IGenProgram & { readonly boot: readonly IBootStatement[] };'
    ]).

% ═══ integer bind helper (phase C sweep finding) ═══════════════════════════
% @libsql/client binds a JS `number` parameter as SQLite REAL, not INTEGER --
% verified empirically (a bound `1` lands as the TEXT value "1.0" in a
% TEXT-affinity column, `1n` lands as "1"), a driver behavior, not a bug in
% any SQL text this compiler emits. Every column here is declared TEXT
% (lower.pl:column_def/2), so an integer-valued arrival or edge-projected
% value must cross the driver seam as a bigint to keep its digit-for-digit
% text form; a genuine fractional number (none in this compiler's corpus
% today) passes through unchanged. Used everywhere a raw IRow (an arrival's
% own row, or an edge projection's numbered-placeholder bind) becomes
% SqlStatement args.

% The return type is NOT `readonly` -- @libsql/client's own `InArgs` is
% `InValue[]`, a mutable array type, so a `readonly` array here would fail
% typecheck at every call site despite being correct at runtime (`.map()`
% already returns a fresh mutable array; the annotation was simply too
% narrow).
bind_args_helper_lines(
    [ 'function bindArgs(values: readonly IRowValue[]): (string | number | bigint)[] {',
      '  return values.map((value) => (typeof value === "number" && Number.isInteger(value) ? BigInt(value) : value));',
      '}'
    ]).

% ═══ ddl ═════════════════════════════════════════════════════════════════════

ddl_lines(Ddl, Lines) :-
    maplist(ddl_entry_line, Ddl, EntryLines),
    append([ ['const ddl: readonly string[] = ['], EntryLines, ['];'] ], Lines).

ddl_entry_line(Sql, Line) :- js_template(Sql, Template), format(atom(Line), '  ~w,', [Template]).

% ═══ relColumns / arrivalTargets ═════════════════════════════════════════════

rel_columns_lines(RelPlans, Lines) :-
    maplist(rel_columns_entry_line, RelPlans, EntryLines),
    append([ ['const relColumns: Record<string, readonly string[]> = {'], EntryLines, ['};'] ], Lines).

rel_columns_entry_line(relplan(Ref, _Kind, Columns, _Key), Line) :-
    ref_name(Ref, Name),
    quoted_string_array_text(Columns, ColumnsSql),
    format(atom(Line), '  ~w: ~w,', [Name, ColumnsSql]).

arrival_targets_lines(ArrivalTargets, Lines) :-
    maplist(ref_name, ArrivalTargets, Names),
    quoted_string_array_text(Names, Sql),
    format(atom(Line), 'const arrivalTargets: readonly string[] = ~w;', [Sql]),
    Lines = [Line].

% ═══ boot ════════════════════════════════════════════════════════════════════

boot_lines(BootStatements, Lines) :-
    maplist(boot_entry_line, BootStatements, EntryLines),
    append([ ['const boot: readonly IBootStatement[] = ['], EntryLines, ['];'] ], Lines).

boot_entry_line(bootstmt(Sql, Params), Line) :-
    js_template(Sql, Template),
    params_array_text(Params, ParamsText),
    format(atom(Line), '  { sql: ~w, params: ~w },', [Template, ParamsText]).

% ═══ snapshot type + reader (forkJoin over selectRows, one entry per rel) ════

snapshot_type_lines(RelPlans, Lines) :-
    maplist(snapshot_field_line, RelPlans, FieldLines),
    append([ ['type Snapshot = {'], FieldLines, ['};'] ], Lines).

snapshot_field_line(relplan(Ref, _Kind, _Columns, _Key), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '  readonly ~w: readonly IRow[];', [Name]).

% forkJoin({}) (zero keys) completes WITHOUT emitting, same hazard the
% edge-resolver's forkJoin([]) guard already documents (verified against
% rxjs 7.8.2, not assumed) -- a program with zero declared rels (Decls and
% Rules both empty; every phase-C fixture found so far avoids this via
% analyze.pl:declared_refs/2, but nothing upstream forbids it structurally)
% would otherwise stall runTick's very first concatMap forever. `of({})` is
% the one-value-then-complete fallback, matching recompute_levels_fn_lines/2's
% [] case just below.
read_snapshot_fn_lines([], Lines) :- !,
    Lines =
    [ 'function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {',
      '  void seam;',
      '  return of({} as Snapshot);',
      '}'
    ].
read_snapshot_fn_lines(DeltaStatements, Lines) :-
    DeltaStatements \== [],
    maplist(snapshot_read_entry_line, DeltaStatements, EntryLines),
    append(
        [ ['function readSnapshot(seam: ISqlSeam): Observable<Snapshot> {', '  return forkJoin({'],
          EntryLines,
          ['  });', '}']
        ], Lines).

snapshot_read_entry_line(deltastmt(Ref, SelectSql), Line) :-
    ref_name(Ref, Name),
    js_template(SelectSql, Template),
    format(atom(Line), '    ~w: selectRows(seam, ~w, relColumns.~w!),', [Name, Template, Name]).

% ═══ arrivals ════════════════════════════════════════════════════════════════

arrival_statements_lines(ArrivalStatements, Lines) :-
    maplist(arrival_statement_entry_line, ArrivalStatements, EntryLines),
    append(
        [ ['const ARRIVAL_STATEMENTS: Record<string, { kind: "log" | "set"; addSql: string; delSql: string | null }> = {'],
          EntryLines,
          ['};']
        ], Lines).

arrival_statement_entry_line(arrivalstmt(Ref, log, AddSql, none), Line) :- !,
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    format(atom(Line), '  ~w: { kind: "log", addSql: ~w, delSql: null },', [Name, AddTemplate]).
arrival_statement_entry_line(arrivalstmt(Ref, set, AddSql, DelSql), Line) :-
    ref_name(Ref, Name),
    js_template(AddSql, AddTemplate),
    js_template(DelSql, DelTemplate),
    format(atom(Line), '  ~w: { kind: "set", addSql: ~w, delSql: ~w },', [Name, AddTemplate, DelTemplate]).

arrival_statement_fn_lines(Name, Lines) :-
    format(atom(UndeclaredError), '    throw new Error(`~w: tick received an arrival for undeclared rel \'${arrival.rel}\'`);', [Name]),
    format(atom(RetractLogError), '      throw new Error(`~w: retract from log rel \'${arrival.rel}\' (engine.pl retract_from_log)`);', [Name]),
    format(atom(NoDeleteError), '      throw new Error(`~w: rel \'${arrival.rel}\' has no delete statement`);', [Name]),
    Lines =
    [ 'function arrivalStatement(arrival: IArrivalRow): SqlStatement {',
      '  const template = ARRIVAL_STATEMENTS[arrival.rel];',
      '  if (template === undefined) {',
      UndeclaredError,
      '  }',
      '  if (arrival.sign === "del") {',
      '    if (template.kind === "log") {',
      RetractLogError,
      '    }',
      '    if (template.delSql === null) {',
      NoDeleteError,
      '    }',
      '    return { sql: template.delSql, args: bindArgs(arrival.row) };',
      '  }',
      '  return { sql: template.addSql, args: bindArgs(arrival.row) };',
      '}',
      '',
      'function applyArrivals(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<unknown> {',
      '  const statements: SqlStatement[] = arrivals.map(arrivalStatement);',
      '  return seam.runner.batch(seam.db, statements);',
      '}'
    ].

% ═══ edge rule resolution (one resolver function per edge rule) ═════════════
% ProjectSql (from lower.pl) is already aliased AS HeadColumns
% (lower.pl:edge_statement/3 passes HeadColumns, not `none`, to
% head_select_list/4 for exactly this reason), so the resolver reads
% `result.rows[0][columnName]` the same way runtime/rows.ts's selectRows
% does -- no string surgery on the SQL text happens in this file.

edge_resolver_blocks(EdgeStatements, ConstLines, FnLines) :-
    maplist(edge_resolver_block, EdgeStatements, ConstLineGroups, FnLineGroups),
    flatten_with_blank_separators(ConstLineGroups, ConstLines),
    flatten_with_blank_separators(FnLineGroups, FnLines).

edge_resolver_block(edgestmt(HeadRef, TriggerRef, HeadColumns, KeyColumns, ProjectSql, UpsertSql), ConstLines, FnLines) :-
    ref_name(TriggerRef, TriggerName),
    upper_snake(HeadRef, Upper),
    format(atom(ProjectConst), 'EDGE_~w_PROJECT_SQL', [Upper]),
    format(atom(UpsertConst), 'EDGE_~w_UPSERT_SQL', [Upper]),
    format(atom(ColumnsConst), 'EDGE_~w_HEAD_COLUMNS', [Upper]),
    format(atom(IndicesConst), 'EDGE_~w_KEY_INDICES', [Upper]),
    js_template(ProjectSql, ProjectTemplate),
    js_template(UpsertSql, UpsertTemplate),
    quoted_string_array_text(HeadColumns, ColumnsArrayText),
    key_indices(HeadColumns, KeyColumns, Indices),
    atomic_list_concat(Indices, ', ', IndicesJoined),
    format(atom(IndicesArrayText), '[~w]', [IndicesJoined]),
    format(atom(ProjectLine), 'const ~w = ~w;', [ProjectConst, ProjectTemplate]),
    format(atom(UpsertLine), 'const ~w = ~w;', [UpsertConst, UpsertTemplate]),
    format(atom(ColumnsLine), 'const ~w: readonly string[] = ~w;', [ColumnsConst, ColumnsArrayText]),
    format(atom(IndicesLine), 'const ~w: readonly number[] = ~w;', [IndicesConst, IndicesArrayText]),
    ConstLines = [ProjectLine, UpsertLine, ColumnsLine, IndicesLine],
    pascal_case(HeadRef, Pascal),
    format(atom(FnName), 'resolve~wWrites', [Pascal]),
    format(atom(SigLine), 'function ~w(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<readonly SqlStatement[]> {', [FnName]),
    format(atom(FilterLine), '  const triggerRows = arrivals.filter((arrival) => arrival.rel === "~w" && arrival.sign === "add");', [TriggerName]),
    format(atom(ForkLine),
           '  return forkJoin(triggerRows.map((arrival) => seam.runner.execute(seam.db, { sql: ~w, args: bindArgs(arrival.row) }))).pipe(',
           [ProjectConst]),
    format(atom(RowLine), '        const projectedRow = ~w.map((column) => result.rows[0]![column] as IRowValue) as IRow;', [ColumnsConst]),
    format(atom(KeyLine), '        const key = JSON.stringify(~w.map((index) => projectedRow[index]));', [IndicesConst]),
    % bindArgs again, not just at the project bind above: the projected
    % value just read back through result.rows[0] may itself be a plain JS
    % number (an INTEGER query-result column, not a TEXT one), and this
    % second bind is the one that actually writes the destination TEXT
    % column -- the same "number" -> REAL -> "N.0" hazard applies here
    % independently of the project-side fix.
    format(atom(UpsertMapLine),
           '      return [...resolved.values()].map((row): SqlStatement => ({ sql: ~w, args: bindArgs(row) }));',
           [UpsertConst]),
    FnLines =
    [ SigLine,
      FilterLine,
      % forkJoin([]) COMPLETES WITHOUT EMITTING (verified against rxjs
      % 7.8.2, not assumed) -- a drain tick, or any tick where no arrival
      % matches this trigger, has an empty triggerRows, and without this
      % guard the WHOLE tick() chain silently completes with no ITickDeltas
      % at all for that tick (a real bug caught running the emitted program
      % against the real seam, not by typecheck -- tsgo has no way to know
      % forkJoin([]) is empty-completing rather than []-emitting).
      '  if (triggerRows.length === 0) return of([]);',
      ForkLine,
      '    map((results) => {',
      '      const resolved = new Map<string, IRow>();',
      '      for (const result of results) {',
      RowLine,
      KeyLine,
      '        resolved.set(key, projectedRow);',
      '      }',
      UpsertMapLine,
      '    }),',
      '  );',
      '}'
    ].

key_indices(HeadColumns, KeyColumns, Indices) :-
    findall(Index0,
            ( member(Column, KeyColumns), nth0(Index0, HeadColumns, Column) ),
            Indices).

% ═══ level recompute ═════════════════════════════════════════════════════════
% Statements joined with the literal two-character escape sequence `\n`
% (NOT an actual newline byte in this Prolog source): embedded inside the
% backtick template literal, that text is what the JS engine itself
% interprets as a newline when the template is evaluated at runtime --
% matches Phase A's exemplar (`.join(";\n")` in real TS source, same
% escape). Keeps the emitted const a single source line.

% A program with zero level rules (every fixture whose Rules list is entirely
% edge rules, or empty outright -- e.g. an EDB-only fixture with no rules at
% all) still has run_tick_fn_lines call `recomputeLevels(seam)` unconditionally
% (that call is not itself gated on LevelStatements), so this needs a real
% zero-op function, not silent failure: `of(undefined)` is the one-void-then-
% complete shape the async-becomes-rxjs law calls for (EMPTY would complete
% without emitting, which starves the caller's `.pipe(map(() => before))` of
% a value and stalls the whole tick chain).
recompute_levels_fn_lines([], Lines) :- !,
    Lines =
    [ 'function recomputeLevels(seam: ISqlSeam): Observable<void> {',
      '  void seam;',
      '  return of(undefined);',
      '}'
    ].
recompute_levels_fn_lines(LevelStatements, Lines) :-
    LevelStatements \== [],
    % InsertSqls is a LIST (lower.pl:level_statement_group/3 -- one entry per
    % rule clause sharing this head, so a multi-clause head's rows all
    % INSERT after exactly one DELETE, never one DELETE per clause); flattens
    % to the identical [Delete, Insert] sequence as before for the common
    % single-clause case.
    findall(Sql, ( member(levelstmt(_, DeleteSql, InsertSqls), LevelStatements), ( Sql = DeleteSql ; member(Sql, InsertSqls) ) ), Sqls),
    atomic_list_concat(Sqls, ';\\n', JoinedSql),
    js_template(JoinedSql, SqlTemplate),
    format(atom(SqlLine), '  const sql = ~w;', [SqlTemplate]),
    Lines =
    [ 'function recomputeLevels(seam: ISqlSeam): Observable<void> {',
      SqlLine,
      '  return seam.runner.executeMultiple(seam.db, sql);',
      '}'
    ].

% ═══ buildDeltas ═════════════════════════════════════════════════════════════

build_deltas_fn_lines(RelPlans, EdgeStatements, Lines) :-
    maplist(diff_local_line, RelPlans, DiffLines),
    maplist(rel_entry_line, RelPlans, RelEntryLines),
    carry_pending_expr(EdgeStatements, CarryExpr),
    format(atom(CarryLine), '    carryPending: ~w,', [CarryExpr]),
    append(
        [ ['function buildDeltas(before: Snapshot, after: Snapshot): ITickDeltas {'],
          DiffLines,
          ['  return {', '    rels: ['],
          RelEntryLines,
          ['    ],', CarryLine, '  };', '}']
        ], Lines).

diff_local_line(relplan(Ref, _Kind, _Columns, _Key), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '  const ~w = multisetDiff(before.~w, after.~w);', [Name, Name, Name]).

rel_entry_line(relplan(Ref, _Kind, _Columns, _Key), Line) :-
    ref_name(Ref, Name),
    format(atom(Line), '      { rel: "~w", add: ~w.add, del: ~w.del },', [Name, Name, Name]).

% carryPending (engine.pl q4/R2): true when a row this tick's edge rule(s)
% wrote SHOWS AS A DELTA (an equal-row rewrite is invisible to multisetDiff,
% so no separate no-op check is needed here -- the diff already absorbs it).
% Simplification, matching Phase A's exemplar finding 3: this ignores the
% general "post-write level growth with no edge write" carry source, safe
% for both target fixtures because neither has a level rule reading an
% arrival-driven rel directly without an edge rule in between. A program
% with zero edge rules (demand_laziness_effect_rows) has carryPending fixed
% at `false` -- not a per-tick computation, a structural fact about that
% program shape (no rule ever writes mid-tick).
carry_pending_expr([], 'false') :- !.
carry_pending_expr(EdgeStatements, Expr) :-
    findall(Cond,
            ( member(edgestmt(HeadRef, _, _, _, _, _), EdgeStatements),
              ref_name(HeadRef, Name),
              format(atom(Cond), '~w.add.length > 0 || ~w.del.length > 0', [Name, Name]) ),
            Conds),
    atomic_list_concat(Conds, ' || ', Expr).

% ═══ tick() + program export ════════════════════════════════════════════════

run_tick_fn_lines(Name, [], Lines) :- !,
    format(atom(NameCommentLine), '  // ~w: no edge rules -- absorb arrivals, recompute levels, diff.', [Name]),
    Lines =
    [ 'function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  return readSnapshot(seam).pipe(',
      '    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),',
      '    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),',
      '    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),',
      '  );',
      NameCommentLine,
      '}'
    ].
run_tick_fn_lines(Name, EdgeStatements, Lines) :-
    EdgeStatements \== [],
    maplist(edge_resolve_call_expr, EdgeStatements, ResolveCallExprs),
    ( ResolveCallExprs = [SingleCall]
    -> format(atom(EdgeWritesExpr), '~w', [SingleCall])
    ; atomic_list_concat(ResolveCallExprs, ', ', JoinedCalls),
      format(atom(EdgeWritesExpr), 'forkJoin([~w]).pipe(map((groups) => groups.flat()))', [JoinedCalls])
    ),
    format(atom(EdgeWritesLine), '      ~w.pipe(', [EdgeWritesExpr]),
    format(atom(NameCommentLine), '  // ~w: engine.pl process_occurrences -> level_closure -> boundary_deltas.', [Name]),
    Lines =
    [ 'function runTick(seam: ISqlSeam, arrivals: IArrivalBatch): Observable<ITickDeltas> {',
      '  return readSnapshot(seam).pipe(',
      '    concatMap((before) => applyArrivals(seam, arrivals).pipe(map(() => before))),',
      '    concatMap((before) =>',
      EdgeWritesLine,
      '        concatMap((statements) => seam.runner.batch(seam.db, statements)),',
      '        map(() => before),',
      '      ),',
      '    ),',
      '    concatMap((before) => recomputeLevels(seam).pipe(map(() => before))),',
      '    concatMap((before) => readSnapshot(seam).pipe(map((after) => buildDeltas(before, after)))),',
      '  );',
      NameCommentLine,
      '}'
    ].

edge_resolve_call_expr(edgestmt(HeadRef, _, _, _, _, _), Expr) :-
    pascal_case(HeadRef, Pascal),
    format(atom(Expr), 'resolve~wWrites(seam, arrivals)', [Pascal]).

program_export_lines(Name,
    [ 'export const program: IGenProgramWithBoot = {',
      NameLine,
      '  ddl,',
      '  relColumns,',
      '  arrivalTargets,',
      '  boot,',
      '  tick: runTick,',
      '};'
    ]) :-
    format(atom(NameLine), '  name: "~w",', [Name]).

% ═══ top level ═══════════════════════════════════════════════════════════════

emit_program(Name, _Plan, Lowered, BootStatements, Text) :-
    Lowered = lowered(Name, Ddl, ArrivalStatements, EdgeStatements, LevelStatements, DeltaStatements, RelPlans, ArrivalTargets),
    header_lines(Name, HeaderLines),
    ( EdgeStatements == [] -> HasEdgeRules = false ; HasEdgeRules = true ),
    imports_lines(HasEdgeRules, ImportLines),
    local_types_lines(LocalTypeLines),
    bind_args_helper_lines(BindArgsHelperLines),
    ddl_lines(Ddl, DdlLines),
    rel_columns_lines(RelPlans, RelColumnsLines),
    arrival_targets_lines(ArrivalTargets, ArrivalTargetsLines),
    boot_lines(BootStatements, BootLines),
    snapshot_type_lines(RelPlans, SnapshotTypeLines),
    read_snapshot_fn_lines(DeltaStatements, ReadSnapshotFnLines),
    arrival_statements_lines(ArrivalStatements, ArrivalStatementsLines),
    arrival_statement_fn_lines(Name, ArrivalStatementFnLines),
    ( EdgeStatements == []
    -> EdgeConstLines = [], EdgeFnLines = []
    ; edge_resolver_blocks(EdgeStatements, EdgeConstLines, EdgeFnLines)
    ),
    recompute_levels_fn_lines(LevelStatements, RecomputeLevelsFnLines),
    build_deltas_fn_lines(RelPlans, EdgeStatements, BuildDeltasFnLines),
    run_tick_fn_lines(Name, EdgeStatements, RunTickFnLines),
    program_export_lines(Name, ProgramExportLines),
    Sections0 =
    [ HeaderLines, ImportLines, LocalTypeLines, BindArgsHelperLines, DdlLines, RelColumnsLines, ArrivalTargetsLines,
      BootLines, SnapshotTypeLines, ReadSnapshotFnLines,
      ArrivalStatementsLines, ArrivalStatementFnLines,
      EdgeConstLines, EdgeFnLines,
      RecomputeLevelsFnLines, BuildDeltasFnLines, RunTickFnLines, ProgramExportLines
    ],
    exclude(==([]), Sections0, Sections),
    maplist(lines_block, Sections, SectionTexts),
    atomic_list_concat(SectionTexts, '\n\n', Body),
    format(atom(Text), '~w\n', [Body]).
