// The single VS Code-coupling file. Everything editor-specific lives here:
// the LSP client, the flow-panel webview wrapper, and the explorer
// decorations. media/flow-panel.html is host-agnostic (it also runs in a plain
// browser against scripts/dl-bridge.mjs); this file only injects a
// `window.dlHost` bootstrap that bridges the panel's three host calls
// (query/hover/open) onto VS Code machinery.
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import * as vscode from "vscode";
import { LanguageClient, LanguageClientOptions, ServerOptions, TransportKind, State } from "vscode-languageclient/node";

let client: LanguageClient | undefined;

// Multi-root: the folder root that OWNS a file. Everything file-scoped (marks,
// type-seed, cursor rel-paths, jump-to-disk) resolves through this so a file in
// any workspace folder is handled by that folder's repo, not just folders[0].
function folderRootOf(uri: vscode.Uri, fallback: string): string {
  return vscode.workspace.getWorkspaceFolder(uri)?.uri.fsPath ?? fallback;
}

// Write the open workspace folders as `[[repos]]` into a per-workspace config,
// and hand `dl` its path via `$SPREFA_CONFIG` (config.rs search path #1). One
// daemon then serves EVERY folder as a repo (local root, no clone, no allowlist
// gate — the config-repo path), so the panel unions across all of them and
// cross-folder jump-to-disk resolves. Returns the config path, or undefined
// (single folder / no storage) to leave `dl` on its default single-root path.
// Drop a scan-all rail into `<primaryRoot>/.dl/` so the discovery convention
// (shared by the LSP and the daemon it attaches to) runs it alongside the
// existing rails. It fans extraction over EVERY configured repo (`scan("*")`)
// for each source language, so the flow panel's call/type/dataflow/module
// presets span all folders — off ONE database. Git-excluded so it never gets
// committed. A CLI run with no `$SPREFA_CONFIG` sees no config repos, so
// `scan("*")` collapses to the self repo — harmless outside the workspace.
const WS_SCAN_NAME = "_workspace-scan.dl";
function writeWorkspaceScanRail(primaryRoot: string): void {
  const railDir = path.join(primaryRoot, ".dl");
  if (!fs.existsSync(railDir)) return; // no discovery dir here; nothing to join
  const lines = [
    "# Auto-generated by the dl VS Code extension (multi-root). Fans extraction",
    "# over every open workspace folder (registered as repos via $SPREFA_CONFIG)",
    "# so the flow panel spans all repos. Git-excluded; safe to delete.",
    "",
    "rel ws_src(path: file).",
  ];
  for (const ext of ["rs", "ts", "tsx", "js", "jsx", "py", "go", "kt"]) {
    lines.push(`ws_src(path) <- scan("*", "WORK", "**/*.${ext}", path, rev).`);
  }
  lines.push("");
  fs.writeFileSync(path.join(railDir, WS_SCAN_NAME), lines.join("\n"));
  // Keep it out of git: add to <primaryRoot>/.git/info/exclude if not already.
  const exclude = path.join(primaryRoot, ".git", "info", "exclude");
  try {
    const entry = `.dl/${WS_SCAN_NAME}`;
    const cur = fs.existsSync(exclude) ? fs.readFileSync(exclude, "utf8") : "";
    if (!cur.split("\n").includes(entry)) {
      fs.appendFileSync(exclude, (cur.endsWith("\n") || cur === "" ? "" : "\n") + entry + "\n");
    }
  } catch { /* not a git repo / no perms: leave it, it's inert */ }
}

// Map a panel node's file back to a real on-disk URI across ALL workspace
// folders. A node file is either `slug/relpath` (repo-prefixed presets) or a
// bare repo-relative path (df_node etc.). Probe each folder for `<folder>/file`
// and, when the first segment names a folder, `<folder>/<rest>` — open the
// candidate that exists so jump-to-disk hits the right repo. Falls back to the
// primary root so a miss still opens *something* rather than nothing.
function resolveOpenUri(file: string, primaryRoot: string): vscode.Uri {
  const folders = vscode.workspace.workspaceFolders ?? [];
  const cands: string[] = [];
  const [head, ...tail] = file.split("/");
  for (const f of folders) {
    cands.push(path.join(f.uri.fsPath, file));
    if (tail.length && path.basename(f.uri.fsPath) === head) {
      cands.push(path.join(f.uri.fsPath, tail.join("/")));
    }
  }
  cands.push(path.join(primaryRoot, file));
  return vscode.Uri.file(cands.find((c) => fs.existsSync(c)) ?? cands[cands.length - 1]);
}

function writeWorkspaceRepoConfig(ctx: vscode.ExtensionContext): string | undefined {
  const folders = vscode.workspace.workspaceFolders ?? [];
  if (folders.length < 2) return undefined; // single-root: nothing to union
  const dir = ctx.storageUri?.fsPath;
  if (!dir) return undefined;
  fs.mkdirSync(dir, { recursive: true });
  const seen = new Set<string>();
  const lines = [
    "# Auto-generated by the dl VS Code extension: the open workspace folders as",
    "# repos, so one dl daemon serves them all (multi-root). Do not hand-edit.",
    "",
  ];
  for (const f of folders) {
    let slug = path.basename(f.uri.fsPath);
    if (seen.has(slug)) { // disambiguate colliding basenames with a parent segment
      const parent = path.basename(path.dirname(f.uri.fsPath));
      slug = `${parent}-${slug}`;
    }
    seen.add(slug);
    lines.push("[[repos]]", `slug = ${JSON.stringify(slug)}`,
      `root = ${JSON.stringify(f.uri.fsPath)}`, "");
  }
  const p = path.join(dir, "workspace-repos.toml");
  fs.writeFileSync(p, lines.join("\n"));
  return p;
}

// Install dirs a GUI-launched editor's PATH typically misses. `cargo install`
// drops `dl` in ~/.cargo/bin, which a macOS app launched from Finder/Dock does
// NOT inherit (the shell-set PATH only exists in a terminal session). Homebrew
// prefixes cover a `brew`-tapped install. Probed on disk AND prepended to the
// spawn PATH so a bare `dl` resolves too.
function dlBinDirs(): string[] {
  return [path.join(os.homedir(), ".cargo", "bin"), "/opt/homebrew/bin", "/usr/local/bin"];
}

// Resolve the `dl` command. An explicit absolute `dl.binaryPath` wins; otherwise
// probe the common install dirs on disk. `found` is false only when nothing on
// disk matched — we still return a command (the bare name, spawned against the
// augmented PATH), but the caller warns the user so a blank panel isn't a
// mystery (the #1 "installs but blank on another machine" cause).
function resolveBinary(configured: string): { command: string; found: boolean } {
  if (configured && configured !== "dl") {
    // A user-set path (absolute or a custom name): trust it, report existence.
    if (path.isAbsolute(configured)) return { command: configured, found: fs.existsSync(configured) };
    return { command: configured, found: true };
  }
  for (const dir of dlBinDirs()) {
    const cand = path.join(dir, "dl");
    if (fs.existsSync(cand)) return { command: cand, found: true };
  }
  return { command: "dl", found: false };
}

export function activate(ctx: vscode.ExtensionContext): void {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders) return;

  const cfg = vscode.workspace.getConfiguration("dl");
  const configuredBinary = cfg.get<string>("binaryPath", "dl");
  const resolved = resolveBinary(configuredBinary);
  const program = cfg.get<string>("program", "");
  const root = cfg.get<string>("root", "") || folders[0].uri.fsPath;

  if (!resolved.found) {
    void vscode.window.showErrorMessage(
      "dl: binary not found on PATH or in ~/.cargo/bin. GUI-launched editors don't " +
      "inherit your shell PATH. Install with `cargo install --git " +
      "https://github.com/hafley66/sprefa sprefa-dl`, or set `dl.binaryPath` to its full path.",
      "Open Settings",
    ).then((pick) => {
      if (pick === "Open Settings") void vscode.commands.executeCommand("workbench.action.openSettings", "dl.binaryPath");
    });
  }

  // Prepend the known install dirs so a bare `dl` (or a `dl` that shells out to
  // a sibling tool) resolves even under the truncated GUI PATH.
  const spawnEnv: Record<string, string | undefined> = {
    ...process.env,
    PATH: [...dlBinDirs(), process.env.PATH || ""].join(path.delimiter),
  };
  // Multi-root: point the LSP (and the daemon it spawns, which inherits this
  // env) at a config listing every open folder as a repo, so one engine serves
  // them all. Undefined for a single-folder workspace -> default single-root.
  const repoConfig = writeWorkspaceRepoConfig(ctx);
  if (repoConfig) spawnEnv.SPREFA_CONFIG = repoConfig;

  // Multi-root: drop a scan-all rail into the primary folder's `.dl/` discovery
  // set so BOTH the LSP and the daemon it attaches to (which discover the same
  // `.dl/*.dl` and share one cache.db) run identical multi-repo programs — one
  // database, no clobber. The rail fans extraction over every configured repo
  // (`scan("*")`) alongside the existing rails. Git-excluded so it never lands
  // in a commit.
  if (repoConfig) writeWorkspaceScanRail(root);
  // No `--root`: `dl` derives the working root from its cwd. We point the server
  // at the primary folder by spawning it with that `cwd`.
  const args = program ? [program, "--lsp"] : ["--lsp"];

  const spawnOpts = { env: spawnEnv, cwd: root };
  const serverOptions: ServerOptions = {
    run: { command: resolved.command, args, transport: TransportKind.stdio, options: spawnOpts },
    debug: { command: resolved.command, args, transport: TransportKind.stdio, options: spawnOpts },
  };

  const documentSelector: vscode.DocumentSelector = [
    { scheme: "file", language: "dl" },
    { scheme: "file", language: "rust" },
    { scheme: "file", language: "typescript" },
    { scheme: "file", language: "typescriptreact" },
    { scheme: "file", language: "javascript" },
    { scheme: "file", language: "javascriptreact" },
    { scheme: "file", language: "python" },
    { scheme: "file", language: "go" },
    { scheme: "file", language: "kotlin" },
    { scheme: "file", language: "json" },
    { scheme: "file", language: "yaml" },
    { scheme: "file", language: "toml" },
    { scheme: "file", language: "shell" },
  ];

  // No synchronize.fileEvents watcher: the server declares change:NONE and has
  // no didChangeWatchedFiles handler (it consumes didSave/didOpen only), so a
  // workspace-wide watcher here only decoded and dropped events client-side.
  const clientOptions: LanguageClientOptions = {
    documentSelector: documentSelector as { scheme: string; language: string }[],
  };

  const bar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 0);
  bar.text = "dl: starting";
  bar.show();
  ctx.subscriptions.push(bar);

  client = new LanguageClient("dlLSP", "dl LSP", serverOptions, clientOptions);
  client.onDidChangeState((e) => {
    bar.text = e.newState === State.Running ? "dl: ready" : "dl: stopped";
    bar.backgroundColor = e.newState === State.Running
      ? undefined
      : new vscode.ThemeColor("statusBarItem.warningBackground");
  });
  ctx.subscriptions.push({ dispose: () => { void client?.stop(); } });
  void client.start();

  // dl diagnostics render markdown: the LSP `Diagnostic.message` field is
  // plain-text-only (VS Code shows it verbatim), so a hover provider re-renders
  // any dl-sourced diagnostic overlapping the cursor as a MarkdownString. `.dl`
  // programs write markdown into diag's msg/hint (links, `code`, lists) and it
  // renders here on hover.
  ctx.subscriptions.push(vscode.languages.registerHoverProvider(documentSelector, {
    provideHover(document, position) {
      const hits = vscode.languages.getDiagnostics(document.uri)
        .filter((d) => d.source === "dl" && d.range.contains(position));
      if (hits.length === 0) return undefined;
      const md = new vscode.MarkdownString();
      md.isTrusted = true;
      md.supportHtml = false;
      for (const d of hits) {
        const code = typeof d.code === "object" ? d.code.value : d.code;
        if (code) md.appendMarkdown(`**\`${code}\`**\n\n`);
        // The server joins the diagnostic as "msg\nhint: h" with a SINGLE
        // newline, which markdown collapses onto one line (so any formatting
        // reads as plain). Promote the hint to its own paragraph, and turn the
        // remaining lone newlines into markdown hard breaks, so whatever
        // markdown the `.dl` wrote into msg/hint (links, `code`, lists) renders.
        const body = d.message
          .replace(/\nhint:[ \t]*/g, "\n\n**hint:** ")
          .replace(/([^\n])\n(?!\n)/g, "$1  \n");
        md.appendMarkdown(body + "\n\n");
      }
      const range = hits.reduce<vscode.Range | undefined>(
        (acc, d) => (acc ? acc.union(d.range) : d.range), undefined);
      return new vscode.Hover(md, range);
    },
  }));

  const slice = new SliceDecorations(root);
  ctx.subscriptions.push(vscode.window.registerFileDecorationProvider(slice));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.flowPanel", () => {
    openFlowPanel(ctx, root, slice);
  }));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.markSelection", () => addMark(root)));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.clearMarks", () => clearMarks(root)));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.typeSeed", () => addTypeSeed(root)));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.clearTypeSeeds", () => clearTypeSeeds(root)));
  ctx.subscriptions.push(vscode.commands.registerCommand("dl.pickDiagCode", () => toggleDiagCode()));

  // marked-line decorations: left stripe + overview-ruler tick, re-read from
  // .dl/marks.dl (same facts the engine joins) so external edits show up live
  markDecoration = vscode.window.createTextEditorDecorationType({
    isWholeLine: true,
    borderWidth: "0 0 0 3px",
    borderStyle: "solid",
    borderColor: new vscode.ThemeColor("dlFlow.slice"),
    overviewRulerColor: new vscode.ThemeColor("dlFlow.slice"),
    overviewRulerLane: vscode.OverviewRulerLane.Left,
  });
  ctx.subscriptions.push(markDecoration);
  refreshMarkDecorations(root, false);
  ctx.subscriptions.push(vscode.window.onDidChangeVisibleTextEditors(() => refreshMarkDecorations(root, false)));
  // Watch EVERY folder's .dl/marks.dl (multi-root), so a mark added in any repo
  // updates decorations live. `**/.dl/marks.dl` matches under each folder.
  const marksWatcher = vscode.workspace.createFileSystemWatcher("**/.dl/marks.dl");
  for (const on of [marksWatcher.onDidChange, marksWatcher.onDidCreate, marksWatcher.onDidDelete]) {
    ctx.subscriptions.push(on(() => refreshMarkDecorations(root, true)));
  }
  ctx.subscriptions.push(marksWatcher);
}

// ── marks: selection -> a `mark` fact the reactive engine joins against ─────
// The editor is a dumb recorder; resolution (entity? df node? shared pattern
// across marks?) is dl rules in .dl/mark-lens.dl. Facts only here — the rel
// decl lives in mark-lens.dl so an absent marks file never breaks the program.

const MARKS_HEADER =
  "# marks.dl — written by the dl VS Code extension (dl.markSelection / dl.clearMarks).\n" +
  "# Facts only; `rel mark(marked: text, path: file, line: int).` is declared in mark-lens.dl.\n";

function marksPath(root: string): string {
  return path.join(root, ".dl", "marks.dl");
}

function addMark(primaryRoot: string): void {
  const ed = vscode.window.activeTextEditor;
  if (!ed) return;
  // Mark the file into ITS OWN folder's .dl/marks.dl (multi-root), not folders[0].
  const root = folderRootOf(ed.document.uri, primaryRoot);
  const sel = ed.selection;
  const text = (sel.isEmpty
    ? ed.document.getText(ed.document.getWordRangeAtPosition(sel.active))
    : ed.document.getText(sel)).trim();
  if (!text) { void vscode.window.showWarningMessage("dl: nothing selected to mark"); return; }
  const rel = path.relative(root, ed.document.uri.fsPath).replace(/\\/g, "/");
  if (rel.startsWith("..")) { void vscode.window.showWarningMessage("dl: file is outside the scan root"); return; }
  const line = sel.active.line + 1; // dl lines are 1-based
  const fact = `mark(${JSON.stringify(text)}, ${JSON.stringify(rel)}, ${line}).\n`;
  const p = marksPath(root);
  const cur = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : MARKS_HEADER;
  if (!cur.includes(fact)) fs.writeFileSync(p, cur + fact);
  refreshMarkDecorations(root, false);
  vscode.window.setStatusBarMessage(`dl mark: ${text} @ ${rel}:${line}`, 3000);
}

function clearMarks(primaryRoot: string): void {
  const ed = vscode.window.activeTextEditor;
  const root = ed ? folderRootOf(ed.document.uri, primaryRoot) : primaryRoot;
  fs.writeFileSync(marksPath(root), MARKS_HEADER);
  refreshMarkDecorations(primaryRoot, false);
  vscode.window.setStatusBarMessage("dl marks cleared", 3000);
}

// ── type seeds: a selected type name -> a type_seed fact the "Type neighbors"
//    panel preset joins against. Same shape as marks (facts-only file, decl
//    lives in .dl/flow-panel.dl so an empty file is harmless). The seed
//    resolves to sym(s) by type_entity name inside dl, so the editor writes the
//    bare selected text — no sym lookup or LSP round-trip needed here.

const TYPE_SEEDS_HEADER =
  "# type-seed.dl — written by the dl VS Code extension (dl.typeSeed / cmd+alt+t).\n" +
  "# Facts only; `rel type_seed(seed: text).` is declared in flow-panel.dl.\n";

function typeSeedsPath(root: string): string {
  return path.join(root, ".dl", "type-seed.dl");
}

function addTypeSeed(primaryRoot: string): void {
  const ed = vscode.window.activeTextEditor;
  if (!ed) return;
  // Seed into the active file's OWN folder (multi-root).
  const root = folderRootOf(ed.document.uri, primaryRoot);
  const sel = ed.selection;
  const text = (sel.isEmpty
    ? ed.document.getText(ed.document.getWordRangeAtPosition(sel.active))
    : ed.document.getText(sel)).trim();
  if (!text) { void vscode.window.showWarningMessage("dl: nothing selected to seed"); return; }
  const fact = `type_seed(${JSON.stringify(text)}).\n`;
  const p = typeSeedsPath(root);
  const cur = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : TYPE_SEEDS_HEADER;
  if (!cur.includes(fact)) fs.writeFileSync(p, cur + fact);
  vscode.window.setStatusBarMessage(`dl type seed: ${text}`, 3000);
}

function clearTypeSeeds(primaryRoot: string): void {
  const ed = vscode.window.activeTextEditor;
  const root = ed ? folderRootOf(ed.document.uri, primaryRoot) : primaryRoot;
  fs.writeFileSync(typeSeedsPath(root), TYPE_SEEDS_HEADER);
  vscode.window.setStatusBarMessage("dl type seeds cleared", 3000);
}

// ── mark line decorations: stripe + ruler tick on every marked line ─────────
// Rendered straight from the marks.dl facts (`mark("text", "rel/path", line).`)
// rather than editor state, so marks survive window reloads and lines marked
// by other tooling appear too. The fields are JSON string literals (that is
// how addMark writes them), so a JSON-string regex + JSON.parse round-trips
// any escaping exactly.

let markDecoration: vscode.TextEditorDecorationType | undefined;
const MARK_FACT = /^mark\("((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)",\s*(\d+)\)\.$/;

function parseMarks(root: string): { byFile: Map<string, number[]>; count: number } {
  const byFile = new Map<string, number[]>();
  let count = 0;
  const p = marksPath(root);
  if (!fs.existsSync(p)) return { byFile, count };
  for (const row of fs.readFileSync(p, "utf8").split("\n")) {
    const m = MARK_FACT.exec(row.trim());
    if (!m) continue;
    const rel = JSON.parse(`"${m[2]}"`) as string;
    if (!byFile.has(rel)) byFile.set(rel, []);
    byFile.get(rel)!.push(Number(m[3]));
    count++;
  }
  return { byFile, count };
}

function refreshMarkDecorations(primaryRoot: string, announce: boolean): void {
  if (!markDecoration) return;
  // Each visible editor reads ITS OWN folder's marks.dl (multi-root). Parse a
  // folder's marks once, keyed by root, then match each editor's folder-relative
  // path against them.
  const byRoot = new Map<string, ReturnType<typeof parseMarks>>();
  let count = 0;
  for (const ed of vscode.window.visibleTextEditors) {
    const root = folderRootOf(ed.document.uri, primaryRoot);
    let parsed = byRoot.get(root);
    if (!parsed) { parsed = parseMarks(root); byRoot.set(root, parsed); count += parsed.count; }
    const rel = path.relative(root, ed.document.uri.fsPath).replace(/\\/g, "/");
    const lines = parsed.byFile.get(rel) ?? [];
    ed.setDecorations(markDecoration, lines.map((l) => {
      const i = Math.max(0, Math.min(l - 1, ed.document.lineCount - 1)); // marks are 1-based
      return new vscode.Range(i, 0, i, 0);
    }));
  }
  if (announce) vscode.window.setStatusBarMessage(`dl marks: ${count}`, 3000);
}

// ── diagnostic muting: a session/db-scoped affordance ───────────────────────
// The server owns the mute set (`diag_mute` rel). This command lists the codes
// currently in `diag` (each with its muted state) via `dl.listDiagCodes`, shows
// a quick-pick, and toggles the chosen one via `dl.toggleDiagCode`. The server
// republishes with muted codes filtered out. Muting never affects `dl --check`
// (documented in docs/lsp.md).

interface DiagCodeState { code: string; muted: boolean; }

async function toggleDiagCode(): Promise<void> {
  if (!client) { void vscode.window.showWarningMessage("dl: language server not running"); return; }
  let states: DiagCodeState[];
  try {
    states = await client.sendRequest<DiagCodeState[]>("workspace/executeCommand", {
      command: "dl.listDiagCodes", arguments: [],
    });
  } catch (e) {
    void vscode.window.showErrorMessage(`dl: could not list diagnostic codes: ${String((e as Error).message ?? e)}`);
    return;
  }
  if (!states || states.length === 0) {
    void vscode.window.showInformationMessage("dl: no diagnostic codes to mute");
    return;
  }
  const items = states.map((s) => ({
    label: `${s.muted ? "$(check) " : ""}${s.code}`,
    description: s.muted ? "muted — select to un-mute" : "select to mute",
    code: s.code,
  }));
  const pick = await vscode.window.showQuickPick(items, {
    placeHolder: "Toggle a diagnostic code (muting is session-scoped, never affects --check)",
  });
  if (!pick) return;
  try {
    const res = await client.sendRequest<{ code: string; muted: boolean }>("workspace/executeCommand", {
      command: "dl.toggleDiagCode", arguments: [pick.code],
    });
    vscode.window.setStatusBarMessage(
      `dl: ${res.code} ${res.muted ? "muted" : "un-muted"}`, 3000);
  } catch (e) {
    void vscode.window.showErrorMessage(`dl: toggle failed: ${String((e as Error).message ?? e)}`);
  }
}

export function deactivate(): Thenable<void> | undefined {
  return client?.stop();
}

/** Explorer highlight for the hovered graph slice: badge + theme color on the
 *  slice's files, propagated up their parent folders. `set([])` clears. */
class SliceDecorations implements vscode.FileDecorationProvider {
  private files = new Set<string>();
  private emitter = new vscode.EventEmitter<vscode.Uri[] | undefined>();
  readonly onDidChangeFileDecorations = this.emitter.event;

  constructor(private root: string) {}

  set(relFiles: string[]): void {
    const next = new Set(relFiles.map((f) => path.join(this.root, f)));
    const touched = [...this.files, ...next].map((p) => vscode.Uri.file(p));
    this.files = next;
    this.emitter.fire(touched.length ? touched : undefined);
  }

  provideFileDecoration(uri: vscode.Uri): vscode.FileDecoration | undefined {
    if (!this.files.has(uri.fsPath)) return undefined;
    const d = new vscode.FileDecoration("◆", "dl flow slice", new vscode.ThemeColor("dlFlow.slice"));
    d.propagate = true;
    return d;
  }
}

let panel: vscode.WebviewPanel | undefined;

function openFlowPanel(ctx: vscode.ExtensionContext, root: string, slice: SliceDecorations): void {
  if (panel) { panel.reveal(); return; }
  panel = vscode.window.createWebviewPanel("dlFlow", "dl flow", vscode.ViewColumn.Beside, {
    enableScripts: true,
    retainContextWhenHidden: true,
    localResourceRoots: [vscode.Uri.file(path.join(ctx.extensionPath, "media"))],
  });
  // Follow the editor cursor: post the caret's file:line + word-under-caret to
  // the webview on every selection change (debounced). The panel's "follow
  // cursor" toggle decides whether to act on it — highlight + center the node
  // at that location. Disposed with the panel.
  let cursorTimer: ReturnType<typeof setTimeout> | undefined;
  const selSub = vscode.window.onDidChangeTextEditorSelection((e) => {
    if (!panel) return;
    const doc = e.textEditor.document;
    // Rel-path against the file's OWN workspace folder (multi-root). A node's
    // file is `slug/relpath`; the panel's findNodeAt suffix-matches, so posting
    // the folder-relative path lands on the right node in any folder.
    const rel = path.relative(folderRootOf(doc.uri, root), doc.uri.fsPath).replace(/\\/g, "/");
    if (rel.startsWith("..")) return; // outside every workspace folder
    const pos = e.selections[0]?.active;
    if (!pos) return;
    const wr = doc.getWordRangeAtPosition(pos);
    const word = wr ? doc.getText(wr) : "";
    if (cursorTimer) clearTimeout(cursorTimer);
    cursorTimer = setTimeout(() => {
      void panel?.webview.postMessage({ type: "cursor", file: rel, line: pos.line + 1, word });
    }, 120);
  });

  panel.onDidDispose(() => {
    if (cursorTimer) clearTimeout(cursorTimer);
    selSub.dispose();
    panel = undefined;
    slice.set([]);
  }, null, ctx.subscriptions);

  // The dlHost bootstrap replaces the panel's HTTP fallback: query rides the
  // LSP custom request `dl/query`; hover and open post back to this file.
  const bootstrap = `<script>window.dlHost = (() => {
    const vscode = acquireVsCodeApi();
    const pending = new Map(); let seq = 0;
    window.addEventListener('message', e => {
      const m = e.data;
      if ((m.type === 'rows' || m.type === 'error') && pending.has(m.id)) {
        const p = pending.get(m.id); pending.delete(m.id);
        // Surface the server's true row count as a property on the resolved
        // array (rows stays a plain any[][] everywhere else it's consumed).
        if (m.type === 'rows') { const rows = m.rows; rows.total = m.total; p.resolve(rows); }
        else p.reject(new Error(m.message));
      } else if (m.type === 'cursor' && window.__dlCursor) {
        window.__dlCursor(m);
      }
    });
    return {
      // opts.limit threads through to dl/query's optional limit param; the
      // server truncates server-side and the true count comes back as total.
      query: (sql, params = [], opts = {}) => new Promise((resolve, reject) => {
        const id = ++seq; pending.set(id, { resolve, reject });
        vscode.postMessage({ type: 'query', id, sql, params, limit: opts.limit });
      }),
      hover: files => vscode.postMessage({ type: 'hover', files }),
      open: (file, line) => vscode.postMessage({ type: 'open', file, line }),
    };
  })();</script>`;
  const html = fs.readFileSync(path.join(ctx.extensionPath, "media", "flow-panel.html"), "utf8");
  // Bundled graph engine: cytoscape is vendored into media/ (CSP blocks CDNs)
  // and loaded before the panel's own script so `window.cytoscape` is ready.
  const cyUri = panel.webview.asWebviewUri(
    vscode.Uri.file(path.join(ctx.extensionPath, "media", "cytoscape.min.js")));
  panel.webview.html = html
    .replace("<!-- DL_CYTOSCAPE -->", `<script src="${cyUri}"></script>`)
    .replace("<!-- DL_HOST -->", bootstrap);

  panel.webview.onDidReceiveMessage(async (m) => {
    if (m.type === "query") {
      try {
        // m.limit (dl/query's optional {limit,offset,count} params) forwards
        // only when the panel sent one; omitting it keeps old-server behavior.
        const result: { rows: unknown[][]; total?: number } = await client!.sendRequest("dl/query", {
          sql: m.sql, params: m.params ?? [], ...(m.limit != null ? { limit: m.limit } : {}),
        });
        // Guard the postMessage boundary: a giant result (custom SQL with no
        // LIMIT over a multi-repo db) serializes into the webview and OOMs the
        // renderer. Cap the crossing; the panel still slices to a renderable
        // count below and shows the true total. Prefer the server's own total
        // (accurate even when `limit` already truncated result.rows) over the
        // pre-cap length, for a server that hasn't grown `total` yet.
        const QUERY_ROW_CAP = 20000;
        const all = result.rows ?? [];
        const rows = all.length > QUERY_ROW_CAP ? all.slice(0, QUERY_ROW_CAP) : all;
        void panel?.webview.postMessage({ type: "rows", id: m.id, rows, total: result.total ?? all.length });
      } catch (e) {
        void panel?.webview.postMessage({ type: "error", id: m.id, message: String((e as Error).message ?? e) });
      }
    } else if (m.type === "hover") {
      slice.set(m.files ?? []);
    } else if (m.type === "open") {
      const uri = resolveOpenUri(String(m.file), root);
      const line = Math.max(0, (Number(m.line) || 1) - 1);
      const doc = await vscode.workspace.openTextDocument(uri);
      await vscode.window.showTextDocument(doc, {
        viewColumn: vscode.ViewColumn.One,
        selection: new vscode.Range(line, 0, line, 0),
      });
    }
  }, null, ctx.subscriptions);
}
