[package]
name    = "pipeline"
version = "0.0.0"
edition.workspace = true
publish.workspace = true
build   = "build.rs"

[dependencies]
effect_runtime = { path = "../effect_runtime" }
sprefa_macros  = { path = "../sprefa_macros" }
tokio          = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tree-sitter    = "0.24"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }

[build-dependencies]
cc = "1"
