[package]
name    = "pipeline"
version = "0.0.0"
edition.workspace = true
publish.workspace = true
build   = "build.rs"

[dependencies]
ast-grep-core     = "0.36"
ast-grep-language = { version = "0.36", default-features = false, features = ["builtin-parser", "tree-sitter-rust", "tree-sitter-typescript", "tree-sitter-c"] }
effect_runtime    = { path = "../effect_runtime" }
globset           = "0.4"
regex             = "1"
rustc-hash        = "2"
sprefa_macros     = { path = "../sprefa_macros" }
tokio             = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-stream      = { version = "0.1", features = ["sync"] }
tree-sitter       = "0.24"
tree-sitter-json    = "0.24"
tree-sitter-yaml    = "0.7"
tree-sitter-toml-ng = "0.7"
futures           = "0.3"
rayon             = "1"


[dev-dependencies]
sprefa_parse          = { path = "../sprefa_parse" }
tree-sitter-sprefa    = { path = "../tree-sitter-sprefa" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }

[build-dependencies]
cc = "1"
