[workspace]

[package]
name = "macro_expand_lab"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ra_ap_syntax = "0.0.349"
ra_ap_mbe = "0.0.349"
ra_ap_tt = "0.0.349"
ra_ap_parser = "0.0.349"
ra_ap_span = "0.0.349"
ra_ap_syntax-bridge = "0.0.349"
ra_ap_intern = "0.0.349"
salsa = { version = "0.28.2", default-features = false, features = ["macros", "rayon"] }
ra_ap_hir_expand = "0.0.349"
ra_ap_base_db = "0.0.349"

[profile.release]
debug = false
