[package]
name = "sprefa_sprf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
winnow = "0.7"
anyhow = { workspace = true }
sprefa_rules = { path = "../rules" }
sprefa_extract = { path = "../extract" }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
globset = { workspace = true }
walkdir = { workspace = true }
regex = { workspace = true }
sha2 = "0.10"
log = "0.4"

[dev-dependencies]
insta = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true }
sprefa_extract = { path = "../extract" }
sprefa_cache = { path = "../cache" }
sprefa_schema = { path = "../schema" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
