//! `dl docs [topic]` — read the guides baked into the binary, so a bare
//! prebuilt download is self-documenting with no source tree on disk. Same
//! `include_str!`-the-asset pattern as `setup`/`corpus`; same pre-clap
//! intercept in `main.rs` as `examples`.
//!
//!   dl docs                     list the topics (reference pages + book + tutorial)
//!   dl docs syntax              print one reference page to stdout (plain cat)
//!   dl docs book                print the book index
//!   dl docs book 3              print book chapter 3 (by number)
//!   dl docs 03-the-cycle-problem  print a chapter by its slug
//!   dl docs tutorial            print the hands-on tutorial index
//!   dl docs tutorial 2          print tutorial lesson 2
//!
//! Reference pages under `docs/reference/*.md` are GENERATED (examples/gen-
//! reference.dl regenerates them). `include_str!` embeds whatever is committed
//! at build time; the read here never writes them back.

use anyhow::Result;

// The rules survival guide: the same skill body `dl setup --print` dumps,
// re-exported (not re-embedded) so `dl docs authoring` reads it too.
const AUTHORING: &str = crate::setup::SKILL_MD;

// Reference pages (generated; embedded read-only).
const SYNTAX: &str = include_str!("../docs/reference/syntax.md");
const FUNCTIONS: &str = include_str!("../docs/reference/functions.md");
const RELATIONS: &str = include_str!("../docs/reference/relations.md");
const EXAMPLES: &str = include_str!("../docs/reference/examples.md");

// The book: README.md is the index, then chapters 0..=8. The chapter consts +
// the CHAPTERS/LESSONS tables below are GENERATED by examples/gen-doc-indexes.dl
// (scan of book/*.md + book/tutorial/*.md); edit that program, then regen. The
// zones between the `// BEGIN: gen …` / `// END: gen …` markers are spliced.
const BOOK_INDEX: &str = include_str!("../book/README.md");
// BEGIN: gen chapter-consts
const CHAPTER_00: &str = include_str!("../book/00-a-calmer-frame.md");
const CHAPTER_01: &str = include_str!("../book/01-facts-and-rules.md");
const CHAPTER_02: &str = include_str!("../book/02-recursion-and-fixpoint.md");
const CHAPTER_03: &str = include_str!("../book/03-the-cycle-problem.md");
const CHAPTER_04: &str = include_str!("../book/04-incremental-maintenance.md");
const CHAPTER_05: &str = include_str!("../book/05-where-bytes-live.md");
const CHAPTER_06: &str = include_str!("../book/06-gold-standards-and-your-engine.md");
const CHAPTER_07: &str = include_str!("../book/07-the-fast-paths.md");
const CHAPTER_08: &str = include_str!("../book/08-argmax-and-friends.md");
// END: gen chapter-consts

// The hands-on tutorial: README.md is the track index, then lessons 0..=8.
const TUTORIAL_INDEX: &str = include_str!("../book/tutorial/README.md");
// BEGIN: gen lesson-consts
const LESSON_00: &str = include_str!("../book/tutorial/00-setup.md");
const LESSON_01: &str = include_str!("../book/tutorial/01-first-facts.md");
const LESSON_02: &str = include_str!("../book/tutorial/02-extraction.md");
const LESSON_03: &str = include_str!("../book/tutorial/03-join-and-derived.md");
const LESSON_04: &str = include_str!("../book/tutorial/04-graphs-for-free.md");
const LESSON_05: &str = include_str!("../book/tutorial/05-negation-and-argmax.md");
const LESSON_06: &str = include_str!("../book/tutorial/06-make-it-a-rail.md");
const LESSON_07: &str = include_str!("../book/tutorial/07-make-it-write.md");
const LESSON_08: &str = include_str!("../book/tutorial/08-where-next.md");
// END: gen lesson-consts

/// A reference page: CLI topic name, one-line blurb, embedded body.
const REFERENCE: &[(&str, &str, &str)] = &[
    ("authoring", "the rules survival guide: the constraints that bite + language matrix", AUTHORING),
    ("syntax", "the language surface: source ops, body constructs, sinks", SYNTAX),
    ("functions", "scalar functions callable in a rule head or comparison", FUNCTIONS),
    ("relations", "every built-in relation the engine exposes", RELATIONS),
    ("examples", "one-line summary of every program under examples/", EXAMPLES),
];

/// A book chapter: number, slug, one-line blurb, embedded body.
const CHAPTERS: &[(u32, &str, &str, &str)] = &[
    // BEGIN: gen chapters-table
    (0, "00-a-calmer-frame", "the arc of how this got built, v4 sorrow vs v5 calm, and biasing toward easier times. Read when you are in the pit.", CHAPTER_00),
    (1, "01-facts-and-rules", "datalog from zero: facts, rules, joins, anti-joins, source vs derived.", CHAPTER_01),
    (2, "02-recursion-and-fixpoint", "transitive closure, the frontier, why it terminates.", CHAPTER_02),
    (3, "03-the-cycle-problem", "self-support, why counting breaks, time vs structure, SCC condensation.", CHAPTER_03),
    (4, "04-incremental-maintenance", "inserts vs deletes, ownership, the source/derived split.", CHAPTER_04),
    (5, "05-where-bytes-live", "storage engines vs databases, the bounded-RSS discipline, the zoo.", CHAPTER_05),
    (6, "06-gold-standards-and-your-engine", "Glean, Zoekt, and how `dl` is the same ideas.", CHAPTER_06),
    (7, "07-the-fast-paths", "the loops that make it scale: semi-naive fixpoint, Tarjan/condensation, seeded reachability, stratification, auto-index, with citations and exercises.", CHAPTER_07),
    (8, "08-argmax-and-friends", "max vs argmax, the candidates/beaten/winner negation shape, per-key vs per-row grouping, the `key(...) merge(MaxBy(...))` lattice shortcut, and the SQL it lowers to.", CHAPTER_08),
    // END: gen chapters-table
];

/// A tutorial lesson: number, one-line blurb, embedded body. Addressed only
/// through `dl docs tutorial [N]` (no slug form; lesson slugs would collide
/// with book chapter slugs on the bare-number path).
const LESSONS: &[(u32, &str, &str)] = &[
    // BEGIN: gen lessons-table
    (0, "install `dl`, build the fixture repo, meet `dl docs` and `dl examples`.", LESSON_00),
    (1, "a bare `scan`, the `file` relation, the `(repo, path, rev)` coordinate.", LESSON_01),
    (2, "`match` with a regex capture, then the same thing with `ast`/`sg`; when to use which; metavars and `$$$`.", LESSON_02),
    (3, "two source relations joined into a third derived one, and the one-relation-one-rule-kind law shown by triggering the engine's bail.", LESSON_03),
    (4, "`type_entity` and `call_edge` off the same scan; blast radius with a recursive rule; why you seed a recursive rule instead of reading `closure()` unpinned.", LESSON_04),
    (5, "newest-per-group with the candidate / beaten / winner shape.", LESSON_05),
    (6, "`diag` rows, `--check` exit codes, the `--lsp` one-liner.", LESSON_06),
    (7, "a `gen` splice into a markdown file, and the marker discipline.", LESSON_07),
    (8, "the examples browser, the book, the `std/` libs, the reference.", LESSON_08),
    // END: gen lessons-table
];

/// Resolve a chapter selector (a bare number like `3` or a slug like
/// `03-the-cycle-problem`, with or without the numeric prefix) to its body.
fn chapter_body(selector: &str) -> Option<&'static str> {
    let wanted = selector.trim_end_matches(".md");
    if let Ok(number) = wanted.parse::<u32>() {
        return CHAPTERS.iter().find(|(n, ..)| *n == number).map(|(.., body)| *body);
    }
    CHAPTERS.iter()
        .find(|(_, slug, ..)| *slug == wanted || slug.trim_start_matches(|c: char| c.is_ascii_digit() || c == '-') == wanted)
        .map(|(.., body)| *body)
}

/// The topic listing printed by bare `dl docs` (and on an unknown topic).
fn print_topics() {
    println!("dl docs — read the embedded guides (plain stdout, no pager)\n");
    println!("REFERENCE   (dl docs <topic>)");
    for (name, blurb, _) in REFERENCE {
        println!("  {name:<12}{blurb}");
    }
    println!("\nTHE BOOK    (dl docs book [N]  |  dl docs <NN-slug>)");
    println!("  {:<12}{}", "book", "the index; add a chapter number or slug to read one");
    for (number, _, blurb, _) in CHAPTERS {
        println!("  {number:<12}{blurb}");
    }
    println!("\nTUTORIAL    (dl docs tutorial [N] — hands-on, type-along track)");
    println!("  {:<12}{}", "tutorial", "the track index; add a lesson number to read one");
    for (number, blurb, _) in LESSONS {
        println!("  {number:<12}{blurb}");
    }
    println!("\naddress a chapter as `dl docs book 3` or `dl docs 03-the-cycle-problem`;");
    println!("a lesson as `dl docs tutorial 2`.");
}

/// `dl docs …`. Returns the process exit code.
pub fn run(args: &[String]) -> Result<i32> {
    let topic = match args.first() {
        None => { print_topics(); return Ok(0); }
        Some(t) => t.as_str(),
    };
    if topic == "-h" || topic == "--help" {
        print_topics();
        return Ok(0);
    }
    if topic == "book" {
        match args.get(1) {
            None => { print!("{BOOK_INDEX}"); return Ok(0); }
            Some(selector) => match chapter_body(selector) {
                Some(body) => { print!("{body}"); return Ok(0); }
                None => {
                    eprintln!("dl docs: no book chapter {selector:?}\n");
                    print_topics();
                    return Ok(1);
                }
            },
        }
    }
    if topic == "tutorial" {
        match args.get(1) {
            None => { print!("{TUTORIAL_INDEX}"); return Ok(0); }
            Some(selector) => {
                let lesson = selector.trim_end_matches(".md").parse::<u32>().ok()
                    .and_then(|number| LESSONS.iter().find(|(n, ..)| *n == number));
                match lesson {
                    Some((.., body)) => { print!("{body}"); return Ok(0); }
                    None => {
                        eprintln!("dl docs: no tutorial lesson {selector:?}\n");
                        print_topics();
                        return Ok(1);
                    }
                }
            }
        }
    }
    if let Some((.., body)) = REFERENCE.iter().find(|(name, ..)| *name == topic) {
        print!("{body}");
        return Ok(0);
    }
    if let Some(body) = chapter_body(topic) {
        print!("{body}");
        return Ok(0);
    }
    eprintln!("dl docs: unknown topic {topic:?}\n");
    print_topics();
    Ok(1)
}
