[package]
name = "sprefa_sprf_lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sprf-lsp"
path = "src/main.rs"

[dependencies]
tower-lsp = { workspace = true }
tokio = { workspace = true }
sprefa_sprf = { path = "../sprf" }
sprefa_rules = { path = "../rules" }
sprefa_config = { path = "../config" }
serde_json = { workspace = true }
anyhow = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"] }
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
tempfile = { workspace = true }
